/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "../../../asn1/PKIX1Explicit88.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "AdministrationDomainName.h"

asn_TYPE_member_t asn_MBR_AdministrationDomainName_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AdministrationDomainName, choice.numeric),
		(ASN_TAG_CLASS_UNIVERSAL | (18 << 2)),
		0,
		&asn_DEF_NumericString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numeric"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AdministrationDomainName, choice.printable),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"printable"
		},
};
static const ber_tlv_tag_t asn_DEF_AdministrationDomainName_tags_1[] = {
	(ASN_TAG_CLASS_APPLICATION | (2 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AdministrationDomainName_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (18 << 2)), 0, 0, 0 }, /* numeric */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 1, 0, 0 } /* printable */
};
asn_CHOICE_specifics_t asn_SPC_AdministrationDomainName_specs_1 = {
	sizeof(struct AdministrationDomainName),
	offsetof(struct AdministrationDomainName, _asn_ctx),
	offsetof(struct AdministrationDomainName, present),
	sizeof(((struct AdministrationDomainName *)0)->present),
	asn_MAP_AdministrationDomainName_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_AdministrationDomainName = {
	"AdministrationDomainName",
	"AdministrationDomainName",
	&asn_OP_CHOICE,
	asn_DEF_AdministrationDomainName_tags_1,
	sizeof(asn_DEF_AdministrationDomainName_tags_1)
		/sizeof(asn_DEF_AdministrationDomainName_tags_1[0]), /* 1 */
	asn_DEF_AdministrationDomainName_tags_1,	/* Same as above */
	sizeof(asn_DEF_AdministrationDomainName_tags_1)
		/sizeof(asn_DEF_AdministrationDomainName_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_AdministrationDomainName_1,
	2,	/* Elements count */
	&asn_SPC_AdministrationDomainName_specs_1	/* Additional specs */
};

