/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_AlgoParameter_H_
#define	_AlgoParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <OCTET_STRING.h>
#include "UInt8.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AlgoParameter__algorithmID {
	AlgoParameter__algorithmID_milenage	= 1,
	AlgoParameter__algorithmID_tuak	= 2,
	AlgoParameter__algorithmID_usim_test_algorithm	= 3
} e_AlgoParameter__algorithmID;

/* AlgoParameter */
typedef struct AlgoParameter {
	long	 algorithmID;
	OCTET_STRING_t	 algorithmOptions;
	OCTET_STRING_t	 key;
	OCTET_STRING_t	 opc;
	OCTET_STRING_t	*rotationConstants	/* DEFAULT '4000204060'HH */;
	OCTET_STRING_t	*xoringConstants	/* DEFAULT '0000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000020000000000000000000000000000000400000000000000000000000000000008'HH */;
	OCTET_STRING_t	*authCounterMax	/* OPTIONAL */;
	UInt8_t	*numberOfKeccak	/* DEFAULT 1 */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AlgoParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AlgoParameter;
extern asn_SEQUENCE_specifics_t asn_SPC_AlgoParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_AlgoParameter_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _AlgoParameter_H_ */
#include <asn_internal.h>
