/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "AlgoParameter.h"

static int asn_DFL_12_cmp_1(const void *sptr) {
	const UInt8_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 1 */
	return (*st != 1);
}
static int asn_DFL_12_set_1(void **sptr) {
	UInt8_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 1 */
	*st = 1;
	return 0;
}
asn_TYPE_member_t asn_MBR_AlgoParameter_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct AlgoParameter, algorithmID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"algorithmID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlgoParameter, algorithmOptions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"algorithmOptions"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlgoParameter, key),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"key"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AlgoParameter, opc),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"opc"
		},
	{ ATF_POINTER, 4, offsetof(struct AlgoParameter, rotationConstants),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rotationConstants"
		},
	{ ATF_POINTER, 3, offsetof(struct AlgoParameter, xoringConstants),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"xoringConstants"
		},
	{ ATF_POINTER, 2, offsetof(struct AlgoParameter, authCounterMax),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authCounterMax"
		},
	{ ATF_POINTER, 1, offsetof(struct AlgoParameter, numberOfKeccak),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UInt8,
		0,
		{ 0, 0, 0 },
		&asn_DFL_12_cmp_1,	/* Compare DEFAULT 1 */
		&asn_DFL_12_set_1,	/* Set DEFAULT 1 */
		"numberOfKeccak"
		},
};
static const ber_tlv_tag_t asn_DEF_AlgoParameter_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AlgoParameter_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* algorithmID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* algorithmOptions */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* key */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* opc */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* rotationConstants */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* xoringConstants */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* authCounterMax */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* numberOfKeccak */
};
asn_SEQUENCE_specifics_t asn_SPC_AlgoParameter_specs_1 = {
	sizeof(struct AlgoParameter),
	offsetof(struct AlgoParameter, _asn_ctx),
	asn_MAP_AlgoParameter_tag2el_1,
	8,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	8,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AlgoParameter = {
	"AlgoParameter",
	"AlgoParameter",
	&asn_OP_SEQUENCE,
	asn_DEF_AlgoParameter_tags_1,
	sizeof(asn_DEF_AlgoParameter_tags_1)
		/sizeof(asn_DEF_AlgoParameter_tags_1[0]), /* 1 */
	asn_DEF_AlgoParameter_tags_1,	/* Same as above */
	sizeof(asn_DEF_AlgoParameter_tags_1)
		/sizeof(asn_DEF_AlgoParameter_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_AlgoParameter_1,
	8,	/* Elements count */
	&asn_SPC_AlgoParameter_specs_1	/* Additional specs */
};

