/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ApplicationSystemParameters.h"

asn_TYPE_member_t asn_MBR_ApplicationSystemParameters_1[] = {
	{ ATF_POINTER, 12, offsetof(struct ApplicationSystemParameters, volatileMemoryQuotaC7),
		(ASN_TAG_CLASS_PRIVATE | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"volatileMemoryQuotaC7"
		},
	{ ATF_POINTER, 11, offsetof(struct ApplicationSystemParameters, nonVolatileMemoryQuotaC8),
		(ASN_TAG_CLASS_PRIVATE | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonVolatileMemoryQuotaC8"
		},
	{ ATF_POINTER, 10, offsetof(struct ApplicationSystemParameters, globalServiceParameters),
		(ASN_TAG_CLASS_PRIVATE | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"globalServiceParameters"
		},
	{ ATF_POINTER, 9, offsetof(struct ApplicationSystemParameters, implicitSelectionParameter),
		(ASN_TAG_CLASS_PRIVATE | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"implicitSelectionParameter"
		},
	{ ATF_POINTER, 8, offsetof(struct ApplicationSystemParameters, volatileReservedMemory),
		(ASN_TAG_CLASS_PRIVATE | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"volatileReservedMemory"
		},
	{ ATF_POINTER, 7, offsetof(struct ApplicationSystemParameters, nonVolatileReservedMemory),
		(ASN_TAG_CLASS_PRIVATE | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonVolatileReservedMemory"
		},
	{ ATF_POINTER, 6, offsetof(struct ApplicationSystemParameters, ts102226SIMFileAccessToolkitParameter),
		(ASN_TAG_CLASS_PRIVATE | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ts102226SIMFileAccessToolkitParameter"
		},
	{ ATF_POINTER, 5, offsetof(struct ApplicationSystemParameters, ts102226AdditionalContactlessParameters),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TS102226AdditionalContactlessParameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ts102226AdditionalContactlessParameters"
		},
	{ ATF_POINTER, 4, offsetof(struct ApplicationSystemParameters, contactlessProtocolParameters),
		(ASN_TAG_CLASS_PRIVATE | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"contactlessProtocolParameters"
		},
	{ ATF_POINTER, 3, offsetof(struct ApplicationSystemParameters, userInteractionContactlessParameters),
		(ASN_TAG_CLASS_PRIVATE | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"userInteractionContactlessParameters"
		},
	{ ATF_POINTER, 2, offsetof(struct ApplicationSystemParameters, cumulativeGrantedVolatileMemory),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cumulativeGrantedVolatileMemory"
		},
	{ ATF_POINTER, 1, offsetof(struct ApplicationSystemParameters, cumulativeGrantedNonVolatileMemory),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cumulativeGrantedNonVolatileMemory"
		},
};
static const ber_tlv_tag_t asn_DEF_ApplicationSystemParameters_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ApplicationSystemParameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 7, 0, 0 }, /* ts102226AdditionalContactlessParameters */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 10, 0, 0 }, /* cumulativeGrantedVolatileMemory */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 11, 0, 0 }, /* cumulativeGrantedNonVolatileMemory */
    { (ASN_TAG_CLASS_PRIVATE | (7 << 2)), 0, 0, 0 }, /* volatileMemoryQuotaC7 */
    { (ASN_TAG_CLASS_PRIVATE | (8 << 2)), 1, 0, 0 }, /* nonVolatileMemoryQuotaC8 */
    { (ASN_TAG_CLASS_PRIVATE | (10 << 2)), 6, 0, 0 }, /* ts102226SIMFileAccessToolkitParameter */
    { (ASN_TAG_CLASS_PRIVATE | (11 << 2)), 2, 0, 0 }, /* globalServiceParameters */
    { (ASN_TAG_CLASS_PRIVATE | (15 << 2)), 3, 0, 0 }, /* implicitSelectionParameter */
    { (ASN_TAG_CLASS_PRIVATE | (23 << 2)), 4, 0, 0 }, /* volatileReservedMemory */
    { (ASN_TAG_CLASS_PRIVATE | (24 << 2)), 5, 0, 0 }, /* nonVolatileReservedMemory */
    { (ASN_TAG_CLASS_PRIVATE | (25 << 2)), 8, 0, 0 }, /* contactlessProtocolParameters */
    { (ASN_TAG_CLASS_PRIVATE | (26 << 2)), 9, 0, 0 } /* userInteractionContactlessParameters */
};
asn_SEQUENCE_specifics_t asn_SPC_ApplicationSystemParameters_specs_1 = {
	sizeof(struct ApplicationSystemParameters),
	offsetof(struct ApplicationSystemParameters, _asn_ctx),
	asn_MAP_ApplicationSystemParameters_tag2el_1,
	12,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	12,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ApplicationSystemParameters = {
	"ApplicationSystemParameters",
	"ApplicationSystemParameters",
	&asn_OP_SEQUENCE,
	asn_DEF_ApplicationSystemParameters_tags_1,
	sizeof(asn_DEF_ApplicationSystemParameters_tags_1)
		/sizeof(asn_DEF_ApplicationSystemParameters_tags_1[0]), /* 1 */
	asn_DEF_ApplicationSystemParameters_tags_1,	/* Same as above */
	sizeof(asn_DEF_ApplicationSystemParameters_tags_1)
		/sizeof(asn_DEF_ApplicationSystemParameters_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_ApplicationSystemParameters_1,
	12,	/* Elements count */
	&asn_SPC_ApplicationSystemParameters_specs_1	/* Additional specs */
};

