/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_AuthenticateClientResponseEsipa_H_
#define	_AuthenticateClientResponseEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AuthenticateClientOkDPEsipa.h"
#include "AuthenticateClientOkDSEsipa.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AuthenticateClientResponseEsipa_PR {
	AuthenticateClientResponseEsipa_PR_NOTHING,	/* No components present */
	AuthenticateClientResponseEsipa_PR_authenticateClientOkDPEsipa,
	AuthenticateClientResponseEsipa_PR_authenticateClientOkDSEsipa,
	AuthenticateClientResponseEsipa_PR_authenticateClientErrorEsipa
	/* Extensions may appear below */
	
} AuthenticateClientResponseEsipa_PR;
typedef enum AuthenticateClientResponseEsipa__authenticateClientErrorEsipa {
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_eumCertificateInvalid	= 1,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_eumCertificateExpired	= 2,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_euiccCertificateInvalid	= 3,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_euiccCertificateExpired	= 4,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_euiccSignatureInvalid	= 5,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_matchingIdRefused	= 6,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_eidMismatch	= 7,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_noEligibleProfile	= 8,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_ciPKUnknown	= 9,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_invalidTransactionId	= 10,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_insufficientMemory	= 11,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_pprNotAllowed	= 50,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_eventIdUnknown	= 56,
	AuthenticateClientResponseEsipa__authenticateClientErrorEsipa_undefinedError	= 127
} e_AuthenticateClientResponseEsipa__authenticateClientErrorEsipa;

/* AuthenticateClientResponseEsipa */
typedef struct AuthenticateClientResponseEsipa {
	AuthenticateClientResponseEsipa_PR present;
	union AuthenticateClientResponseEsipa_u {
		AuthenticateClientOkDPEsipa_t	 authenticateClientOkDPEsipa;
		AuthenticateClientOkDSEsipa_t	 authenticateClientOkDSEsipa;
		long	 authenticateClientErrorEsipa;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientResponseEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientResponseEsipa;
extern asn_CHOICE_specifics_t asn_SPC_AuthenticateClientResponseEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientResponseEsipa_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientResponseEsipa_H_ */
#include <asn_internal.h>
