/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_AuthenticateClientOk_H_
#define	_AuthenticateClientOk_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "StoreMetadataRequest.h"
#include "SmdpSigned2.h"
#include <OCTET_STRING.h>
#include "Certificate.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientOk */
typedef struct AuthenticateClientOk {
	TransactionId_t	 transactionId;
	StoreMetadataRequest_t	 profileMetaData;
	SmdpSigned2_t	 smdpSigned2;
	OCTET_STRING_t	 smdpSignature2;
	Certificate_t	 smdpCertificate;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientOk_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOk;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOk_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientOk_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientOk_H_ */
#include <asn_internal.h>
