/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_AuthenticateClientRequestEsipa_H_
#define	_AuthenticateClientRequestEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SGP32-AuthenticateServerResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* AuthenticateClientRequestEsipa */
typedef struct AuthenticateClientRequestEsipa {
	TransactionId_t	 transactionId;
	SGP32_AuthenticateServerResponse_t	 authenticateServerResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AuthenticateClientRequestEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AuthenticateClientRequestEsipa;
extern asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientRequestEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_AuthenticateClientRequestEsipa_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _AuthenticateClientRequestEsipa_H_ */
#include <asn_internal.h>
