/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "AuthenticateClientOkDPEsipa.h"

asn_TYPE_member_t asn_MBR_AuthenticateClientOkDPEsipa_1[] = {
	{ ATF_POINTER, 2, offsetof(struct AuthenticateClientOkDPEsipa, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticateClientOkDPEsipa, profileMetaData),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StoreMetadataRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileMetaData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDPEsipa, smdpSigned2),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDPEsipa, smdpSignature2),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct AuthenticateClientOkDPEsipa, smdpCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpCertificate"
		},
	{ ATF_POINTER, 1, offsetof(struct AuthenticateClientOkDPEsipa, hashCc),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Octet32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashCc"
		},
};
static const ber_tlv_tag_t asn_DEF_AuthenticateClientOkDPEsipa_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_AuthenticateClientOkDPEsipa_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 5, 0, 0 }, /* hashCc */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 2, 0, 1 }, /* smdpSigned2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 }, /* smdpCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 3, 0, 0 }, /* smdpSignature2 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 1, 0, 0 } /* profileMetaData */
};
asn_SEQUENCE_specifics_t asn_SPC_AuthenticateClientOkDPEsipa_specs_1 = {
	sizeof(struct AuthenticateClientOkDPEsipa),
	offsetof(struct AuthenticateClientOkDPEsipa, _asn_ctx),
	asn_MAP_AuthenticateClientOkDPEsipa_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_AuthenticateClientOkDPEsipa = {
	"AuthenticateClientOkDPEsipa",
	"AuthenticateClientOkDPEsipa",
	&asn_OP_SEQUENCE,
	asn_DEF_AuthenticateClientOkDPEsipa_tags_1,
	sizeof(asn_DEF_AuthenticateClientOkDPEsipa_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkDPEsipa_tags_1[0]), /* 1 */
	asn_DEF_AuthenticateClientOkDPEsipa_tags_1,	/* Same as above */
	sizeof(asn_DEF_AuthenticateClientOkDPEsipa_tags_1)
		/sizeof(asn_DEF_AuthenticateClientOkDPEsipa_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_AuthenticateClientOkDPEsipa_1,
	6,	/* Elements count */
	&asn_SPC_AuthenticateClientOkDPEsipa_specs_1	/* Additional specs */
};

