/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_BoundProfilePackage_H_
#define	_BoundProfilePackage_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitialiseSecureChannelRequest.h"
#include "BoundProfilePackage-FirstSequenceOf87.h"
#include "BoundProfilePackage-SequenceOf88.h"
#include "BoundProfilePackage-SequenceOf86.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct BoundProfilePackage_SecondSequenceOf87;

/* BoundProfilePackage */
typedef struct BoundProfilePackage {
	InitialiseSecureChannelRequest_t	 initialiseSecureChannelRequest;
	BoundProfilePackage_FirstSequenceOf87_t	 firstSequenceOf87;
	BoundProfilePackage_SequenceOf88_t	 sequenceOf88;
	struct BoundProfilePackage_SecondSequenceOf87	*secondSequenceOf87	/* OPTIONAL */;
	BoundProfilePackage_SequenceOf86_t	 sequenceOf86;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoundProfilePackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage;
extern asn_SEQUENCE_specifics_t asn_SPC_BoundProfilePackage_specs_1;
extern asn_TYPE_member_t asn_MBR_BoundProfilePackage_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BoundProfilePackage-SecondSequenceOf87.h"

#endif	/* _BoundProfilePackage_H_ */
#include <asn_internal.h>
