/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "BoundProfilePackage-88tlv.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_BoundProfilePackage_88tlv_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage_88tlv = {
	"BoundProfilePackage-88tlv",
	"BoundProfilePackage-88tlv",
	&asn_OP_OCTET_STRING,
	asn_DEF_BoundProfilePackage_88tlv_tags_1,
	sizeof(asn_DEF_BoundProfilePackage_88tlv_tags_1)
		/sizeof(asn_DEF_BoundProfilePackage_88tlv_tags_1[0]) - 1, /* 1 */
	asn_DEF_BoundProfilePackage_88tlv_tags_1,	/* Same as above */
	sizeof(asn_DEF_BoundProfilePackage_88tlv_tags_1)
		/sizeof(asn_DEF_BoundProfilePackage_88tlv_tags_1[0]), /* 2 */
	{ 0, 0, OCTET_STRING_constraint },
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};

