/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_BoundProfilePackage_SequenceOf86_H_
#define	_BoundProfilePackage_SequenceOf86_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BoundProfilePackage-86tlv.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* BoundProfilePackage-SequenceOf86 */
typedef struct BoundProfilePackage_SequenceOf86 {
	A_SEQUENCE_OF(BoundProfilePackage_86tlv_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BoundProfilePackage_SequenceOf86_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BoundProfilePackage_SequenceOf86;
extern asn_SET_OF_specifics_t asn_SPC_BoundProfilePackage_SequenceOf86_specs_1;
extern asn_TYPE_member_t asn_MBR_BoundProfilePackage_SequenceOf86_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _BoundProfilePackage_SequenceOf86_H_ */
#include <asn_internal.h>
