/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "CancelSessionResponse.h"

asn_TYPE_member_t asn_MBR_CancelSessionResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CancelSessionResponse, choice.cancelSessionResponseOk),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionResponseOk,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseOk"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CancelSessionResponse, choice.cancelSessionResponseError),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseError"
		},
};
static const ber_tlv_tag_t asn_DEF_CancelSessionResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (65 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CancelSessionResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cancelSessionResponseOk */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cancelSessionResponseError */
};
asn_CHOICE_specifics_t asn_SPC_CancelSessionResponse_specs_1 = {
	sizeof(struct CancelSessionResponse),
	offsetof(struct CancelSessionResponse, _asn_ctx),
	offsetof(struct CancelSessionResponse, present),
	sizeof(((struct CancelSessionResponse *)0)->present),
	asn_MAP_CancelSessionResponse_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_CancelSessionResponse = {
	"CancelSessionResponse",
	"CancelSessionResponse",
	&asn_OP_CHOICE,
	asn_DEF_CancelSessionResponse_tags_1,
	sizeof(asn_DEF_CancelSessionResponse_tags_1)
		/sizeof(asn_DEF_CancelSessionResponse_tags_1[0]), /* 1 */
	asn_DEF_CancelSessionResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_CancelSessionResponse_tags_1)
		/sizeof(asn_DEF_CancelSessionResponse_tags_1[0]), /* 1 */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_CancelSessionResponse_1,
	2,	/* Elements count */
	&asn_SPC_CancelSessionResponse_specs_1	/* Additional specs */
};

