/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "CompactEuiccSigned1.h"

asn_TYPE_member_t asn_MBR_CompactEuiccSigned1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CompactEuiccSigned1, extCardResource),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"extCardResource"
		},
	{ ATF_POINTER, 1, offsetof(struct CompactEuiccSigned1, ctxParams1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CtxParams1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ctxParams1"
		},
};
static const ber_tlv_tag_t asn_DEF_CompactEuiccSigned1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CompactEuiccSigned1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* ctxParams1 */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 0, 0, 0 } /* extCardResource */
};
asn_SEQUENCE_specifics_t asn_SPC_CompactEuiccSigned1_specs_1 = {
	sizeof(struct CompactEuiccSigned1),
	offsetof(struct CompactEuiccSigned1, _asn_ctx),
	asn_MAP_CompactEuiccSigned1_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CompactEuiccSigned1 = {
	"CompactEuiccSigned1",
	"CompactEuiccSigned1",
	&asn_OP_SEQUENCE,
	asn_DEF_CompactEuiccSigned1_tags_1,
	sizeof(asn_DEF_CompactEuiccSigned1_tags_1)
		/sizeof(asn_DEF_CompactEuiccSigned1_tags_1[0]), /* 1 */
	asn_DEF_CompactEuiccSigned1_tags_1,	/* Same as above */
	sizeof(asn_DEF_CompactEuiccSigned1_tags_1)
		/sizeof(asn_DEF_CompactEuiccSigned1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CompactEuiccSigned1_1,
	2,	/* Elements count */
	&asn_SPC_CompactEuiccSigned1_specs_1	/* Additional specs */
};

