/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_CompactEuiccCancelSessionSigned_H_
#define	_CompactEuiccCancelSessionSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CancelSessionReason.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CompactEuiccCancelSessionSigned */
typedef struct CompactEuiccCancelSessionSigned {
	CancelSessionReason_t	*reason	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CompactEuiccCancelSessionSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompactEuiccCancelSessionSigned;
extern asn_SEQUENCE_specifics_t asn_SPC_CompactEuiccCancelSessionSigned_specs_1;
extern asn_TYPE_member_t asn_MBR_CompactEuiccCancelSessionSigned_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _CompactEuiccCancelSessionSigned_H_ */
#include <asn_internal.h>
