/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_CompactProfileInstallationResult_H_
#define	_CompactProfileInstallationResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CompactProfileInstallationResultData.h"
#include "EuiccSignPIR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* CompactProfileInstallationResult */
typedef struct CompactProfileInstallationResult {
	CompactProfileInstallationResultData_t	 compactProfileInstallationResultData;
	EuiccSignPIR_t	 euiccSignPIR;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CompactProfileInstallationResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CompactProfileInstallationResult;
extern asn_SEQUENCE_specifics_t asn_SPC_CompactProfileInstallationResult_specs_1;
extern asn_TYPE_member_t asn_MBR_CompactProfileInstallationResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CompactProfileInstallationResult_H_ */
#include <asn_internal.h>
