/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "CompactEuiccSigned2.h"

asn_TYPE_member_t asn_MBR_CompactEuiccSigned2_1[] = {
	{ ATF_POINTER, 2, offsetof(struct CompactEuiccSigned2, euiccOtpk),
		(ASN_TAG_CLASS_APPLICATION | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccOtpk"
		},
	{ ATF_POINTER, 1, offsetof(struct CompactEuiccSigned2, hashCc),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Octet32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashCc"
		},
};
static const ber_tlv_tag_t asn_DEF_CompactEuiccSigned2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CompactEuiccSigned2_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* hashCc */
    { (ASN_TAG_CLASS_APPLICATION | (73 << 2)), 0, 0, 0 } /* euiccOtpk */
};
asn_SEQUENCE_specifics_t asn_SPC_CompactEuiccSigned2_specs_1 = {
	sizeof(struct CompactEuiccSigned2),
	offsetof(struct CompactEuiccSigned2, _asn_ctx),
	asn_MAP_CompactEuiccSigned2_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CompactEuiccSigned2 = {
	"CompactEuiccSigned2",
	"CompactEuiccSigned2",
	&asn_OP_SEQUENCE,
	asn_DEF_CompactEuiccSigned2_tags_1,
	sizeof(asn_DEF_CompactEuiccSigned2_tags_1)
		/sizeof(asn_DEF_CompactEuiccSigned2_tags_1[0]), /* 1 */
	asn_DEF_CompactEuiccSigned2_tags_1,	/* Same as above */
	sizeof(asn_DEF_CompactEuiccSigned2_tags_1)
		/sizeof(asn_DEF_CompactEuiccSigned2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CompactEuiccSigned2_1,
	2,	/* Elements count */
	&asn_SPC_CompactEuiccSigned2_specs_1	/* Additional specs */
};

