/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "CompactAuthenticateResponseOk.h"

static asn_TYPE_member_t asn_MBR_signedData_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CompactAuthenticateResponseOk__signedData, choice.euiccSigned1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EuiccSigned1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccSigned1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CompactAuthenticateResponseOk__signedData, choice.compactEuiccSigned1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompactEuiccSigned1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compactEuiccSigned1"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_signedData_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* euiccSigned1 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 } /* compactEuiccSigned1 */
};
static asn_CHOICE_specifics_t asn_SPC_signedData_specs_2 = {
	sizeof(struct CompactAuthenticateResponseOk__signedData),
	offsetof(struct CompactAuthenticateResponseOk__signedData, _asn_ctx),
	offsetof(struct CompactAuthenticateResponseOk__signedData, present),
	sizeof(((struct CompactAuthenticateResponseOk__signedData *)0)->present),
	asn_MAP_signedData_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_signedData_2 = {
	"signedData",
	"signedData",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_signedData_2,
	2,	/* Elements count */
	&asn_SPC_signedData_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CompactAuthenticateResponseOk_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CompactAuthenticateResponseOk, signedData),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_signedData_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"signedData"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CompactAuthenticateResponseOk, euiccSignature1),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccSignature1"
		},
	{ ATF_POINTER, 2, offsetof(struct CompactAuthenticateResponseOk, euiccCertificate),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCertificate"
		},
	{ ATF_POINTER, 1, offsetof(struct CompactAuthenticateResponseOk, eumCertificate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eumCertificate"
		},
};
static const ber_tlv_tag_t asn_DEF_CompactAuthenticateResponseOk_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CompactAuthenticateResponseOk_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 }, /* euiccSigned1 */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 }, /* euiccSignature1 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* compactEuiccSigned1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 }, /* euiccCertificate */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 } /* eumCertificate */
};
asn_SEQUENCE_specifics_t asn_SPC_CompactAuthenticateResponseOk_specs_1 = {
	sizeof(struct CompactAuthenticateResponseOk),
	offsetof(struct CompactAuthenticateResponseOk, _asn_ctx),
	asn_MAP_CompactAuthenticateResponseOk_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CompactAuthenticateResponseOk = {
	"CompactAuthenticateResponseOk",
	"CompactAuthenticateResponseOk",
	&asn_OP_SEQUENCE,
	asn_DEF_CompactAuthenticateResponseOk_tags_1,
	sizeof(asn_DEF_CompactAuthenticateResponseOk_tags_1)
		/sizeof(asn_DEF_CompactAuthenticateResponseOk_tags_1[0]), /* 1 */
	asn_DEF_CompactAuthenticateResponseOk_tags_1,	/* Same as above */
	sizeof(asn_DEF_CompactAuthenticateResponseOk_tags_1)
		/sizeof(asn_DEF_CompactAuthenticateResponseOk_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_CompactAuthenticateResponseOk_1,
	4,	/* Elements count */
	&asn_SPC_CompactAuthenticateResponseOk_specs_1	/* Additional specs */
};

