/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "ConfigureAutoProfileEnablingRequest.h"

static asn_TYPE_member_t asn_MBR_ConfigureAutoProfileEnablingRequest_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ConfigureAutoProfileEnablingRequest, autoEnableFlag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"autoEnableFlag"
		},
	{ ATF_POINTER, 2, offsetof(struct ConfigureAutoProfileEnablingRequest, smdpOid),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpOid"
		},
	{ ATF_POINTER, 1, offsetof(struct ConfigureAutoProfileEnablingRequest, smdpAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpAddress"
		},
};
static const ber_tlv_tag_t asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (89 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfigureAutoProfileEnablingRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* autoEnableFlag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* smdpOid */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* smdpAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConfigureAutoProfileEnablingRequest_specs_1 = {
	sizeof(struct ConfigureAutoProfileEnablingRequest),
	offsetof(struct ConfigureAutoProfileEnablingRequest, _asn_ctx),
	asn_MAP_ConfigureAutoProfileEnablingRequest_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfigureAutoProfileEnablingRequest = {
	"ConfigureAutoProfileEnablingRequest",
	"ConfigureAutoProfileEnablingRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1,
	sizeof(asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1)
		/sizeof(asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1)
		/sizeof(asn_DEF_ConfigureAutoProfileEnablingRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConfigureAutoProfileEnablingRequest_1,
	3,	/* Elements count */
	&asn_SPC_ConfigureAutoProfileEnablingRequest_specs_1	/* Additional specs */
};

