/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "ConfigureImmediateProfileEnablingRequest.h"

static asn_TYPE_member_t asn_MBR_ConfigureImmediateProfileEnablingRequest_1[] = {
	{ ATF_POINTER, 3, offsetof(struct ConfigureImmediateProfileEnablingRequest, immediateEnableFlag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"immediateEnableFlag"
		},
	{ ATF_POINTER, 2, offsetof(struct ConfigureImmediateProfileEnablingRequest, defaultSmdpOid),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultSmdpOid"
		},
	{ ATF_POINTER, 1, offsetof(struct ConfigureImmediateProfileEnablingRequest, defaultSmdpAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultSmdpAddress"
		},
};
static const int asn_MAP_ConfigureImmediateProfileEnablingRequest_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (89 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConfigureImmediateProfileEnablingRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* immediateEnableFlag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* defaultSmdpOid */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* defaultSmdpAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConfigureImmediateProfileEnablingRequest_specs_1 = {
	sizeof(struct ConfigureImmediateProfileEnablingRequest),
	offsetof(struct ConfigureImmediateProfileEnablingRequest, _asn_ctx),
	asn_MAP_ConfigureImmediateProfileEnablingRequest_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ConfigureImmediateProfileEnablingRequest_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConfigureImmediateProfileEnablingRequest = {
	"ConfigureImmediateProfileEnablingRequest",
	"ConfigureImmediateProfileEnablingRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1,
	sizeof(asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1)
		/sizeof(asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1)
		/sizeof(asn_DEF_ConfigureImmediateProfileEnablingRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConfigureImmediateProfileEnablingRequest_1,
	3,	/* Elements count */
	&asn_SPC_ConfigureImmediateProfileEnablingRequest_specs_1	/* Additional specs */
};

