/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_DeleteProfileResponse_H_
#define	_DeleteProfileResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DeleteProfileResponse__deleteResult {
	DeleteProfileResponse__deleteResult_ok	= 0,
	DeleteProfileResponse__deleteResult_iccidOrAidNotFound	= 1,
	DeleteProfileResponse__deleteResult_profileNotInDisabledState	= 2,
	DeleteProfileResponse__deleteResult_disallowedByPolicy	= 3,
	DeleteProfileResponse__deleteResult_undefinedError	= 127
} e_DeleteProfileResponse__deleteResult;

/* DeleteProfileResponse */
typedef struct DeleteProfileResponse {
	long	 deleteResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DeleteProfileResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DeleteProfileResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _DeleteProfileResponse_H_ */
#include <asn_internal.h>
