/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_EimPackageResultResponseError_H_
#define	_EimPackageResultResponseError_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "EimPackageResultErrorCode.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EimPackageResultResponseError */
typedef struct EimPackageResultResponseError {
	TransactionId_t	*eimTransactionId	/* OPTIONAL */;
	EimPackageResultErrorCode_t	 eimPackageResultErrorCode;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EimPackageResultResponseError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EimPackageResultResponseError;
extern asn_SEQUENCE_specifics_t asn_SPC_EimPackageResultResponseError_specs_1;
extern asn_TYPE_member_t asn_MBR_EimPackageResultResponseError_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EimPackageResultResponseError_H_ */
#include <asn_internal.h>
