/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "EnableUsingDDRequest.h"

static const ber_tlv_tag_t asn_DEF_EnableUsingDDRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (90 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_EnableUsingDDRequest_specs_1 = {
	sizeof(struct EnableUsingDDRequest),
	offsetof(struct EnableUsingDDRequest, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EnableUsingDDRequest = {
	"EnableUsingDDRequest",
	"EnableUsingDDRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_EnableUsingDDRequest_tags_1,
	sizeof(asn_DEF_EnableUsingDDRequest_tags_1)
		/sizeof(asn_DEF_EnableUsingDDRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_EnableUsingDDRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnableUsingDDRequest_tags_1)
		/sizeof(asn_DEF_EnableUsingDDRequest_tags_1[0]), /* 2 */
	{ 0, 0, 0 },
	0, 0,	/* No members */
	&asn_SPC_EnableUsingDDRequest_specs_1	/* Additional specs */
};

