/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_EnableProfileResponse_H_
#define	_EnableProfileResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnableProfileResponse__enableResult {
	EnableProfileResponse__enableResult_ok	= 0,
	EnableProfileResponse__enableResult_iccidOrAidNotFound	= 1,
	EnableProfileResponse__enableResult_profileNotInDisabledState	= 2,
	EnableProfileResponse__enableResult_disallowedByPolicy	= 3,
	EnableProfileResponse__enableResult_wrongProfileReenabling	= 4,
	EnableProfileResponse__enableResult_catBusy	= 5,
	EnableProfileResponse__enableResult_undefinedError	= 127
} e_EnableProfileResponse__enableResult;

/* EnableProfileResponse */
typedef struct EnableProfileResponse {
	long	 enableResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnableProfileResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnableProfileResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _EnableProfileResponse_H_ */
#include <asn_internal.h>
