/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "EnableUsingDDResponse.h"

static asn_TYPE_member_t asn_MBR_EnableUsingDDResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EnableUsingDDResponse, enableUsingDDResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enableUsingDDResult"
		},
};
static const ber_tlv_tag_t asn_DEF_EnableUsingDDResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (90 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EnableUsingDDResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* enableUsingDDResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_EnableUsingDDResponse_specs_1 = {
	sizeof(struct EnableUsingDDResponse),
	offsetof(struct EnableUsingDDResponse, _asn_ctx),
	asn_MAP_EnableUsingDDResponse_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EnableUsingDDResponse = {
	"EnableUsingDDResponse",
	"EnableUsingDDResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_EnableUsingDDResponse_tags_1,
	sizeof(asn_DEF_EnableUsingDDResponse_tags_1)
		/sizeof(asn_DEF_EnableUsingDDResponse_tags_1[0]) - 1, /* 1 */
	asn_DEF_EnableUsingDDResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_EnableUsingDDResponse_tags_1)
		/sizeof(asn_DEF_EnableUsingDDResponse_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_EnableUsingDDResponse_1,
	1,	/* Elements count */
	&asn_SPC_EnableUsingDDResponse_specs_1	/* Additional specs */
};

