/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_EnableUsingDDResponse_H_
#define	_EnableUsingDDResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnableUsingDDResponse__enableUsingDDResult {
	EnableUsingDDResponse__enableUsingDDResult_ok	= 0,
	EnableUsingDDResponse__enableUsingDDResult_autoEnableNotAvailable	= 1,
	EnableUsingDDResponse__enableUsingDDResult_noSessionContext	= 4,
	EnableUsingDDResponse__enableUsingDDResult_undefinedError	= 127
} e_EnableUsingDDResponse__enableUsingDDResult;

/* EnableUsingDDResponse */
typedef struct EnableUsingDDResponse {
	long	 enableUsingDDResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EnableUsingDDResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EnableUsingDDResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _EnableUsingDDResponse_H_ */
#include <asn_internal.h>
