/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_EsipaMessageFromEimToIpa_H_
#define	_EsipaMessageFromEimToIpa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitiateAuthenticationResponseEsipa.h"
#include "AuthenticateClientResponseEsipa.h"
#include "GetBoundProfilePackageResponseEsipa.h"
#include "CancelSessionResponseEsipa.h"
#include "TransferEimPackageRequest.h"
#include "GetEimPackageResponse.h"
#include "ProvideEimPackageResultResponse.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EsipaMessageFromEimToIpa_PR {
	EsipaMessageFromEimToIpa_PR_NOTHING,	/* No components present */
	EsipaMessageFromEimToIpa_PR_initiateAuthenticationResponseEsipa,
	EsipaMessageFromEimToIpa_PR_authenticateClientResponseEsipa,
	EsipaMessageFromEimToIpa_PR_getBoundProfilePackageResponseEsipa,
	EsipaMessageFromEimToIpa_PR_cancelSessionResponseEsipa,
	EsipaMessageFromEimToIpa_PR_transferEimPackageRequest,
	EsipaMessageFromEimToIpa_PR_getEimPackageResponse,
	EsipaMessageFromEimToIpa_PR_provideEimPackageResultResponse
	/* Extensions may appear below */
	
} EsipaMessageFromEimToIpa_PR;

/* EsipaMessageFromEimToIpa */
typedef struct EsipaMessageFromEimToIpa {
	EsipaMessageFromEimToIpa_PR present;
	union EsipaMessageFromEimToIpa_u {
		InitiateAuthenticationResponseEsipa_t	 initiateAuthenticationResponseEsipa;
		AuthenticateClientResponseEsipa_t	 authenticateClientResponseEsipa;
		GetBoundProfilePackageResponseEsipa_t	 getBoundProfilePackageResponseEsipa;
		CancelSessionResponseEsipa_t	 cancelSessionResponseEsipa;
		TransferEimPackageRequest_t	 transferEimPackageRequest;
		GetEimPackageResponse_t	 getEimPackageResponse;
		ProvideEimPackageResultResponse_t	 provideEimPackageResultResponse;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EsipaMessageFromEimToIpa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EsipaMessageFromEimToIpa;

#ifdef __cplusplus
}
#endif

#endif	/* _EsipaMessageFromEimToIpa_H_ */
#include <asn_internal.h>
