/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "EsipaMessageFromEimToIpa.h"

static asn_TYPE_member_t asn_MBR_EsipaMessageFromEimToIpa_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.initiateAuthenticationResponseEsipa),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateAuthenticationResponseEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateAuthenticationResponseEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.authenticateClientResponseEsipa),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthenticateClientResponseEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authenticateClientResponseEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.getBoundProfilePackageResponseEsipa),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetBoundProfilePackageResponseEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getBoundProfilePackageResponseEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.cancelSessionResponseEsipa),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionResponseEsipa,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseEsipa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.transferEimPackageRequest),
		(ASN_TAG_CLASS_CONTEXT | (78 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransferEimPackageRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transferEimPackageRequest"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.getEimPackageResponse),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetEimPackageResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getEimPackageResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EsipaMessageFromEimToIpa, choice.provideEimPackageResultResponse),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProvideEimPackageResultResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"provideEimPackageResultResponse"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_EsipaMessageFromEimToIpa_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 0, 0, 0 }, /* initiateAuthenticationResponseEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 2, 0, 0 }, /* getBoundProfilePackageResponseEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 1, 0, 0 }, /* authenticateClientResponseEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 3, 0, 0 }, /* cancelSessionResponseEsipa */
    { (ASN_TAG_CLASS_CONTEXT | (78 << 2)), 4, 0, 0 }, /* transferEimPackageRequest */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 5, 0, 0 }, /* getEimPackageResponse */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 6, 0, 0 } /* provideEimPackageResultResponse */
};
static asn_CHOICE_specifics_t asn_SPC_EsipaMessageFromEimToIpa_specs_1 = {
	sizeof(struct EsipaMessageFromEimToIpa),
	offsetof(struct EsipaMessageFromEimToIpa, _asn_ctx),
	offsetof(struct EsipaMessageFromEimToIpa, present),
	sizeof(((struct EsipaMessageFromEimToIpa *)0)->present),
	asn_MAP_EsipaMessageFromEimToIpa_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0,
	7	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EsipaMessageFromEimToIpa = {
	"EsipaMessageFromEimToIpa",
	"EsipaMessageFromEimToIpa",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_EsipaMessageFromEimToIpa_1,
	7,	/* Elements count */
	&asn_SPC_EsipaMessageFromEimToIpa_specs_1	/* Additional specs */
};

