/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_EuiccPackageResult_H_
#define	_EuiccPackageResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EuiccPackageResultSigned.h"
#include "EuiccPackageErrorSigned.h"
#include "EuiccPackageErrorUnsigned.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuiccPackageResult_PR {
	EuiccPackageResult_PR_NOTHING,	/* No components present */
	EuiccPackageResult_PR_euiccPackageResultSigned,
	EuiccPackageResult_PR_euiccPackageErrorSigned,
	EuiccPackageResult_PR_euiccPackageErrorUnsigned
	/* Extensions may appear below */
	
} EuiccPackageResult_PR;

/* EuiccPackageResult */
typedef struct EuiccPackageResult {
	EuiccPackageResult_PR present;
	union EuiccPackageResult_u {
		EuiccPackageResultSigned_t	 euiccPackageResultSigned;
		EuiccPackageErrorSigned_t	 euiccPackageErrorSigned;
		EuiccPackageErrorUnsigned_t	 euiccPackageErrorUnsigned;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccPackageResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccPackageResult;
extern asn_CHOICE_specifics_t asn_SPC_EuiccPackageResult_specs_1;
extern asn_TYPE_member_t asn_MBR_EuiccPackageResult_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccPackageResult_H_ */
#include <asn_internal.h>
