/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_EuiccPackageErrorUnsigned_H_
#define	_EuiccPackageErrorUnsigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccPackageErrorUnsigned */
typedef struct EuiccPackageErrorUnsigned {
	UTF8String_t	 eimId;
	long	*associationToken	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccPackageErrorUnsigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccPackageErrorUnsigned;
extern asn_SEQUENCE_specifics_t asn_SPC_EuiccPackageErrorUnsigned_specs_1;
extern asn_TYPE_member_t asn_MBR_EuiccPackageErrorUnsigned_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccPackageErrorUnsigned_H_ */
#include <asn_internal.h>
