/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "EUICCResponse.h"

static asn_TYPE_member_t asn_MBR_peStatus_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PEStatus,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_peStatus_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_peStatus_specs_2 = {
	sizeof(struct EUICCResponse__peStatus),
	offsetof(struct EUICCResponse__peStatus, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_peStatus_2 = {
	"peStatus",
	"peStatus",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_peStatus_tags_2,
	sizeof(asn_DEF_peStatus_tags_2)
		/sizeof(asn_DEF_peStatus_tags_2[0]) - 1, /* 1 */
	asn_DEF_peStatus_tags_2,	/* Same as above */
	sizeof(asn_DEF_peStatus_tags_2)
		/sizeof(asn_DEF_peStatus_tags_2[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_peStatus_2,
	1,	/* Single element */
	&asn_SPC_peStatus_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_EUICCResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EUICCResponse, peStatus),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_peStatus_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"peStatus"
		},
	{ ATF_POINTER, 2, offsetof(struct EUICCResponse, profileInstallationAborted),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileInstallationAborted"
		},
	{ ATF_POINTER, 1, offsetof(struct EUICCResponse, statusMessage),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statusMessage"
		},
};
static const ber_tlv_tag_t asn_DEF_EUICCResponse_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EUICCResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* peStatus */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* profileInstallationAborted */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* statusMessage */
};
static asn_SEQUENCE_specifics_t asn_SPC_EUICCResponse_specs_1 = {
	sizeof(struct EUICCResponse),
	offsetof(struct EUICCResponse, _asn_ctx),
	asn_MAP_EUICCResponse_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EUICCResponse = {
	"EUICCResponse",
	"EUICCResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_EUICCResponse_tags_1,
	sizeof(asn_DEF_EUICCResponse_tags_1)
		/sizeof(asn_DEF_EUICCResponse_tags_1[0]), /* 1 */
	asn_DEF_EUICCResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_EUICCResponse_tags_1)
		/sizeof(asn_DEF_EUICCResponse_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_EUICCResponse_1,
	3,	/* Elements count */
	&asn_SPC_EUICCResponse_specs_1	/* Additional specs */
};

