/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_EuiccPackageSigned_H_
#define	_EuiccPackageSigned_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include "Octet16.h"
#include <NativeInteger.h>
#include "TransactionId.h"
#include "EuiccPackage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccPackageSigned */
typedef struct EuiccPackageSigned {
	UTF8String_t	 eimId;
	Octet16_t	 eidValue;
	long	 counterValue;
	TransactionId_t	*eimTransactionId	/* OPTIONAL */;
	EuiccPackage_t	 euiccPackage;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EuiccPackageSigned_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccPackageSigned;
extern asn_SEQUENCE_specifics_t asn_SPC_EuiccPackageSigned_specs_1;
extern asn_TYPE_member_t asn_MBR_EuiccPackageSigned_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccPackageSigned_H_ */
#include <asn_internal.h>
