/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_EUICCResponse_H_
#define	_EUICCResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <UTF8String.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PEStatus;

/* EUICCResponse */
typedef struct EUICCResponse {
	struct EUICCResponse__peStatus {
		A_SEQUENCE_OF(struct PEStatus) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} peStatus;
	NULL_t	*profileInstallationAborted	/* OPTIONAL */;
	UTF8String_t	*statusMessage	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUICCResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUICCResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PEStatus.h"

#endif	/* _EUICCResponse_H_ */
#include <asn_internal.h>
