/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_EuiccFormFactorType_H_
#define	_EuiccFormFactorType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EuiccFormFactorType */
typedef long	 EuiccFormFactorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccFormFactorType;
asn_struct_free_f EuiccFormFactorType_free;
asn_struct_print_f EuiccFormFactorType_print;
asn_constr_check_f EuiccFormFactorType_constraint;
ber_type_decoder_f EuiccFormFactorType_decode_ber;
der_type_encoder_f EuiccFormFactorType_encode_der;
xer_type_decoder_f EuiccFormFactorType_decode_xer;
xer_type_encoder_f EuiccFormFactorType_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccFormFactorType_H_ */
#include <asn_internal.h>
