/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "EuiccPackageResult.h"

asn_TYPE_member_t asn_MBR_EuiccPackageResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageResult, choice.euiccPackageResultSigned),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageResultSigned,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResultSigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageResult, choice.euiccPackageErrorSigned),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageErrorSigned,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageErrorSigned"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageResult, choice.euiccPackageErrorUnsigned),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageErrorUnsigned,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageErrorUnsigned"
		},
};
static const ber_tlv_tag_t asn_DEF_EuiccPackageResult_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (81 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EuiccPackageResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* euiccPackageResultSigned */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* euiccPackageErrorSigned */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* euiccPackageErrorUnsigned */
};
asn_CHOICE_specifics_t asn_SPC_EuiccPackageResult_specs_1 = {
	sizeof(struct EuiccPackageResult),
	offsetof(struct EuiccPackageResult, _asn_ctx),
	offsetof(struct EuiccPackageResult, present),
	sizeof(((struct EuiccPackageResult *)0)->present),
	asn_MAP_EuiccPackageResult_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EuiccPackageResult = {
	"EuiccPackageResult",
	"EuiccPackageResult",
	&asn_OP_CHOICE,
	asn_DEF_EuiccPackageResult_tags_1,
	sizeof(asn_DEF_EuiccPackageResult_tags_1)
		/sizeof(asn_DEF_EuiccPackageResult_tags_1[0]), /* 1 */
	asn_DEF_EuiccPackageResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_EuiccPackageResult_tags_1)
		/sizeof(asn_DEF_EuiccPackageResult_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_EuiccPackageResult_1,
	3,	/* Elements count */
	&asn_SPC_EuiccPackageResult_specs_1	/* Additional specs */
};

