/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_EuiccPackageErrorCode_H_
#define	_EuiccPackageErrorCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EuiccPackageErrorCode {
	EuiccPackageErrorCode_invalidEid	= 3,
	EuiccPackageErrorCode_replayError	= 4,
	EuiccPackageErrorCode_counterValueOutOfRange	= 6,
	EuiccPackageErrorCode_sizeOverflow	= 15,
	EuiccPackageErrorCode_ecallActive	= 104,
	EuiccPackageErrorCode_undefinedError	= 127
} e_EuiccPackageErrorCode;

/* EuiccPackageErrorCode */
typedef long	 EuiccPackageErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EuiccPackageErrorCode;
asn_struct_free_f EuiccPackageErrorCode_free;
asn_struct_print_f EuiccPackageErrorCode_print;
asn_constr_check_f EuiccPackageErrorCode_constraint;
ber_type_decoder_f EuiccPackageErrorCode_decode_ber;
der_type_encoder_f EuiccPackageErrorCode_encode_der;
xer_type_decoder_f EuiccPackageErrorCode_decode_xer;
xer_type_encoder_f EuiccPackageErrorCode_encode_xer;
oer_type_decoder_f EuiccPackageErrorCode_decode_oer;
oer_type_encoder_f EuiccPackageErrorCode_encode_oer;
per_type_decoder_f EuiccPackageErrorCode_decode_uper;
per_type_encoder_f EuiccPackageErrorCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EuiccPackageErrorCode_H_ */
#include <asn_internal.h>
