/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "EuiccPackageSigned.h"

asn_TYPE_member_t asn_MBR_EuiccPackageSigned_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageSigned, eimId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageSigned, eidValue),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eidValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageSigned, counterValue),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"counterValue"
		},
	{ ATF_POINTER, 1, offsetof(struct EuiccPackageSigned, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EuiccPackageSigned, euiccPackage),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_EuiccPackage,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackage"
		},
};
static const ber_tlv_tag_t asn_DEF_EuiccPackageSigned_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EuiccPackageSigned_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 1, 0, 0 }, /* eidValue */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 1 }, /* eimId */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 4, -1, 0 }, /* psmoList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 1 }, /* counterValue */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 4, -1, 0 }, /* ecoList */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 } /* transactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_EuiccPackageSigned_specs_1 = {
	sizeof(struct EuiccPackageSigned),
	offsetof(struct EuiccPackageSigned, _asn_ctx),
	asn_MAP_EuiccPackageSigned_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EuiccPackageSigned = {
	"EuiccPackageSigned",
	"EuiccPackageSigned",
	&asn_OP_SEQUENCE,
	asn_DEF_EuiccPackageSigned_tags_1,
	sizeof(asn_DEF_EuiccPackageSigned_tags_1)
		/sizeof(asn_DEF_EuiccPackageSigned_tags_1[0]), /* 1 */
	asn_DEF_EuiccPackageSigned_tags_1,	/* Same as above */
	sizeof(asn_DEF_EuiccPackageSigned_tags_1)
		/sizeof(asn_DEF_EuiccPackageSigned_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_EuiccPackageSigned_1,
	5,	/* Elements count */
	&asn_SPC_EuiccPackageSigned_specs_1	/* Additional specs */
};

