/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ExpirationDate.h"

/*
 * This type is implemented using Time,
 * so here we adjust the DEF accordingly.
 */
asn_TYPE_descriptor_t asn_DEF_ExpirationDate = {
	"ExpirationDate",
	"ExpirationDate",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_Time_1,
	2,	/* Elements count */
	&asn_SPC_Time_specs_1	/* Additional specs */
};

