/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_Fcp_H_
#define	_Fcp_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include "ApplicationIdentifier.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProprietaryInfo;

/* Fcp */
typedef struct Fcp {
	OCTET_STRING_t	*fileDescriptor	/* OPTIONAL */;
	OCTET_STRING_t	*fileID	/* OPTIONAL */;
	ApplicationIdentifier_t	*dfName	/* OPTIONAL */;
	OCTET_STRING_t	*lcsi	/* DEFAULT '05'HH */;
	OCTET_STRING_t	*securityAttributesReferenced	/* OPTIONAL */;
	OCTET_STRING_t	*efFileSize	/* OPTIONAL */;
	OCTET_STRING_t	*pinStatusTemplateDO	/* OPTIONAL */;
	OCTET_STRING_t	*shortEFID	/* OPTIONAL */;
	struct ProprietaryInfo	*proprietaryEFInfo	/* OPTIONAL */;
	OCTET_STRING_t	*linkPath	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Fcp_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Fcp;
extern asn_SEQUENCE_specifics_t asn_SPC_Fcp_specs_1;
extern asn_TYPE_member_t asn_MBR_Fcp_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ProprietaryInfo.h"

#endif	/* _Fcp_H_ */
#include <asn_internal.h>
