/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "Fcp.h"

asn_TYPE_member_t asn_MBR_Fcp_1[] = {
	{ ATF_POINTER, 10, offsetof(struct Fcp, fileDescriptor),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fileDescriptor"
		},
	{ ATF_POINTER, 9, offsetof(struct Fcp, fileID),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"fileID"
		},
	{ ATF_POINTER, 8, offsetof(struct Fcp, dfName),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ApplicationIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dfName"
		},
	{ ATF_POINTER, 7, offsetof(struct Fcp, lcsi),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lcsi"
		},
	{ ATF_POINTER, 6, offsetof(struct Fcp, securityAttributesReferenced),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityAttributesReferenced"
		},
	{ ATF_POINTER, 5, offsetof(struct Fcp, efFileSize),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"efFileSize"
		},
	{ ATF_POINTER, 4, offsetof(struct Fcp, pinStatusTemplateDO),
		(ASN_TAG_CLASS_PRIVATE | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pinStatusTemplateDO"
		},
	{ ATF_POINTER, 3, offsetof(struct Fcp, shortEFID),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"shortEFID"
		},
	{ ATF_POINTER, 2, offsetof(struct Fcp, proprietaryEFInfo),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProprietaryInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"proprietaryEFInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct Fcp, linkPath),
		(ASN_TAG_CLASS_PRIVATE | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"linkPath"
		},
};
static const ber_tlv_tag_t asn_DEF_Fcp_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Fcp_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 5, 0, 0 }, /* efFileSize */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 }, /* fileDescriptor */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* fileID */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 2, 0, 0 }, /* dfName */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 8, 0, 0 }, /* proprietaryEFInfo */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 7, 0, 0 }, /* shortEFID */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 3, 0, 0 }, /* lcsi */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 4, 0, 0 }, /* securityAttributesReferenced */
    { (ASN_TAG_CLASS_PRIVATE | (6 << 2)), 6, 0, 0 }, /* pinStatusTemplateDO */
    { (ASN_TAG_CLASS_PRIVATE | (7 << 2)), 9, 0, 0 } /* linkPath */
};
asn_SEQUENCE_specifics_t asn_SPC_Fcp_specs_1 = {
	sizeof(struct Fcp),
	offsetof(struct Fcp, _asn_ctx),
	asn_MAP_Fcp_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Fcp = {
	"Fcp",
	"Fcp",
	&asn_OP_SEQUENCE,
	asn_DEF_Fcp_tags_1,
	sizeof(asn_DEF_Fcp_tags_1)
		/sizeof(asn_DEF_Fcp_tags_1[0]), /* 1 */
	asn_DEF_Fcp_tags_1,	/* Same as above */
	sizeof(asn_DEF_Fcp_tags_1)
		/sizeof(asn_DEF_Fcp_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_Fcp_1,
	10,	/* Elements count */
	&asn_SPC_Fcp_specs_1	/* Additional specs */
};

