/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_GetBoundProfilePackageRequestEsipa_H_
#define	_GetBoundProfilePackageRequestEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SGP32-PrepareDownloadResponse.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetBoundProfilePackageRequestEsipa */
typedef struct GetBoundProfilePackageRequestEsipa {
	TransactionId_t	 transactionId;
	SGP32_PrepareDownloadResponse_t	 prepareDownloadResponse;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetBoundProfilePackageRequestEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetBoundProfilePackageRequestEsipa;
extern asn_SEQUENCE_specifics_t asn_SPC_GetBoundProfilePackageRequestEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_GetBoundProfilePackageRequestEsipa_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GetBoundProfilePackageRequestEsipa_H_ */
#include <asn_internal.h>
