/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_GetConnectivityParametersRequest_H_
#define	_GetConnectivityParametersRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetConnectivityParametersRequest */
typedef struct GetConnectivityParametersRequest {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetConnectivityParametersRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetConnectivityParametersRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _GetConnectivityParametersRequest_H_ */
#include <asn_internal.h>
