/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_GetEimPackageRequest_H_
#define	_GetEimPackageRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet16.h"
#include <NULL.h>
#include "StateChangeCause.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetEimPackageRequest */
typedef struct GetEimPackageRequest {
	Octet16_t	 eidValue;
	NULL_t	*notifyStateChange	/* OPTIONAL */;
	StateChangeCause_t	*stateChangeCause	/* OPTIONAL */;
	OCTET_STRING_t	*rPLMN	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEimPackageRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEimPackageRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_GetEimPackageRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_GetEimPackageRequest_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _GetEimPackageRequest_H_ */
#include <asn_internal.h>
