/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_GetEimConfigurationDataResponse_H_
#define	_GetEimConfigurationDataResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EimConfigurationData;

/* GetEimConfigurationDataResponse */
typedef struct GetEimConfigurationDataResponse {
	struct GetEimConfigurationDataResponse__eimConfigurationDataList {
		A_SEQUENCE_OF(struct EimConfigurationData) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} eimConfigurationDataList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEimConfigurationDataResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEimConfigurationDataResponse;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EimConfigurationData.h"

#endif	/* _GetEimConfigurationDataResponse_H_ */
#include <asn_internal.h>
