/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_GetEimConfigurationDataRequest_H_
#define	_GetEimConfigurationDataRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetEimConfigurationDataRequest */
typedef struct GetEimConfigurationDataRequest {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEimConfigurationDataRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEimConfigurationDataRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _GetEimConfigurationDataRequest_H_ */
#include <asn_internal.h>
