/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_GetEuiccDataResponse_H_
#define	_GetEuiccDataResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GetEuiccDataResponse */
typedef struct GetEuiccDataResponse {
	Octet16_t	 eidValue;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GetEuiccDataResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GetEuiccDataResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _GetEuiccDataResponse_H_ */
#include <asn_internal.h>
