/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_HandleNotificationEsipa_H_
#define	_HandleNotificationEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SGP32-PendingNotification.h"
#include "ProvideEimPackageResult.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HandleNotificationEsipa_PR {
	HandleNotificationEsipa_PR_NOTHING,	/* No components present */
	HandleNotificationEsipa_PR_pendingNotification,
	HandleNotificationEsipa_PR_provideEimPackageResult
	/* Extensions may appear below */
	
} HandleNotificationEsipa_PR;

/* HandleNotificationEsipa */
typedef struct HandleNotificationEsipa {
	HandleNotificationEsipa_PR present;
	union HandleNotificationEsipa_u {
		SGP32_PendingNotification_t	 pendingNotification;
		ProvideEimPackageResult_t	 provideEimPackageResult;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} HandleNotificationEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HandleNotificationEsipa;
extern asn_CHOICE_specifics_t asn_SPC_HandleNotificationEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_HandleNotificationEsipa_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _HandleNotificationEsipa_H_ */
#include <asn_internal.h>
