/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "HandleNotificationEsipa.h"

static asn_oer_constraints_t asn_OER_type_HandleNotificationEsipa_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_HandleNotificationEsipa_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_HandleNotificationEsipa_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct HandleNotificationEsipa, choice.pendingNotification),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_SGP32_PendingNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pendingNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct HandleNotificationEsipa, choice.provideEimPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProvideEimPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"provideEimPackageResult"
		},
};
static const ber_tlv_tag_t asn_DEF_HandleNotificationEsipa_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (61 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HandleNotificationEsipa_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pendingNotification */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 1, 0, 0 } /* provideEimPackageResult */
};
asn_CHOICE_specifics_t asn_SPC_HandleNotificationEsipa_specs_1 = {
	sizeof(struct HandleNotificationEsipa),
	offsetof(struct HandleNotificationEsipa, _asn_ctx),
	offsetof(struct HandleNotificationEsipa, present),
	sizeof(((struct HandleNotificationEsipa *)0)->present),
	asn_MAP_HandleNotificationEsipa_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_HandleNotificationEsipa = {
	"HandleNotificationEsipa",
	"HandleNotificationEsipa",
	&asn_OP_CHOICE,
	asn_DEF_HandleNotificationEsipa_tags_1,
	sizeof(asn_DEF_HandleNotificationEsipa_tags_1)
		/sizeof(asn_DEF_HandleNotificationEsipa_tags_1[0]), /* 1 */
	asn_DEF_HandleNotificationEsipa_tags_1,	/* Same as above */
	sizeof(asn_DEF_HandleNotificationEsipa_tags_1)
		/sizeof(asn_DEF_HandleNotificationEsipa_tags_1[0]), /* 1 */
	{ &asn_OER_type_HandleNotificationEsipa_constr_1, &asn_PER_type_HandleNotificationEsipa_constr_1, CHOICE_constraint },
	asn_MBR_HandleNotificationEsipa_1,
	2,	/* Elements count */
	&asn_SPC_HandleNotificationEsipa_specs_1	/* Additional specs */
};

