/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_ImmediateEnableResponse_H_
#define	_ImmediateEnableResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ImmediateEnableResponse__immediateEnableResult {
	ImmediateEnableResponse__immediateEnableResult_ok	= 0,
	ImmediateEnableResponse__immediateEnableResult_immediateEnableNotAvailable	= 1,
	ImmediateEnableResponse__immediateEnableResult_noSessionContext	= 4,
	ImmediateEnableResponse__immediateEnableResult_catBusy	= 5,
	ImmediateEnableResponse__immediateEnableResult_undefinedError	= 127
} e_ImmediateEnableResponse__immediateEnableResult;

/* ImmediateEnableResponse */
typedef struct ImmediateEnableResponse {
	long	 immediateEnableResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImmediateEnableResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImmediateEnableResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _ImmediateEnableResponse_H_ */
#include <asn_internal.h>
