/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "InitiateAuthenticationRequestEsipa.h"

asn_TYPE_member_t asn_MBR_InitiateAuthenticationRequestEsipa_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateAuthenticationRequestEsipa, euiccChallenge),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccChallenge"
		},
	{ ATF_POINTER, 3, offsetof(struct InitiateAuthenticationRequestEsipa, smdpAddress),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpAddress"
		},
	{ ATF_POINTER, 2, offsetof(struct InitiateAuthenticationRequestEsipa, euiccInfo1),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		0,
		&asn_DEF_EUICCInfo1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccInfo1"
		},
	{ ATF_POINTER, 1, offsetof(struct InitiateAuthenticationRequestEsipa, eimTransactionId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimTransactionId"
		},
};
static const int asn_MAP_InitiateAuthenticationRequestEsipa_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_InitiateAuthenticationRequestEsipa_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiateAuthenticationRequestEsipa_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* euiccChallenge */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 3, 0, 0 }, /* eimTransactionId */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 1, 0, 0 }, /* smdpAddress */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 2, 0, 0 } /* euiccInfo1 */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiateAuthenticationRequestEsipa_specs_1 = {
	sizeof(struct InitiateAuthenticationRequestEsipa),
	offsetof(struct InitiateAuthenticationRequestEsipa, _asn_ctx),
	asn_MAP_InitiateAuthenticationRequestEsipa_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_InitiateAuthenticationRequestEsipa_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationRequestEsipa = {
	"InitiateAuthenticationRequestEsipa",
	"InitiateAuthenticationRequestEsipa",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiateAuthenticationRequestEsipa_tags_1,
	sizeof(asn_DEF_InitiateAuthenticationRequestEsipa_tags_1)
		/sizeof(asn_DEF_InitiateAuthenticationRequestEsipa_tags_1[0]) - 1, /* 1 */
	asn_DEF_InitiateAuthenticationRequestEsipa_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiateAuthenticationRequestEsipa_tags_1)
		/sizeof(asn_DEF_InitiateAuthenticationRequestEsipa_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitiateAuthenticationRequestEsipa_1,
	4,	/* Elements count */
	&asn_SPC_InitiateAuthenticationRequestEsipa_specs_1	/* Additional specs */
};

