/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "InitiateAuthenticationOkEsipa.h"

asn_TYPE_member_t asn_MBR_InitiateAuthenticationOkEsipa_1[] = {
	{ ATF_POINTER, 1, offsetof(struct InitiateAuthenticationOkEsipa, transactionId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transactionId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateAuthenticationOkEsipa, serverSigned1),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ServerSigned1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverSigned1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateAuthenticationOkEsipa, serverSignature1),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverSignature1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateAuthenticationOkEsipa, euiccCiPKIdToBeUsed),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKIdToBeUsed"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct InitiateAuthenticationOkEsipa, serverCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serverCertificate"
		},
	{ ATF_POINTER, 2, offsetof(struct InitiateAuthenticationOkEsipa, matchingId),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"matchingId"
		},
	{ ATF_POINTER, 1, offsetof(struct InitiateAuthenticationOkEsipa, ctxParams1),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CtxParams1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ctxParams1"
		},
};
static const ber_tlv_tag_t asn_DEF_InitiateAuthenticationOkEsipa_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_InitiateAuthenticationOkEsipa_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 3, 0, 0 }, /* euiccCiPKIdToBeUsed */
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 5, 0, 0 }, /* matchingId */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 1 }, /* serverSigned1 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 4, -1, 0 }, /* serverCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 2, 0, 0 }, /* serverSignature1 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* transactionId */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 6, 0, 0 } /* ctxParams1 */
};
asn_SEQUENCE_specifics_t asn_SPC_InitiateAuthenticationOkEsipa_specs_1 = {
	sizeof(struct InitiateAuthenticationOkEsipa),
	offsetof(struct InitiateAuthenticationOkEsipa, _asn_ctx),
	asn_MAP_InitiateAuthenticationOkEsipa_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationOkEsipa = {
	"InitiateAuthenticationOkEsipa",
	"InitiateAuthenticationOkEsipa",
	&asn_OP_SEQUENCE,
	asn_DEF_InitiateAuthenticationOkEsipa_tags_1,
	sizeof(asn_DEF_InitiateAuthenticationOkEsipa_tags_1)
		/sizeof(asn_DEF_InitiateAuthenticationOkEsipa_tags_1[0]), /* 1 */
	asn_DEF_InitiateAuthenticationOkEsipa_tags_1,	/* Same as above */
	sizeof(asn_DEF_InitiateAuthenticationOkEsipa_tags_1)
		/sizeof(asn_DEF_InitiateAuthenticationOkEsipa_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_InitiateAuthenticationOkEsipa_1,
	7,	/* Elements count */
	&asn_SPC_InitiateAuthenticationOkEsipa_specs_1	/* Additional specs */
};

