/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_InitiateAuthenticationRequestEsipa_H_
#define	_InitiateAuthenticationRequestEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Octet16.h"
#include <UTF8String.h>
#include "TransactionId.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUICCInfo1;

/* InitiateAuthenticationRequestEsipa */
typedef struct InitiateAuthenticationRequestEsipa {
	Octet16_t	 euiccChallenge;
	UTF8String_t	*smdpAddress	/* OPTIONAL */;
	struct EUICCInfo1	*euiccInfo1	/* OPTIONAL */;
	TransactionId_t	*eimTransactionId	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateAuthenticationRequestEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationRequestEsipa;
extern asn_SEQUENCE_specifics_t asn_SPC_InitiateAuthenticationRequestEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiateAuthenticationRequestEsipa_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EUICCInfo1.h"

#endif	/* _InitiateAuthenticationRequestEsipa_H_ */
#include <asn_internal.h>
