/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_InitiateAuthenticationResponseEsipa_H_
#define	_InitiateAuthenticationResponseEsipa_H_


#include <asn_application.h>

/* Including external dependencies */
#include "InitiateAuthenticationOkEsipa.h"
#include <NativeInteger.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum InitiateAuthenticationResponseEsipa_PR {
	InitiateAuthenticationResponseEsipa_PR_NOTHING,	/* No components present */
	InitiateAuthenticationResponseEsipa_PR_initiateAuthenticationOkEsipa,
	InitiateAuthenticationResponseEsipa_PR_initiateAuthenticationErrorEsipa
	/* Extensions may appear below */
	
} InitiateAuthenticationResponseEsipa_PR;
typedef enum InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa {
	InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa_invalidDpAddress	= 1,
	InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa_euiccVersionNotSupportedByDp	= 2,
	InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa_ciPKIdNotSupported	= 3,
	InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa_smdpAddressMismatch	= 50,
	InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa_smdpOidMismatch	= 51
} e_InitiateAuthenticationResponseEsipa__initiateAuthenticationErrorEsipa;

/* InitiateAuthenticationResponseEsipa */
typedef struct InitiateAuthenticationResponseEsipa {
	InitiateAuthenticationResponseEsipa_PR present;
	union InitiateAuthenticationResponseEsipa_u {
		InitiateAuthenticationOkEsipa_t	 initiateAuthenticationOkEsipa;
		long	 initiateAuthenticationErrorEsipa;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} InitiateAuthenticationResponseEsipa_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InitiateAuthenticationResponseEsipa;
extern asn_CHOICE_specifics_t asn_SPC_InitiateAuthenticationResponseEsipa_specs_1;
extern asn_TYPE_member_t asn_MBR_InitiateAuthenticationResponseEsipa_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _InitiateAuthenticationResponseEsipa_H_ */
#include <asn_internal.h>
