/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_IpaeActivationRequest_H_
#define	_IpaeActivationRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpaeActivationRequest__ipaeOption {
	IpaeActivationRequest__ipaeOption_activateIpae	= 0
} e_IpaeActivationRequest__ipaeOption;

/* IpaeActivationRequest */
typedef struct IpaeActivationRequest {
	BIT_STRING_t	 ipaeOption;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpaeActivationRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpaeActivationRequest;

#ifdef __cplusplus
}
#endif

#endif	/* _IpaeActivationRequest_H_ */
#include <asn_internal.h>
