/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "IpaEuiccDataRequest.h"

static asn_TYPE_member_t asn_MBR_searchCriteria_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpaEuiccDataRequest__searchCriteria, choice.seqNumber),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"seqNumber"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpaEuiccDataRequest__searchCriteria, choice.profileManagementOperation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NotificationEvent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileManagementOperation"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct IpaEuiccDataRequest__searchCriteria, choice.euiccPackageResults),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResults"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_searchCriteria_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* seqNumber */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* profileManagementOperation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* euiccPackageResults */
};
static asn_CHOICE_specifics_t asn_SPC_searchCriteria_specs_4 = {
	sizeof(struct IpaEuiccDataRequest__searchCriteria),
	offsetof(struct IpaEuiccDataRequest__searchCriteria, _asn_ctx),
	offsetof(struct IpaEuiccDataRequest__searchCriteria, present),
	sizeof(((struct IpaEuiccDataRequest__searchCriteria *)0)->present),
	asn_MAP_searchCriteria_tag2el_4,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_searchCriteria_4 = {
	"searchCriteria",
	"searchCriteria",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_searchCriteria_4,
	3,	/* Elements count */
	&asn_SPC_searchCriteria_specs_4	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_IpaEuiccDataRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct IpaEuiccDataRequest, tagList),
		(ASN_TAG_CLASS_APPLICATION | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"tagList"
		},
	{ ATF_POINTER, 2, offsetof(struct IpaEuiccDataRequest, euiccCiPKId),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_SubjectKeyIdentifier,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccCiPKId"
		},
	{ ATF_POINTER, 1, offsetof(struct IpaEuiccDataRequest, searchCriteria),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_searchCriteria_4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"searchCriteria"
		},
};
static const ber_tlv_tag_t asn_DEF_IpaEuiccDataRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IpaEuiccDataRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* euiccCiPKId */
    { (ASN_TAG_CLASS_APPLICATION | (28 << 2)), 0, 0, 0 }, /* tagList */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 2, 0, 0 } /* searchCriteria */
};
asn_SEQUENCE_specifics_t asn_SPC_IpaEuiccDataRequest_specs_1 = {
	sizeof(struct IpaEuiccDataRequest),
	offsetof(struct IpaEuiccDataRequest, _asn_ctx),
	asn_MAP_IpaEuiccDataRequest_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IpaEuiccDataRequest = {
	"IpaEuiccDataRequest",
	"IpaEuiccDataRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_IpaEuiccDataRequest_tags_1,
	sizeof(asn_DEF_IpaEuiccDataRequest_tags_1)
		/sizeof(asn_DEF_IpaEuiccDataRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_IpaEuiccDataRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_IpaEuiccDataRequest_tags_1)
		/sizeof(asn_DEF_IpaEuiccDataRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_IpaEuiccDataRequest_1,
	3,	/* Elements count */
	&asn_SPC_IpaEuiccDataRequest_specs_1	/* Additional specs */
};

