/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_IpaEuiccData_H_
#define	_IpaEuiccData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUICCInfo1;
struct SGP32_EUICCInfo2;
struct Certificate;
struct IpaCapabilities;
struct DeviceInfo;
struct SGP32_RetrieveNotificationsListResponse;

/* IpaEuiccData */
typedef struct IpaEuiccData {
	UTF8String_t	*defaultSmdpAddress	/* OPTIONAL */;
	struct EUICCInfo1	*euiccInfo1	/* OPTIONAL */;
	struct SGP32_EUICCInfo2	*euiccInfo2	/* OPTIONAL */;
	UTF8String_t	*rootSmdsAddress	/* OPTIONAL */;
	long	*associationToken	/* OPTIONAL */;
	struct Certificate	*eumCertificate	/* OPTIONAL */;
	struct Certificate	*euiccCertificate	/* OPTIONAL */;
	struct IpaCapabilities	*ipaCapabilities	/* OPTIONAL */;
	struct DeviceInfo	*deviceInfo	/* OPTIONAL */;
	struct SGP32_RetrieveNotificationsListResponse	*notificationsList	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpaEuiccData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpaEuiccData;
extern asn_SEQUENCE_specifics_t asn_SPC_IpaEuiccData_specs_1;
extern asn_TYPE_member_t asn_MBR_IpaEuiccData_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EUICCInfo1.h"
#include "SGP32-EUICCInfo2.h"
#include "Certificate.h"
#include "IpaCapabilities.h"
#include "DeviceInfo.h"
#include "SGP32-RetrieveNotificationsListResponse.h"

#endif	/* _IpaEuiccData_H_ */
#include <asn_internal.h>
