/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_IpaeActivationResponse_H_
#define	_IpaeActivationResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpaeActivationResponse__ipaeActivationResult {
	IpaeActivationResponse__ipaeActivationResult_ok	= 0,
	IpaeActivationResponse__ipaeActivationResult_notSupported	= 1
} e_IpaeActivationResponse__ipaeActivationResult;

/* IpaeActivationResponse */
typedef struct IpaeActivationResponse {
	long	 ipaeActivationResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IpaeActivationResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpaeActivationResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _IpaeActivationResponse_H_ */
#include <asn_internal.h>
