/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_IpaEuiccDataErrorCode_H_
#define	_IpaEuiccDataErrorCode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpaEuiccDataErrorCode {
	IpaEuiccDataErrorCode_incorrectTagList	= 1,
	IpaEuiccDataErrorCode_euiccCiPKIdNotFound	= 5,
	IpaEuiccDataErrorCode_ecallActive	= 104,
	IpaEuiccDataErrorCode_undefinedError	= 127
} e_IpaEuiccDataErrorCode;

/* IpaEuiccDataErrorCode */
typedef long	 IpaEuiccDataErrorCode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpaEuiccDataErrorCode;
asn_struct_free_f IpaEuiccDataErrorCode_free;
asn_struct_print_f IpaEuiccDataErrorCode_print;
asn_constr_check_f IpaEuiccDataErrorCode_constraint;
ber_type_decoder_f IpaEuiccDataErrorCode_decode_ber;
der_type_encoder_f IpaEuiccDataErrorCode_encode_der;
xer_type_decoder_f IpaEuiccDataErrorCode_decode_xer;
xer_type_encoder_f IpaEuiccDataErrorCode_encode_xer;
oer_type_decoder_f IpaEuiccDataErrorCode_decode_oer;
oer_type_encoder_f IpaEuiccDataErrorCode_encode_oer;
per_type_decoder_f IpaEuiccDataErrorCode_decode_uper;
per_type_encoder_f IpaEuiccDataErrorCode_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _IpaEuiccDataErrorCode_H_ */
#include <asn_internal.h>
