/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_IpaMode_H_
#define	_IpaMode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IpaMode {
	IpaMode_ipad	= 0,
	IpaMode_ipae	= 1
} e_IpaMode;

/* IpaMode */
typedef long	 IpaMode_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IpaMode;
asn_struct_free_f IpaMode_free;
asn_struct_print_f IpaMode_print;
asn_constr_check_f IpaMode_constraint;
ber_type_decoder_f IpaMode_decode_ber;
der_type_encoder_f IpaMode_encode_der;
xer_type_decoder_f IpaMode_decode_xer;
xer_type_encoder_f IpaMode_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IpaMode_H_ */
#include <asn_internal.h>
