/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_ISDRProprietaryApplicationTemplateIoT_H_
#define	_ISDRProprietaryApplicationTemplateIoT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ISDRProprietaryApplicationTemplateIoT__euiccConfiguration {
	ISDRProprietaryApplicationTemplateIoT__euiccConfiguration_ipaeSupported	= 0,
	ISDRProprietaryApplicationTemplateIoT__euiccConfiguration_enabledProfile	= 1
} e_ISDRProprietaryApplicationTemplateIoT__euiccConfiguration;

/* ISDRProprietaryApplicationTemplateIoT */
typedef struct ISDRProprietaryApplicationTemplateIoT {
	BIT_STRING_t	 euiccConfiguration;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ISDRProprietaryApplicationTemplateIoT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ISDRProprietaryApplicationTemplateIoT;

#ifdef __cplusplus
}
#endif

#endif	/* _ISDRProprietaryApplicationTemplateIoT_H_ */
#include <asn_internal.h>
