/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Implicit88"
 * 	found in "../../../asn1/PKIX1Implicit88.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "IssuerAltName.h"

/*
 * This type is implemented using GeneralNames,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_IssuerAltName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_IssuerAltName = {
	"IssuerAltName",
	"IssuerAltName",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_IssuerAltName_tags_1,
	sizeof(asn_DEF_IssuerAltName_tags_1)
		/sizeof(asn_DEF_IssuerAltName_tags_1[0]), /* 1 */
	asn_DEF_IssuerAltName_tags_1,	/* Same as above */
	sizeof(asn_DEF_IssuerAltName_tags_1)
		/sizeof(asn_DEF_IssuerAltName_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_GeneralNames_1,
	1,	/* Single element */
	&asn_SPC_GeneralNames_specs_1	/* Additional specs */
};

