/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_NotificationSentResponse_H_
#define	_NotificationSentResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NotificationSentResponse__deleteNotificationStatus {
	NotificationSentResponse__deleteNotificationStatus_ok	= 0,
	NotificationSentResponse__deleteNotificationStatus_nothingToDelete	= 1,
	NotificationSentResponse__deleteNotificationStatus_undefinedError	= 127
} e_NotificationSentResponse__deleteNotificationStatus;

/* NotificationSentResponse */
typedef struct NotificationSentResponse {
	long	 deleteNotificationStatus;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NotificationSentResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NotificationSentResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _NotificationSentResponse_H_ */
#include <asn_internal.h>
