/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_Octet4_H_
#define	_Octet4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Octet4 */
typedef OCTET_STRING_t	 Octet4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Octet4;
asn_struct_free_f Octet4_free;
asn_struct_print_f Octet4_print;
asn_constr_check_f Octet4_constraint;
ber_type_decoder_f Octet4_decode_ber;
der_type_encoder_f Octet4_encode_der;
xer_type_decoder_f Octet4_decode_xer;
xer_type_encoder_f Octet4_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _Octet4_H_ */
#include <asn_internal.h>
