/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_OperatorId_H_
#define	_OperatorId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* OperatorId */
typedef struct OperatorId {
	OCTET_STRING_t	 mccMnc;
	OCTET_STRING_t	*gid1	/* OPTIONAL */;
	OCTET_STRING_t	*gid2	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OperatorId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OperatorId;
extern asn_SEQUENCE_specifics_t asn_SPC_OperatorId_specs_1;
extern asn_TYPE_member_t asn_MBR_OperatorId_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _OperatorId_H_ */
#include <asn_internal.h>
