/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PartialCrlNumber_H_
#define	_PartialCrlNumber_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PartialCrlNumber */
typedef long	 PartialCrlNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartialCrlNumber;
asn_struct_free_f PartialCrlNumber_free;
asn_struct_print_f PartialCrlNumber_print;
asn_constr_check_f PartialCrlNumber_constraint;
ber_type_decoder_f PartialCrlNumber_decode_ber;
der_type_encoder_f PartialCrlNumber_encode_der;
xer_type_decoder_f PartialCrlNumber_decode_xer;
xer_type_encoder_f PartialCrlNumber_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PartialCrlNumber_H_ */
#include <asn_internal.h>
