/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PE_AKAParameter_H_
#define	_PE_AKAParameter_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OCTET_STRING.h>
#include "MappingParameter.h"
#include "AlgoParameter.h"
#include <constr_CHOICE.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PE_AKAParameter__algoConfiguration_PR {
	PE_AKAParameter__algoConfiguration_PR_NOTHING,	/* No components present */
	PE_AKAParameter__algoConfiguration_PR_mappingParameter,
	PE_AKAParameter__algoConfiguration_PR_algoParameter
	/* Extensions may appear below */
	
} PE_AKAParameter__algoConfiguration_PR;

/* PE-AKAParameter */
typedef struct PE_AKAParameter {
	PEHeader_t	 aka_header;
	struct PE_AKAParameter__algoConfiguration {
		PE_AKAParameter__algoConfiguration_PR present;
		union PE_AKAParameter__algoConfiguration_u {
			MappingParameter_t	 mappingParameter;
			AlgoParameter_t	 algoParameter;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} algoConfiguration;
	OCTET_STRING_t	*sqnOptions	/* DEFAULT '02'HH00000000000000000000000000000000000000000000000000000000001000000000000000000000000000000020000000000000000000000000000000400000000000000000000000000000008'HH */;
	OCTET_STRING_t	*sqnDelta	/* DEFAULT '000010000000'HH0000000000000000000000000000000000000000000000001000000000000000000000000000000020000000000000000000000000000000400000000000000000000000000000008'HH */;
	OCTET_STRING_t	*sqnAgeLimit	/* DEFAULT '000010000000'HH0000000000000000000000000000000000000000000000001000000000000000000000000000000020000000000000000000000000000000400000000000000000000000000000008'HH */;
	struct PE_AKAParameter__sqnInit {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sqnInit;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_AKAParameter_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_AKAParameter;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_AKAParameter_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_AKAParameter_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _PE_AKAParameter_H_ */
#include <asn_internal.h>
