/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PE_CSIM_H_
#define	_PE_CSIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include "File.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PE-CSIM */
typedef struct PE_CSIM {
	PEHeader_t	 csim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	File_t	 adf_csim;
	File_t	 ef_arr;
	File_t	 ef_call_count;
	File_t	 ef_imsi_m;
	File_t	 ef_imsi_t;
	File_t	 ef_tmsi;
	File_t	 ef_ah;
	File_t	 ef_aop;
	File_t	 ef_aloc;
	File_t	 ef_cdmahome;
	File_t	 ef_znregi;
	File_t	 ef_snregi;
	File_t	 ef_distregi;
	File_t	 ef_accolc;
	File_t	 ef_term;
	File_t	 ef_acp;
	File_t	 ef_prl;
	File_t	 ef_ruimid;
	File_t	 ef_csim_st;
	File_t	 ef_spc;
	File_t	 ef_otapaspc;
	File_t	 ef_namlock;
	File_t	 ef_ota;
	File_t	 ef_sp;
	File_t	 ef_esn_meid_me;
	File_t	 ef_li;
	File_t	 ef_usgind;
	File_t	 ef_ad;
	File_t	 ef_max_prl;
	File_t	 ef_spcs;
	File_t	 ef_mecrp;
	File_t	 ef_home_tag;
	File_t	 ef_group_tag;
	File_t	 ef_specific_tag;
	File_t	 ef_call_prompt;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_CSIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_CSIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_CSIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_CSIM_1[37];

#ifdef __cplusplus
}
#endif

#endif	/* _PE_CSIM_H_ */
#include <asn_internal.h>
