/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "PE-Dummy.h"

static const ber_tlv_tag_t asn_DEF_PE_Dummy_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SEQUENCE_specifics_t asn_SPC_PE_Dummy_specs_1 = {
	sizeof(struct PE_Dummy),
	offsetof(struct PE_Dummy, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_Dummy = {
	"PE-Dummy",
	"PE-Dummy",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_Dummy_tags_1,
	sizeof(asn_DEF_PE_Dummy_tags_1)
		/sizeof(asn_DEF_PE_Dummy_tags_1[0]), /* 1 */
	asn_DEF_PE_Dummy_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_Dummy_tags_1)
		/sizeof(asn_DEF_PE_Dummy_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	0, 0,	/* No members */
	&asn_SPC_PE_Dummy_specs_1	/* Additional specs */
};

