/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PE_DF_SNPN_H_
#define	_PE_DF_SNPN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include "File.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-DF-SNPN */
typedef struct PE_DF_SNPN {
	PEHeader_t	 df_snpn_header;
	OBJECT_IDENTIFIER_t	 templateID;
	File_t	 df_df_snpn;
	struct File	*ef_pws_snpn	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_DF_SNPN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_DF_SNPN;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_DF_SNPN_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_DF_SNPN_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_DF_SNPN_H_ */
#include <asn_internal.h>
