/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_End_H_
#define	_PE_End_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PE-End */
typedef struct PE_End {
	PEHeader_t	 end_header;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_End_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_End;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_End_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_End_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _PE_End_H_ */
#include <asn_internal.h>
