/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "PE-EAP.h"

asn_TYPE_member_t asn_MBR_PE_EAP_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PE_EAP, eap_header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PEHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eap-header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_EAP, templateID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"templateID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_EAP, df_eap),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-eap"
		},
	{ ATF_POINTER, 1, offsetof(struct PE_EAP, ef_eapkeys),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-eapkeys"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_EAP, ef_eapstatus),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-eapstatus"
		},
	{ ATF_POINTER, 5, offsetof(struct PE_EAP, ef_puid),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-puid"
		},
	{ ATF_POINTER, 4, offsetof(struct PE_EAP, ef_ps),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ps"
		},
	{ ATF_POINTER, 3, offsetof(struct PE_EAP, ef_curid),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-curid"
		},
	{ ATF_POINTER, 2, offsetof(struct PE_EAP, ef_reid),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-reid"
		},
	{ ATF_POINTER, 1, offsetof(struct PE_EAP, ef_realm),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-realm"
		},
};
static const ber_tlv_tag_t asn_DEF_PE_EAP_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PE_EAP_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* eap-header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* templateID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* df-eap */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ef-eapkeys */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ef-eapstatus */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ef-puid */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ef-ps */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ef-curid */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ef-reid */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* ef-realm */
};
asn_SEQUENCE_specifics_t asn_SPC_PE_EAP_specs_1 = {
	sizeof(struct PE_EAP),
	offsetof(struct PE_EAP, _asn_ctx),
	asn_MAP_PE_EAP_tag2el_1,
	10,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_EAP = {
	"PE-EAP",
	"PE-EAP",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_EAP_tags_1,
	sizeof(asn_DEF_PE_EAP_tags_1)
		/sizeof(asn_DEF_PE_EAP_tags_1[0]), /* 1 */
	asn_DEF_PE_EAP_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_EAP_tags_1)
		/sizeof(asn_DEF_PE_EAP_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PE_EAP_1,
	10,	/* Elements count */
	&asn_SPC_PE_EAP_specs_1	/* Additional specs */
};

