/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "PE-GSM-ACCESS.h"

asn_TYPE_member_t asn_MBR_PE_GSM_ACCESS_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PE_GSM_ACCESS, gsm_access_header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PEHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gsm-access-header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_GSM_ACCESS, templateID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"templateID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_GSM_ACCESS, df_gsm_access),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-gsm-access"
		},
	{ ATF_POINTER, 4, offsetof(struct PE_GSM_ACCESS, ef_kc),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-kc"
		},
	{ ATF_POINTER, 3, offsetof(struct PE_GSM_ACCESS, ef_kcgprs),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-kcgprs"
		},
	{ ATF_POINTER, 2, offsetof(struct PE_GSM_ACCESS, ef_cpbcch),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cpbcch"
		},
	{ ATF_POINTER, 1, offsetof(struct PE_GSM_ACCESS, ef_invscan),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-invscan"
		},
};
static const ber_tlv_tag_t asn_DEF_PE_GSM_ACCESS_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PE_GSM_ACCESS_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gsm-access-header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* templateID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* df-gsm-access */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ef-kc */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ef-kcgprs */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ef-cpbcch */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 } /* ef-invscan */
};
asn_SEQUENCE_specifics_t asn_SPC_PE_GSM_ACCESS_specs_1 = {
	sizeof(struct PE_GSM_ACCESS),
	offsetof(struct PE_GSM_ACCESS, _asn_ctx),
	asn_MAP_PE_GSM_ACCESS_tag2el_1,
	7,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	7,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_GSM_ACCESS = {
	"PE-GSM-ACCESS",
	"PE-GSM-ACCESS",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_GSM_ACCESS_tags_1,
	sizeof(asn_DEF_PE_GSM_ACCESS_tags_1)
		/sizeof(asn_DEF_PE_GSM_ACCESS_tags_1[0]), /* 1 */
	asn_DEF_PE_GSM_ACCESS_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_GSM_ACCESS_tags_1)
		/sizeof(asn_DEF_PE_GSM_ACCESS_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PE_GSM_ACCESS_1,
	7,	/* Elements count */
	&asn_SPC_PE_GSM_ACCESS_specs_1	/* Additional specs */
};

