/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "PE-GenericFileManagement.h"

static int
memb_fileManagementCMD_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_TYPE_member_t asn_MBR_fileManagementCMD_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_FileManagement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_fileManagementCMD_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_fileManagementCMD_specs_3 = {
	sizeof(struct PE_GenericFileManagement__fileManagementCMD),
	offsetof(struct PE_GenericFileManagement__fileManagementCMD, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fileManagementCMD_3 = {
	"fileManagementCMD",
	"fileManagementCMD",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_fileManagementCMD_tags_3,
	sizeof(asn_DEF_fileManagementCMD_tags_3)
		/sizeof(asn_DEF_fileManagementCMD_tags_3[0]) - 1, /* 1 */
	asn_DEF_fileManagementCMD_tags_3,	/* Same as above */
	sizeof(asn_DEF_fileManagementCMD_tags_3)
		/sizeof(asn_DEF_fileManagementCMD_tags_3[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_fileManagementCMD_3,
	1,	/* Single element */
	&asn_SPC_fileManagementCMD_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_PE_GenericFileManagement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PE_GenericFileManagement, gfm_header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PEHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gfm-header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_GenericFileManagement, fileManagementCMD),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_fileManagementCMD_3,
		0,
		{ 0, 0,  memb_fileManagementCMD_constraint_1 },
		0, 0, /* No default value */
		"fileManagementCMD"
		},
};
static const ber_tlv_tag_t asn_DEF_PE_GenericFileManagement_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PE_GenericFileManagement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* gfm-header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* fileManagementCMD */
};
asn_SEQUENCE_specifics_t asn_SPC_PE_GenericFileManagement_specs_1 = {
	sizeof(struct PE_GenericFileManagement),
	offsetof(struct PE_GenericFileManagement, _asn_ctx),
	asn_MAP_PE_GenericFileManagement_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_GenericFileManagement = {
	"PE-GenericFileManagement",
	"PE-GenericFileManagement",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_GenericFileManagement_tags_1,
	sizeof(asn_DEF_PE_GenericFileManagement_tags_1)
		/sizeof(asn_DEF_PE_GenericFileManagement_tags_1[0]), /* 1 */
	asn_DEF_PE_GenericFileManagement_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_GenericFileManagement_tags_1)
		/sizeof(asn_DEF_PE_GenericFileManagement_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PE_GenericFileManagement_1,
	2,	/* Elements count */
	&asn_SPC_PE_GenericFileManagement_specs_1	/* Additional specs */
};

