/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_ISIM_H_
#define	_PE_ISIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include "File.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-ISIM */
typedef struct PE_ISIM {
	PEHeader_t	 isim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	File_t	 adf_isim;
	File_t	 ef_impi;
	File_t	 ef_impu;
	File_t	 ef_domain;
	File_t	 ef_ist;
	struct File	*ef_ad	/* OPTIONAL */;
	File_t	 ef_arr;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_ISIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_ISIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_ISIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_ISIM_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_ISIM_H_ */
#include <asn_internal.h>
