/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "PE-OPT-IoT.h"

asn_TYPE_member_t asn_MBR_PE_OPT_IoT_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PE_OPT_IoT, optiot_header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PEHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"optiot-header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_OPT_IoT, templateID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"templateID"
		},
	{ ATF_POINTER, 26, offsetof(struct PE_OPT_IoT, ef_fdn),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-fdn"
		},
	{ ATF_POINTER, 25, offsetof(struct PE_OPT_IoT, ef_sms),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-sms"
		},
	{ ATF_POINTER, 24, offsetof(struct PE_OPT_IoT, ef_smsp),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-smsp"
		},
	{ ATF_POINTER, 23, offsetof(struct PE_OPT_IoT, ef_smss),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-smss"
		},
	{ ATF_POINTER, 22, offsetof(struct PE_OPT_IoT, ef_spn),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-spn"
		},
	{ ATF_POINTER, 21, offsetof(struct PE_OPT_IoT, ef_est),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-est"
		},
	{ ATF_POINTER, 20, offsetof(struct PE_OPT_IoT, ef_oplmnwact),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-oplmnwact"
		},
	{ ATF_POINTER, 19, offsetof(struct PE_OPT_IoT, ef_hplmnwact),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-hplmnwact"
		},
	{ ATF_POINTER, 18, offsetof(struct PE_OPT_IoT, ef_ehplmn),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ehplmn"
		},
	{ ATF_POINTER, 17, offsetof(struct PE_OPT_IoT, ef_epsloci),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epsloci"
		},
	{ ATF_POINTER, 16, offsetof(struct PE_OPT_IoT, ef_epsnsc),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epsnsc"
		},
	{ ATF_POINTER, 15, offsetof(struct PE_OPT_IoT, df_df_5gs),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-df-5gs"
		},
	{ ATF_POINTER, 14, offsetof(struct PE_OPT_IoT, ef_5gs3gpploci),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-5gs3gpploci"
		},
	{ ATF_POINTER, 13, offsetof(struct PE_OPT_IoT, ef_5gsn3gpploci),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-5gsn3gpploci"
		},
	{ ATF_POINTER, 12, offsetof(struct PE_OPT_IoT, ef_5gs3gppnsc),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-5gs3gppnsc"
		},
	{ ATF_POINTER, 11, offsetof(struct PE_OPT_IoT, ef_5gsn3gppnsc),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-5gsn3gppnsc"
		},
	{ ATF_POINTER, 10, offsetof(struct PE_OPT_IoT, ef_5gauthkeys),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-5gauthkeys"
		},
	{ ATF_POINTER, 9, offsetof(struct PE_OPT_IoT, ef_uac_aic),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-uac-aic"
		},
	{ ATF_POINTER, 8, offsetof(struct PE_OPT_IoT, ef_suci_calc_info),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-suci-calc-info"
		},
	{ ATF_POINTER, 7, offsetof(struct PE_OPT_IoT, ef_opl5g),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-opl5g"
		},
	{ ATF_POINTER, 6, offsetof(struct PE_OPT_IoT, ef_supi_nai),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-supi-nai"
		},
	{ ATF_POINTER, 5, offsetof(struct PE_OPT_IoT, ef_routing_indicator),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-routing-indicator"
		},
	{ ATF_POINTER, 4, offsetof(struct PE_OPT_IoT, ef_ursp),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ursp"
		},
	{ ATF_POINTER, 3, offsetof(struct PE_OPT_IoT, ef_tn3gppsnn),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-tn3gppsnn"
		},
	{ ATF_POINTER, 2, offsetof(struct PE_OPT_IoT, df_df_saip),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-df-saip"
		},
	{ ATF_POINTER, 1, offsetof(struct PE_OPT_IoT, ef_suci_calc_info_usim),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-suci-calc-info-usim"
		},
};
static const ber_tlv_tag_t asn_DEF_PE_OPT_IoT_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PE_OPT_IoT_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* optiot-header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* templateID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ef-fdn */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ef-sms */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ef-smsp */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ef-smss */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ef-spn */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ef-est */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ef-oplmnwact */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ef-hplmnwact */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* ef-ehplmn */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* ef-epsloci */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* ef-epsnsc */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* df-df-5gs */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* ef-5gs3gpploci */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* ef-5gsn3gpploci */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* ef-5gs3gppnsc */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* ef-5gsn3gppnsc */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* ef-5gauthkeys */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* ef-uac-aic */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* ef-suci-calc-info */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* ef-opl5g */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* ef-supi-nai */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* ef-routing-indicator */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* ef-ursp */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* ef-tn3gppsnn */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* df-df-saip */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 } /* ef-suci-calc-info-usim */
};
asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_IoT_specs_1 = {
	sizeof(struct PE_OPT_IoT),
	offsetof(struct PE_OPT_IoT, _asn_ctx),
	asn_MAP_PE_OPT_IoT_tag2el_1,
	28,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	28,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_OPT_IoT = {
	"PE-OPT-IoT",
	"PE-OPT-IoT",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_OPT_IoT_tags_1,
	sizeof(asn_DEF_PE_OPT_IoT_tags_1)
		/sizeof(asn_DEF_PE_OPT_IoT_tags_1[0]), /* 1 */
	asn_DEF_PE_OPT_IoT_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_OPT_IoT_tags_1)
		/sizeof(asn_DEF_PE_OPT_IoT_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PE_OPT_IoT_1,
	28,	/* Elements count */
	&asn_SPC_PE_OPT_IoT_specs_1	/* Additional specs */
};

