/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_OPT_CSIM_H_
#define	_PE_OPT_CSIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-OPT-CSIM */
typedef struct PE_OPT_CSIM {
	PEHeader_t	 optcsim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	struct File	*ef_ssci	/* OPTIONAL */;
	struct File	*ef_fdn	/* OPTIONAL */;
	struct File	*ef_sms	/* OPTIONAL */;
	struct File	*ef_smsp	/* OPTIONAL */;
	struct File	*ef_smss	/* OPTIONAL */;
	struct File	*ef_ssfc	/* OPTIONAL */;
	struct File	*ef_spn	/* OPTIONAL */;
	struct File	*ef_mdn	/* OPTIONAL */;
	struct File	*ef_ecc	/* OPTIONAL */;
	struct File	*ef_me3gpdopc	/* OPTIONAL */;
	struct File	*ef_3gpdopm	/* OPTIONAL */;
	struct File	*ef_sipcap	/* OPTIONAL */;
	struct File	*ef_mipcap	/* OPTIONAL */;
	struct File	*ef_sipupp	/* OPTIONAL */;
	struct File	*ef_mipupp	/* OPTIONAL */;
	struct File	*ef_sipsp	/* OPTIONAL */;
	struct File	*ef_mipsp	/* OPTIONAL */;
	struct File	*ef_sippapss	/* OPTIONAL */;
	struct File	*ef_puzl	/* OPTIONAL */;
	struct File	*ef_maxpuzl	/* OPTIONAL */;
	struct File	*ef_hrpdcap	/* OPTIONAL */;
	struct File	*ef_hrpdupp	/* OPTIONAL */;
	struct File	*ef_csspr	/* OPTIONAL */;
	struct File	*ef_atc	/* OPTIONAL */;
	struct File	*ef_eprl	/* OPTIONAL */;
	struct File	*ef_bcsmscfg	/* OPTIONAL */;
	struct File	*ef_bcsmspref	/* OPTIONAL */;
	struct File	*ef_bcsmstable	/* OPTIONAL */;
	struct File	*ef_bcsmsp	/* OPTIONAL */;
	struct File	*ef_bakpara	/* OPTIONAL */;
	struct File	*ef_upbakpara	/* OPTIONAL */;
	struct File	*ef_mmsn	/* OPTIONAL */;
	struct File	*ef_ext8	/* OPTIONAL */;
	struct File	*ef_mmsicp	/* OPTIONAL */;
	struct File	*ef_mmsup	/* OPTIONAL */;
	struct File	*ef_mmsucp	/* OPTIONAL */;
	struct File	*ef_auth_capability	/* OPTIONAL */;
	struct File	*ef_3gcik	/* OPTIONAL */;
	struct File	*ef_dck	/* OPTIONAL */;
	struct File	*ef_gid1	/* OPTIONAL */;
	struct File	*ef_gid2	/* OPTIONAL */;
	struct File	*ef_cdmacnl	/* OPTIONAL */;
	struct File	*ef_sf_euimid	/* OPTIONAL */;
	struct File	*ef_est	/* OPTIONAL */;
	struct File	*ef_hidden_key	/* OPTIONAL */;
	struct File	*ef_lcsver	/* OPTIONAL */;
	struct File	*ef_lcscp	/* OPTIONAL */;
	struct File	*ef_sdn	/* OPTIONAL */;
	struct File	*ef_ext2	/* OPTIONAL */;
	struct File	*ef_ext3	/* OPTIONAL */;
	struct File	*ef_ici	/* OPTIONAL */;
	struct File	*ef_oci	/* OPTIONAL */;
	struct File	*ef_ext5	/* OPTIONAL */;
	struct File	*ef_ccp2	/* OPTIONAL */;
	struct File	*ef_applabels	/* OPTIONAL */;
	struct File	*ef_model	/* OPTIONAL */;
	struct File	*ef_rc	/* OPTIONAL */;
	struct File	*ef_smscap	/* OPTIONAL */;
	struct File	*ef_mipflags	/* OPTIONAL */;
	struct File	*ef_3gpduppext	/* OPTIONAL */;
	struct File	*ef_ipv6cap	/* OPTIONAL */;
	struct File	*ef_tcpconfig	/* OPTIONAL */;
	struct File	*ef_dgc	/* OPTIONAL */;
	struct File	*ef_wapbrowsercp	/* OPTIONAL */;
	struct File	*ef_wapbrowserbm	/* OPTIONAL */;
	struct File	*ef_mmsconfig	/* OPTIONAL */;
	struct File	*ef_jdl	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_OPT_CSIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_OPT_CSIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_CSIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_OPT_CSIM_1[69];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_OPT_CSIM_H_ */
#include <asn_internal.h>
