/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "PE-OPT-USIM.h"

asn_TYPE_member_t asn_MBR_PE_OPT_USIM_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PE_OPT_USIM, optusim_header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PEHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"optusim-header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PE_OPT_USIM, templateID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"templateID"
		},
	{ ATF_POINTER, 86, offsetof(struct PE_OPT_USIM, ef_li),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-li"
		},
	{ ATF_POINTER, 85, offsetof(struct PE_OPT_USIM, ef_acmax),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-acmax"
		},
	{ ATF_POINTER, 84, offsetof(struct PE_OPT_USIM, ef_acm),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-acm"
		},
	{ ATF_POINTER, 83, offsetof(struct PE_OPT_USIM, ef_gid1),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-gid1"
		},
	{ ATF_POINTER, 82, offsetof(struct PE_OPT_USIM, ef_gid2),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-gid2"
		},
	{ ATF_POINTER, 81, offsetof(struct PE_OPT_USIM, ef_msisdn),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-msisdn"
		},
	{ ATF_POINTER, 80, offsetof(struct PE_OPT_USIM, ef_puct),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-puct"
		},
	{ ATF_POINTER, 79, offsetof(struct PE_OPT_USIM, ef_cbmi),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cbmi"
		},
	{ ATF_POINTER, 78, offsetof(struct PE_OPT_USIM, ef_cbmid),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cbmid"
		},
	{ ATF_POINTER, 77, offsetof(struct PE_OPT_USIM, ef_sdn),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-sdn"
		},
	{ ATF_POINTER, 76, offsetof(struct PE_OPT_USIM, ef_ext2),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext2"
		},
	{ ATF_POINTER, 75, offsetof(struct PE_OPT_USIM, ef_ext3),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext3"
		},
	{ ATF_POINTER, 74, offsetof(struct PE_OPT_USIM, ef_cbmir),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cbmir"
		},
	{ ATF_POINTER, 73, offsetof(struct PE_OPT_USIM, ef_plmnwact),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-plmnwact"
		},
	{ ATF_POINTER, 72, offsetof(struct PE_OPT_USIM, ef_oplmnwact),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-oplmnwact"
		},
	{ ATF_POINTER, 71, offsetof(struct PE_OPT_USIM, ef_hplmnwact),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-hplmnwact"
		},
	{ ATF_POINTER, 70, offsetof(struct PE_OPT_USIM, ef_dck),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-dck"
		},
	{ ATF_POINTER, 69, offsetof(struct PE_OPT_USIM, ef_cnl),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cnl"
		},
	{ ATF_POINTER, 68, offsetof(struct PE_OPT_USIM, ef_smsr),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-smsr"
		},
	{ ATF_POINTER, 67, offsetof(struct PE_OPT_USIM, ef_bdn),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-bdn"
		},
	{ ATF_POINTER, 66, offsetof(struct PE_OPT_USIM, ef_ext5),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext5"
		},
	{ ATF_POINTER, 65, offsetof(struct PE_OPT_USIM, ef_ccp2),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ccp2"
		},
	{ ATF_POINTER, 64, offsetof(struct PE_OPT_USIM, ef_ext4),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext4"
		},
	{ ATF_POINTER, 63, offsetof(struct PE_OPT_USIM, ef_acl),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-acl"
		},
	{ ATF_POINTER, 62, offsetof(struct PE_OPT_USIM, ef_cmi),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cmi"
		},
	{ ATF_POINTER, 61, offsetof(struct PE_OPT_USIM, ef_ici),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ici"
		},
	{ ATF_POINTER, 60, offsetof(struct PE_OPT_USIM, ef_oci),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-oci"
		},
	{ ATF_POINTER, 59, offsetof(struct PE_OPT_USIM, ef_ict),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ict"
		},
	{ ATF_POINTER, 58, offsetof(struct PE_OPT_USIM, ef_oct),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-oct"
		},
	{ ATF_POINTER, 57, offsetof(struct PE_OPT_USIM, ef_vgcs),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vgcs"
		},
	{ ATF_POINTER, 56, offsetof(struct PE_OPT_USIM, ef_vgcss),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vgcss"
		},
	{ ATF_POINTER, 55, offsetof(struct PE_OPT_USIM, ef_vbs),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vbs"
		},
	{ ATF_POINTER, 54, offsetof(struct PE_OPT_USIM, ef_vbss),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vbss"
		},
	{ ATF_POINTER, 53, offsetof(struct PE_OPT_USIM, ef_emlpp),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-emlpp"
		},
	{ ATF_POINTER, 52, offsetof(struct PE_OPT_USIM, ef_aaem),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-aaem"
		},
	{ ATF_POINTER, 51, offsetof(struct PE_OPT_USIM, ef_hiddenkey),
		(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-hiddenkey"
		},
	{ ATF_POINTER, 50, offsetof(struct PE_OPT_USIM, ef_pnn),
		(ASN_TAG_CLASS_CONTEXT | (38 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-pnn"
		},
	{ ATF_POINTER, 49, offsetof(struct PE_OPT_USIM, ef_opl),
		(ASN_TAG_CLASS_CONTEXT | (39 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-opl"
		},
	{ ATF_POINTER, 48, offsetof(struct PE_OPT_USIM, ef_mbdn),
		(ASN_TAG_CLASS_CONTEXT | (40 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mbdn"
		},
	{ ATF_POINTER, 47, offsetof(struct PE_OPT_USIM, ef_ext6),
		(ASN_TAG_CLASS_CONTEXT | (41 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext6"
		},
	{ ATF_POINTER, 46, offsetof(struct PE_OPT_USIM, ef_mbi),
		(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mbi"
		},
	{ ATF_POINTER, 45, offsetof(struct PE_OPT_USIM, ef_mwis),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mwis"
		},
	{ ATF_POINTER, 44, offsetof(struct PE_OPT_USIM, ef_cfis),
		(ASN_TAG_CLASS_CONTEXT | (44 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-cfis"
		},
	{ ATF_POINTER, 43, offsetof(struct PE_OPT_USIM, ef_ext7),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext7"
		},
	{ ATF_POINTER, 42, offsetof(struct PE_OPT_USIM, ef_spdi),
		(ASN_TAG_CLASS_CONTEXT | (46 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-spdi"
		},
	{ ATF_POINTER, 41, offsetof(struct PE_OPT_USIM, ef_mmsn),
		(ASN_TAG_CLASS_CONTEXT | (47 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mmsn"
		},
	{ ATF_POINTER, 40, offsetof(struct PE_OPT_USIM, ef_ext8),
		(ASN_TAG_CLASS_CONTEXT | (48 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ext8"
		},
	{ ATF_POINTER, 39, offsetof(struct PE_OPT_USIM, ef_mmsicp),
		(ASN_TAG_CLASS_CONTEXT | (49 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mmsicp"
		},
	{ ATF_POINTER, 38, offsetof(struct PE_OPT_USIM, ef_mmsup),
		(ASN_TAG_CLASS_CONTEXT | (50 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mmsup"
		},
	{ ATF_POINTER, 37, offsetof(struct PE_OPT_USIM, ef_mmsucp),
		(ASN_TAG_CLASS_CONTEXT | (51 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mmsucp"
		},
	{ ATF_POINTER, 36, offsetof(struct PE_OPT_USIM, ef_nia),
		(ASN_TAG_CLASS_CONTEXT | (52 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-nia"
		},
	{ ATF_POINTER, 35, offsetof(struct PE_OPT_USIM, ef_vgcsca),
		(ASN_TAG_CLASS_CONTEXT | (53 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vgcsca"
		},
	{ ATF_POINTER, 34, offsetof(struct PE_OPT_USIM, ef_vbsca),
		(ASN_TAG_CLASS_CONTEXT | (54 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-vbsca"
		},
	{ ATF_POINTER, 33, offsetof(struct PE_OPT_USIM, ef_gbabp),
		(ASN_TAG_CLASS_CONTEXT | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-gbabp"
		},
	{ ATF_POINTER, 32, offsetof(struct PE_OPT_USIM, ef_msk),
		(ASN_TAG_CLASS_CONTEXT | (56 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-msk"
		},
	{ ATF_POINTER, 31, offsetof(struct PE_OPT_USIM, ef_muk),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-muk"
		},
	{ ATF_POINTER, 30, offsetof(struct PE_OPT_USIM, ef_ehplmn),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ehplmn"
		},
	{ ATF_POINTER, 29, offsetof(struct PE_OPT_USIM, ef_gbanl),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-gbanl"
		},
	{ ATF_POINTER, 28, offsetof(struct PE_OPT_USIM, ef_ehplmnpi),
		(ASN_TAG_CLASS_CONTEXT | (60 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ehplmnpi"
		},
	{ ATF_POINTER, 27, offsetof(struct PE_OPT_USIM, ef_lrplmnsi),
		(ASN_TAG_CLASS_CONTEXT | (61 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-lrplmnsi"
		},
	{ ATF_POINTER, 26, offsetof(struct PE_OPT_USIM, ef_nafkca),
		(ASN_TAG_CLASS_CONTEXT | (62 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-nafkca"
		},
	{ ATF_POINTER, 25, offsetof(struct PE_OPT_USIM, ef_spni),
		(ASN_TAG_CLASS_CONTEXT | (63 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-spni"
		},
	{ ATF_POINTER, 24, offsetof(struct PE_OPT_USIM, ef_pnni),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-pnni"
		},
	{ ATF_POINTER, 23, offsetof(struct PE_OPT_USIM, ef_ncp_ip),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ncp-ip"
		},
	{ ATF_POINTER, 22, offsetof(struct PE_OPT_USIM, ef_ufc),
		(ASN_TAG_CLASS_CONTEXT | (66 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ufc"
		},
	{ ATF_POINTER, 21, offsetof(struct PE_OPT_USIM, ef_nasconfig),
		(ASN_TAG_CLASS_CONTEXT | (67 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-nasconfig"
		},
	{ ATF_POINTER, 20, offsetof(struct PE_OPT_USIM, ef_uicciari),
		(ASN_TAG_CLASS_CONTEXT | (68 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-uicciari"
		},
	{ ATF_POINTER, 19, offsetof(struct PE_OPT_USIM, ef_pws),
		(ASN_TAG_CLASS_CONTEXT | (69 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-pws"
		},
	{ ATF_POINTER, 18, offsetof(struct PE_OPT_USIM, ef_fdnuri),
		(ASN_TAG_CLASS_CONTEXT | (70 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-fdnuri"
		},
	{ ATF_POINTER, 17, offsetof(struct PE_OPT_USIM, ef_bdnuri),
		(ASN_TAG_CLASS_CONTEXT | (71 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-bdnuri"
		},
	{ ATF_POINTER, 16, offsetof(struct PE_OPT_USIM, ef_sdnuri),
		(ASN_TAG_CLASS_CONTEXT | (72 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-sdnuri"
		},
	{ ATF_POINTER, 15, offsetof(struct PE_OPT_USIM, ef_ial),
		(ASN_TAG_CLASS_CONTEXT | (73 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ial"
		},
	{ ATF_POINTER, 14, offsetof(struct PE_OPT_USIM, ef_ips),
		(ASN_TAG_CLASS_CONTEXT | (74 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ips"
		},
	{ ATF_POINTER, 13, offsetof(struct PE_OPT_USIM, ef_ipd),
		(ASN_TAG_CLASS_CONTEXT | (75 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-ipd"
		},
	{ ATF_POINTER, 12, offsetof(struct PE_OPT_USIM, ef_epdgid),
		(ASN_TAG_CLASS_CONTEXT | (76 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epdgid"
		},
	{ ATF_POINTER, 11, offsetof(struct PE_OPT_USIM, ef_epdgselection),
		(ASN_TAG_CLASS_CONTEXT | (77 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epdgselection"
		},
	{ ATF_POINTER, 10, offsetof(struct PE_OPT_USIM, ef_epdgidem),
		(ASN_TAG_CLASS_CONTEXT | (78 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epdgidem"
		},
	{ ATF_POINTER, 9, offsetof(struct PE_OPT_USIM, ef_epdgselectionem),
		(ASN_TAG_CLASS_CONTEXT | (79 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-epdgselectionem"
		},
	{ ATF_POINTER, 8, offsetof(struct PE_OPT_USIM, ef_frompreferred),
		(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-frompreferred"
		},
	{ ATF_POINTER, 7, offsetof(struct PE_OPT_USIM, ef_imsconfigdata),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-imsconfigdata"
		},
	{ ATF_POINTER, 6, offsetof(struct PE_OPT_USIM, ef_3gpppsdataoff),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-3gpppsdataoff"
		},
	{ ATF_POINTER, 5, offsetof(struct PE_OPT_USIM, ef_3gpppsdataoffservicelist),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-3gpppsdataoffservicelist"
		},
	{ ATF_POINTER, 4, offsetof(struct PE_OPT_USIM, ef_xcapconfigdata),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-xcapconfigdata"
		},
	{ ATF_POINTER, 3, offsetof(struct PE_OPT_USIM, ef_earfcnlist),
		(ASN_TAG_CLASS_CONTEXT | (85 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-earfcnlist"
		},
	{ ATF_POINTER, 2, offsetof(struct PE_OPT_USIM, ef_mudmidconfigdata),
		(ASN_TAG_CLASS_CONTEXT | (86 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-mudmidconfigdata"
		},
	{ ATF_POINTER, 1, offsetof(struct PE_OPT_USIM, ef_eaka),
		(ASN_TAG_CLASS_CONTEXT | (87 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_File,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ef-eaka"
		},
};
static const ber_tlv_tag_t asn_DEF_PE_OPT_USIM_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PE_OPT_USIM_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* optusim-header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* templateID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ef-li */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ef-acmax */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ef-acm */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ef-gid1 */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ef-gid2 */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ef-msisdn */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* ef-puct */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* ef-cbmi */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* ef-cbmid */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* ef-sdn */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* ef-ext2 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* ef-ext3 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* ef-cbmir */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* ef-plmnwact */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* ef-oplmnwact */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* ef-hplmnwact */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* ef-dck */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* ef-cnl */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* ef-smsr */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* ef-bdn */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* ef-ext5 */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* ef-ccp2 */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* ef-ext4 */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* ef-acl */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* ef-cmi */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* ef-ici */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* ef-oci */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* ef-ict */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* ef-oct */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* ef-vgcs */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* ef-vgcss */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* ef-vbs */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* ef-vbss */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* ef-emlpp */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 }, /* ef-aaem */
    { (ASN_TAG_CLASS_CONTEXT | (37 << 2)), 37, 0, 0 }, /* ef-hiddenkey */
    { (ASN_TAG_CLASS_CONTEXT | (38 << 2)), 38, 0, 0 }, /* ef-pnn */
    { (ASN_TAG_CLASS_CONTEXT | (39 << 2)), 39, 0, 0 }, /* ef-opl */
    { (ASN_TAG_CLASS_CONTEXT | (40 << 2)), 40, 0, 0 }, /* ef-mbdn */
    { (ASN_TAG_CLASS_CONTEXT | (41 << 2)), 41, 0, 0 }, /* ef-ext6 */
    { (ASN_TAG_CLASS_CONTEXT | (42 << 2)), 42, 0, 0 }, /* ef-mbi */
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 43, 0, 0 }, /* ef-mwis */
    { (ASN_TAG_CLASS_CONTEXT | (44 << 2)), 44, 0, 0 }, /* ef-cfis */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 45, 0, 0 }, /* ef-ext7 */
    { (ASN_TAG_CLASS_CONTEXT | (46 << 2)), 46, 0, 0 }, /* ef-spdi */
    { (ASN_TAG_CLASS_CONTEXT | (47 << 2)), 47, 0, 0 }, /* ef-mmsn */
    { (ASN_TAG_CLASS_CONTEXT | (48 << 2)), 48, 0, 0 }, /* ef-ext8 */
    { (ASN_TAG_CLASS_CONTEXT | (49 << 2)), 49, 0, 0 }, /* ef-mmsicp */
    { (ASN_TAG_CLASS_CONTEXT | (50 << 2)), 50, 0, 0 }, /* ef-mmsup */
    { (ASN_TAG_CLASS_CONTEXT | (51 << 2)), 51, 0, 0 }, /* ef-mmsucp */
    { (ASN_TAG_CLASS_CONTEXT | (52 << 2)), 52, 0, 0 }, /* ef-nia */
    { (ASN_TAG_CLASS_CONTEXT | (53 << 2)), 53, 0, 0 }, /* ef-vgcsca */
    { (ASN_TAG_CLASS_CONTEXT | (54 << 2)), 54, 0, 0 }, /* ef-vbsca */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 55, 0, 0 }, /* ef-gbabp */
    { (ASN_TAG_CLASS_CONTEXT | (56 << 2)), 56, 0, 0 }, /* ef-msk */
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 57, 0, 0 }, /* ef-muk */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 58, 0, 0 }, /* ef-ehplmn */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 59, 0, 0 }, /* ef-gbanl */
    { (ASN_TAG_CLASS_CONTEXT | (60 << 2)), 60, 0, 0 }, /* ef-ehplmnpi */
    { (ASN_TAG_CLASS_CONTEXT | (61 << 2)), 61, 0, 0 }, /* ef-lrplmnsi */
    { (ASN_TAG_CLASS_CONTEXT | (62 << 2)), 62, 0, 0 }, /* ef-nafkca */
    { (ASN_TAG_CLASS_CONTEXT | (63 << 2)), 63, 0, 0 }, /* ef-spni */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 64, 0, 0 }, /* ef-pnni */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 65, 0, 0 }, /* ef-ncp-ip */
    { (ASN_TAG_CLASS_CONTEXT | (66 << 2)), 66, 0, 0 }, /* ef-ufc */
    { (ASN_TAG_CLASS_CONTEXT | (67 << 2)), 67, 0, 0 }, /* ef-nasconfig */
    { (ASN_TAG_CLASS_CONTEXT | (68 << 2)), 68, 0, 0 }, /* ef-uicciari */
    { (ASN_TAG_CLASS_CONTEXT | (69 << 2)), 69, 0, 0 }, /* ef-pws */
    { (ASN_TAG_CLASS_CONTEXT | (70 << 2)), 70, 0, 0 }, /* ef-fdnuri */
    { (ASN_TAG_CLASS_CONTEXT | (71 << 2)), 71, 0, 0 }, /* ef-bdnuri */
    { (ASN_TAG_CLASS_CONTEXT | (72 << 2)), 72, 0, 0 }, /* ef-sdnuri */
    { (ASN_TAG_CLASS_CONTEXT | (73 << 2)), 73, 0, 0 }, /* ef-ial */
    { (ASN_TAG_CLASS_CONTEXT | (74 << 2)), 74, 0, 0 }, /* ef-ips */
    { (ASN_TAG_CLASS_CONTEXT | (75 << 2)), 75, 0, 0 }, /* ef-ipd */
    { (ASN_TAG_CLASS_CONTEXT | (76 << 2)), 76, 0, 0 }, /* ef-epdgid */
    { (ASN_TAG_CLASS_CONTEXT | (77 << 2)), 77, 0, 0 }, /* ef-epdgselection */
    { (ASN_TAG_CLASS_CONTEXT | (78 << 2)), 78, 0, 0 }, /* ef-epdgidem */
    { (ASN_TAG_CLASS_CONTEXT | (79 << 2)), 79, 0, 0 }, /* ef-epdgselectionem */
    { (ASN_TAG_CLASS_CONTEXT | (80 << 2)), 80, 0, 0 }, /* ef-frompreferred */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 81, 0, 0 }, /* ef-imsconfigdata */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 82, 0, 0 }, /* ef-3gpppsdataoff */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 83, 0, 0 }, /* ef-3gpppsdataoffservicelist */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 84, 0, 0 }, /* ef-xcapconfigdata */
    { (ASN_TAG_CLASS_CONTEXT | (85 << 2)), 85, 0, 0 }, /* ef-earfcnlist */
    { (ASN_TAG_CLASS_CONTEXT | (86 << 2)), 86, 0, 0 }, /* ef-mudmidconfigdata */
    { (ASN_TAG_CLASS_CONTEXT | (87 << 2)), 87, 0, 0 } /* ef-eaka */
};
asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_USIM_specs_1 = {
	sizeof(struct PE_OPT_USIM),
	offsetof(struct PE_OPT_USIM, _asn_ctx),
	asn_MAP_PE_OPT_USIM_tag2el_1,
	88,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	88,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PE_OPT_USIM = {
	"PE-OPT-USIM",
	"PE-OPT-USIM",
	&asn_OP_SEQUENCE,
	asn_DEF_PE_OPT_USIM_tags_1,
	sizeof(asn_DEF_PE_OPT_USIM_tags_1)
		/sizeof(asn_DEF_PE_OPT_USIM_tags_1[0]), /* 1 */
	asn_DEF_PE_OPT_USIM_tags_1,	/* Same as above */
	sizeof(asn_DEF_PE_OPT_USIM_tags_1)
		/sizeof(asn_DEF_PE_OPT_USIM_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PE_OPT_USIM_1,
	88,	/* Elements count */
	&asn_SPC_PE_OPT_USIM_specs_1	/* Additional specs */
};

