/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_OPT_ISIM_H_
#define	_PE_OPT_ISIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-OPT-ISIM */
typedef struct PE_OPT_ISIM {
	PEHeader_t	 optisim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	struct File	*ef_pcscf	/* OPTIONAL */;
	struct File	*ef_sms	/* OPTIONAL */;
	struct File	*ef_smsp	/* OPTIONAL */;
	struct File	*ef_smss	/* OPTIONAL */;
	struct File	*ef_smsr	/* OPTIONAL */;
	struct File	*ef_gbabp	/* OPTIONAL */;
	struct File	*ef_gbanl	/* OPTIONAL */;
	struct File	*ef_nafkca	/* OPTIONAL */;
	struct File	*ef_uicciari	/* OPTIONAL */;
	struct File	*ef_frompreferred	/* OPTIONAL */;
	struct File	*ef_imsconfigdata	/* OPTIONAL */;
	struct File	*ef_xcapconfigdata	/* OPTIONAL */;
	struct File	*ef_webrtcuri	/* OPTIONAL */;
	struct File	*ef_mudmidconfigdata	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_OPT_ISIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_OPT_ISIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_ISIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_OPT_ISIM_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_OPT_ISIM_H_ */
#include <asn_internal.h>
