/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PE_OPT_USIM_H_
#define	_PE_OPT_USIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-OPT-USIM */
typedef struct PE_OPT_USIM {
	PEHeader_t	 optusim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	struct File	*ef_li	/* OPTIONAL */;
	struct File	*ef_acmax	/* OPTIONAL */;
	struct File	*ef_acm	/* OPTIONAL */;
	struct File	*ef_gid1	/* OPTIONAL */;
	struct File	*ef_gid2	/* OPTIONAL */;
	struct File	*ef_msisdn	/* OPTIONAL */;
	struct File	*ef_puct	/* OPTIONAL */;
	struct File	*ef_cbmi	/* OPTIONAL */;
	struct File	*ef_cbmid	/* OPTIONAL */;
	struct File	*ef_sdn	/* OPTIONAL */;
	struct File	*ef_ext2	/* OPTIONAL */;
	struct File	*ef_ext3	/* OPTIONAL */;
	struct File	*ef_cbmir	/* OPTIONAL */;
	struct File	*ef_plmnwact	/* OPTIONAL */;
	struct File	*ef_oplmnwact	/* OPTIONAL */;
	struct File	*ef_hplmnwact	/* OPTIONAL */;
	struct File	*ef_dck	/* OPTIONAL */;
	struct File	*ef_cnl	/* OPTIONAL */;
	struct File	*ef_smsr	/* OPTIONAL */;
	struct File	*ef_bdn	/* OPTIONAL */;
	struct File	*ef_ext5	/* OPTIONAL */;
	struct File	*ef_ccp2	/* OPTIONAL */;
	struct File	*ef_ext4	/* OPTIONAL */;
	struct File	*ef_acl	/* OPTIONAL */;
	struct File	*ef_cmi	/* OPTIONAL */;
	struct File	*ef_ici	/* OPTIONAL */;
	struct File	*ef_oci	/* OPTIONAL */;
	struct File	*ef_ict	/* OPTIONAL */;
	struct File	*ef_oct	/* OPTIONAL */;
	struct File	*ef_vgcs	/* OPTIONAL */;
	struct File	*ef_vgcss	/* OPTIONAL */;
	struct File	*ef_vbs	/* OPTIONAL */;
	struct File	*ef_vbss	/* OPTIONAL */;
	struct File	*ef_emlpp	/* OPTIONAL */;
	struct File	*ef_aaem	/* OPTIONAL */;
	struct File	*ef_hiddenkey	/* OPTIONAL */;
	struct File	*ef_pnn	/* OPTIONAL */;
	struct File	*ef_opl	/* OPTIONAL */;
	struct File	*ef_mbdn	/* OPTIONAL */;
	struct File	*ef_ext6	/* OPTIONAL */;
	struct File	*ef_mbi	/* OPTIONAL */;
	struct File	*ef_mwis	/* OPTIONAL */;
	struct File	*ef_cfis	/* OPTIONAL */;
	struct File	*ef_ext7	/* OPTIONAL */;
	struct File	*ef_spdi	/* OPTIONAL */;
	struct File	*ef_mmsn	/* OPTIONAL */;
	struct File	*ef_ext8	/* OPTIONAL */;
	struct File	*ef_mmsicp	/* OPTIONAL */;
	struct File	*ef_mmsup	/* OPTIONAL */;
	struct File	*ef_mmsucp	/* OPTIONAL */;
	struct File	*ef_nia	/* OPTIONAL */;
	struct File	*ef_vgcsca	/* OPTIONAL */;
	struct File	*ef_vbsca	/* OPTIONAL */;
	struct File	*ef_gbabp	/* OPTIONAL */;
	struct File	*ef_msk	/* OPTIONAL */;
	struct File	*ef_muk	/* OPTIONAL */;
	struct File	*ef_ehplmn	/* OPTIONAL */;
	struct File	*ef_gbanl	/* OPTIONAL */;
	struct File	*ef_ehplmnpi	/* OPTIONAL */;
	struct File	*ef_lrplmnsi	/* OPTIONAL */;
	struct File	*ef_nafkca	/* OPTIONAL */;
	struct File	*ef_spni	/* OPTIONAL */;
	struct File	*ef_pnni	/* OPTIONAL */;
	struct File	*ef_ncp_ip	/* OPTIONAL */;
	struct File	*ef_ufc	/* OPTIONAL */;
	struct File	*ef_nasconfig	/* OPTIONAL */;
	struct File	*ef_uicciari	/* OPTIONAL */;
	struct File	*ef_pws	/* OPTIONAL */;
	struct File	*ef_fdnuri	/* OPTIONAL */;
	struct File	*ef_bdnuri	/* OPTIONAL */;
	struct File	*ef_sdnuri	/* OPTIONAL */;
	struct File	*ef_ial	/* OPTIONAL */;
	struct File	*ef_ips	/* OPTIONAL */;
	struct File	*ef_ipd	/* OPTIONAL */;
	struct File	*ef_epdgid	/* OPTIONAL */;
	struct File	*ef_epdgselection	/* OPTIONAL */;
	struct File	*ef_epdgidem	/* OPTIONAL */;
	struct File	*ef_epdgselectionem	/* OPTIONAL */;
	struct File	*ef_frompreferred	/* OPTIONAL */;
	struct File	*ef_imsconfigdata	/* OPTIONAL */;
	struct File	*ef_3gpppsdataoff	/* OPTIONAL */;
	struct File	*ef_3gpppsdataoffservicelist	/* OPTIONAL */;
	struct File	*ef_xcapconfigdata	/* OPTIONAL */;
	struct File	*ef_earfcnlist	/* OPTIONAL */;
	struct File	*ef_mudmidconfigdata	/* OPTIONAL */;
	struct File	*ef_eaka	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_OPT_USIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_OPT_USIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_USIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_OPT_USIM_1[88];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_OPT_USIM_H_ */
#include <asn_internal.h>
