/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_OPT_IoT_H_
#define	_PE_OPT_IoT_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-OPT-IoT */
typedef struct PE_OPT_IoT {
	PEHeader_t	 optiot_header;
	OBJECT_IDENTIFIER_t	 templateID;
	struct File	*ef_fdn	/* OPTIONAL */;
	struct File	*ef_sms	/* OPTIONAL */;
	struct File	*ef_smsp	/* OPTIONAL */;
	struct File	*ef_smss	/* OPTIONAL */;
	struct File	*ef_spn	/* OPTIONAL */;
	struct File	*ef_est	/* OPTIONAL */;
	struct File	*ef_oplmnwact	/* OPTIONAL */;
	struct File	*ef_hplmnwact	/* OPTIONAL */;
	struct File	*ef_ehplmn	/* OPTIONAL */;
	struct File	*ef_epsloci	/* OPTIONAL */;
	struct File	*ef_epsnsc	/* OPTIONAL */;
	struct File	*df_df_5gs	/* OPTIONAL */;
	struct File	*ef_5gs3gpploci	/* OPTIONAL */;
	struct File	*ef_5gsn3gpploci	/* OPTIONAL */;
	struct File	*ef_5gs3gppnsc	/* OPTIONAL */;
	struct File	*ef_5gsn3gppnsc	/* OPTIONAL */;
	struct File	*ef_5gauthkeys	/* OPTIONAL */;
	struct File	*ef_uac_aic	/* OPTIONAL */;
	struct File	*ef_suci_calc_info	/* OPTIONAL */;
	struct File	*ef_opl5g	/* OPTIONAL */;
	struct File	*ef_supi_nai	/* OPTIONAL */;
	struct File	*ef_routing_indicator	/* OPTIONAL */;
	struct File	*ef_ursp	/* OPTIONAL */;
	struct File	*ef_tn3gppsnn	/* OPTIONAL */;
	struct File	*df_df_saip	/* OPTIONAL */;
	struct File	*ef_suci_calc_info_usim	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_OPT_IoT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_OPT_IoT;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_OPT_IoT_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_OPT_IoT_1[28];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_OPT_IoT_H_ */
#include <asn_internal.h>
