/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PE_SecurityDomain_H_
#define	_PE_SecurityDomain_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include "ApplicationInstance.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include "UInt16.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct KeyObject;

/* PE-SecurityDomain */
typedef struct PE_SecurityDomain {
	PEHeader_t	 sd_Header;
	ApplicationInstance_t	 instance;
	struct PE_SecurityDomain__keyList {
		A_SEQUENCE_OF(struct KeyObject) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *keyList;
	struct PE_SecurityDomain__sdPersoData {
		A_SEQUENCE_OF(OCTET_STRING_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdPersoData;
	struct PE_SecurityDomain__openPersoData {
		OCTET_STRING_t	*restrictParameter	/* OPTIONAL */;
		OCTET_STRING_t	*contactlessProtocolParameters	/* OPTIONAL */;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *openPersoData;
	struct PE_SecurityDomain__catTpParameters {
		UInt16_t	 catTpMaxSduSize;
		UInt16_t	 catTpMaxPduSize;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *catTpParameters;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_SecurityDomain_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_SecurityDomain;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_SecurityDomain_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_SecurityDomain_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "KeyObject.h"

#endif	/* _PE_SecurityDomain_H_ */
#include <asn_internal.h>
