/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PE_USIM_H_
#define	_PE_USIM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PEHeader.h"
#include <OBJECT_IDENTIFIER.h>
#include "File.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct File;

/* PE-USIM */
typedef struct PE_USIM {
	PEHeader_t	 usim_header;
	OBJECT_IDENTIFIER_t	 templateID;
	File_t	 adf_usim;
	File_t	 ef_imsi;
	File_t	 ef_arr;
	struct File	*ef_keys	/* OPTIONAL */;
	struct File	*ef_keysPS	/* OPTIONAL */;
	struct File	*ef_hpplmn	/* OPTIONAL */;
	File_t	 ef_ust;
	struct File	*ef_fdn	/* OPTIONAL */;
	struct File	*ef_sms	/* OPTIONAL */;
	struct File	*ef_smsp	/* OPTIONAL */;
	struct File	*ef_smss	/* OPTIONAL */;
	File_t	 ef_spn;
	File_t	 ef_est;
	struct File	*ef_start_hfn	/* OPTIONAL */;
	struct File	*ef_threshold	/* OPTIONAL */;
	struct File	*ef_psloci	/* OPTIONAL */;
	File_t	 ef_acc;
	struct File	*ef_fplmn	/* OPTIONAL */;
	struct File	*ef_loci	/* OPTIONAL */;
	struct File	*ef_ad	/* OPTIONAL */;
	File_t	 ef_ecc;
	struct File	*ef_netpar	/* OPTIONAL */;
	struct File	*ef_epsloci	/* OPTIONAL */;
	struct File	*ef_epsnsc	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PE_USIM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PE_USIM;
extern asn_SEQUENCE_specifics_t asn_SPC_PE_USIM_specs_1;
extern asn_TYPE_member_t asn_MBR_PE_USIM_1[26];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "File.h"

#endif	/* _PE_USIM_H_ */
#include <asn_internal.h>
