/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "PEHeader.h"

asn_TYPE_member_t asn_MBR_PEHeader_1[] = {
	{ ATF_POINTER, 1, offsetof(struct PEHeader, mandated),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mandated"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PEHeader, identification),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UInt15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"identification"
		},
};
static const ber_tlv_tag_t asn_DEF_PEHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PEHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mandated */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* identification */
};
asn_SEQUENCE_specifics_t asn_SPC_PEHeader_specs_1 = {
	sizeof(struct PEHeader),
	offsetof(struct PEHeader, _asn_ctx),
	asn_MAP_PEHeader_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PEHeader = {
	"PEHeader",
	"PEHeader",
	&asn_OP_SEQUENCE,
	asn_DEF_PEHeader_tags_1,
	sizeof(asn_DEF_PEHeader_tags_1)
		/sizeof(asn_DEF_PEHeader_tags_1[0]), /* 1 */
	asn_DEF_PEHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_PEHeader_tags_1)
		/sizeof(asn_DEF_PEHeader_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_PEHeader_1,
	2,	/* Elements count */
	&asn_SPC_PEHeader_specs_1	/* Additional specs */
};

