/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_PEHeader_H_
#define	_PEHeader_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include "UInt15.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PEHeader */
typedef struct PEHeader {
	NULL_t	*mandated	/* OPTIONAL */;
	UInt15_t	 identification;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PEHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PEHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_PEHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_PEHeader_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PEHeader_H_ */
#include <asn_internal.h>
