/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PprIds_H_
#define	_PprIds_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PprIds {
	PprIds_pprUpdateControl	= 0,
	PprIds_ppr1	= 1,
	PprIds_ppr2	= 2
} e_PprIds;

/* PprIds */
typedef BIT_STRING_t	 PprIds_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PprIds;
asn_struct_free_f PprIds_free;
asn_struct_print_f PprIds_print;
asn_constr_check_f PprIds_constraint;
ber_type_decoder_f PprIds_decode_ber;
der_type_encoder_f PprIds_encode_der;
xer_type_decoder_f PprIds_decode_xer;
xer_type_encoder_f PprIds_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PprIds_H_ */
#include <asn_internal.h>
