/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "PrepareDownloadRequest.h"

static asn_TYPE_member_t asn_MBR_PrepareDownloadRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareDownloadRequest, smdpSigned2),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_SmdpSigned2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSigned2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareDownloadRequest, smdpSignature2),
		(ASN_TAG_CLASS_APPLICATION | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpSignature2"
		},
	{ ATF_POINTER, 1, offsetof(struct PrepareDownloadRequest, hashCc),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_Octet32,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"hashCc"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PrepareDownloadRequest, smdpCertificate),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Certificate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpCertificate"
		},
};
static const ber_tlv_tag_t asn_DEF_PrepareDownloadRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PrepareDownloadRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 2, 0, 0 }, /* hashCc */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 1 }, /* smdpSigned2 */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 3, -1, 0 }, /* smdpCertificate */
    { (ASN_TAG_CLASS_APPLICATION | (55 << 2)), 1, 0, 0 } /* smdpSignature2 */
};
static asn_SEQUENCE_specifics_t asn_SPC_PrepareDownloadRequest_specs_1 = {
	sizeof(struct PrepareDownloadRequest),
	offsetof(struct PrepareDownloadRequest, _asn_ctx),
	asn_MAP_PrepareDownloadRequest_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PrepareDownloadRequest = {
	"PrepareDownloadRequest",
	"PrepareDownloadRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_PrepareDownloadRequest_tags_1,
	sizeof(asn_DEF_PrepareDownloadRequest_tags_1)
		/sizeof(asn_DEF_PrepareDownloadRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_PrepareDownloadRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_PrepareDownloadRequest_tags_1)
		/sizeof(asn_DEF_PrepareDownloadRequest_tags_1[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_PrepareDownloadRequest_1,
	4,	/* Elements count */
	&asn_SPC_PrepareDownloadRequest_specs_1	/* Additional specs */
};

