/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_ProfileDownloadTriggerResult_H_
#define	_ProfileDownloadTriggerResult_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TransactionId.h"
#include "SGP32-ProfileInstallationResult.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR {
	ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR_NOTHING,	/* No components present */
	ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR_profileInstallationResult,
	ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR_profileDownloadError
	/* Extensions may appear below */
	
} ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR;

/* ProfileDownloadTriggerResult */
typedef struct ProfileDownloadTriggerResult {
	TransactionId_t	*eimTransactionId	/* OPTIONAL */;
	struct ProfileDownloadTriggerResult__profileDownloadTriggerResultData {
		ProfileDownloadTriggerResult__profileDownloadTriggerResultData_PR present;
		union ProfileDownloadTriggerResult__profileDownloadTriggerResultData_u {
			SGP32_ProfileInstallationResult_t	 profileInstallationResult;
			struct ProfileDownloadTriggerResult__profileDownloadTriggerResultData__profileDownloadError {
				OCTET_STRING_t	*errorResponse	/* OPTIONAL */;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} profileDownloadError;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} profileDownloadTriggerResultData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProfileDownloadTriggerResult_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileDownloadTriggerResult;
extern asn_SEQUENCE_specifics_t asn_SPC_ProfileDownloadTriggerResult_specs_1;
extern asn_TYPE_member_t asn_MBR_ProfileDownloadTriggerResult_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileDownloadTriggerResult_H_ */
#include <asn_internal.h>
