/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_ProfileDownloadData_H_
#define	_ProfileDownloadData_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ProfileDownloadData_PR {
	ProfileDownloadData_PR_NOTHING,	/* No components present */
	ProfileDownloadData_PR_activationCode,
	ProfileDownloadData_PR_contactDefaultSmdp,
	ProfileDownloadData_PR_contactSmds
	/* Extensions may appear below */
	
} ProfileDownloadData_PR;

/* ProfileDownloadData */
typedef struct ProfileDownloadData {
	ProfileDownloadData_PR present;
	union ProfileDownloadData_u {
		UTF8String_t	 activationCode;
		NULL_t	 contactDefaultSmdp;
		struct ProfileDownloadData__contactSmds {
			UTF8String_t	*smdsAddress	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} contactSmds;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProfileDownloadData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProfileDownloadData;
extern asn_CHOICE_specifics_t asn_SPC_ProfileDownloadData_specs_1;
extern asn_TYPE_member_t asn_MBR_ProfileDownloadData_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ProfileDownloadData_H_ */
#include <asn_internal.h>
