/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ProfileInfo.h"

static asn_TYPE_member_t asn_MBR_notificationConfigurationInfo_11[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NotificationConfigurationInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_notificationConfigurationInfo_tags_11[] = {
	(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_notificationConfigurationInfo_specs_11 = {
	sizeof(struct ProfileInfo__notificationConfigurationInfo),
	offsetof(struct ProfileInfo__notificationConfigurationInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_notificationConfigurationInfo_11 = {
	"notificationConfigurationInfo",
	"notificationConfigurationInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_notificationConfigurationInfo_tags_11,
	sizeof(asn_DEF_notificationConfigurationInfo_tags_11)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_11[0]) - 1, /* 1 */
	asn_DEF_notificationConfigurationInfo_tags_11,	/* Same as above */
	sizeof(asn_DEF_notificationConfigurationInfo_tags_11)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_11[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_notificationConfigurationInfo_11,
	1,	/* Single element */
	&asn_SPC_notificationConfigurationInfo_specs_11	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProfileInfo_1[] = {
	{ ATF_POINTER, 14, offsetof(struct ProfileInfo, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_POINTER, 13, offsetof(struct ProfileInfo, isdpAid),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OctetTo16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"isdpAid"
		},
	{ ATF_POINTER, 12, offsetof(struct ProfileInfo, profileState),
		(ASN_TAG_CLASS_CONTEXT | (112 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileState,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileState"
		},
	{ ATF_POINTER, 11, offsetof(struct ProfileInfo, profileNickname),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileNickname"
		},
	{ ATF_POINTER, 10, offsetof(struct ProfileInfo, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_POINTER, 9, offsetof(struct ProfileInfo, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 8, offsetof(struct ProfileInfo, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 7, offsetof(struct ProfileInfo, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 6, offsetof(struct ProfileInfo, profileClass),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileClass,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileClass"
		},
	{ ATF_POINTER, 5, offsetof(struct ProfileInfo, notificationConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		0,
		&asn_DEF_notificationConfigurationInfo_11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationConfigurationInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct ProfileInfo, profileOwner),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OperatorId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwner"
		},
	{ ATF_POINTER, 3, offsetof(struct ProfileInfo, dpProprietaryData),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DpProprietaryData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dpProprietaryData"
		},
	{ ATF_POINTER, 2, offsetof(struct ProfileInfo, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
	{ ATF_POINTER, 1, offsetof(struct ProfileInfo, serviceSpecificDataStoredInEuicc),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceSpecificDataStoredInEuicc"
		},
};
static const ber_tlv_tag_t asn_DEF_ProfileInfo_tags_1[] = {
	(ASN_TAG_CLASS_PRIVATE | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProfileInfo_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 1, 0, 0 }, /* isdpAid */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 3, 0, 0 }, /* profileNickname */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 4, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 5, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 6, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 7, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 8, 0, 0 }, /* profileClass */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 9, 0, 0 }, /* notificationConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 10, 0, 0 }, /* profileOwner */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 11, 0, 0 }, /* dpProprietaryData */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 12, 0, 0 }, /* profilePolicyRules */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 13, 0, 0 }, /* serviceSpecificDataStoredInEuicc */
    { (ASN_TAG_CLASS_CONTEXT | (112 << 2)), 2, 0, 0 } /* profileState */
};
asn_SEQUENCE_specifics_t asn_SPC_ProfileInfo_specs_1 = {
	sizeof(struct ProfileInfo),
	offsetof(struct ProfileInfo, _asn_ctx),
	asn_MAP_ProfileInfo_tag2el_1,
	14,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	14,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProfileInfo = {
	"ProfileInfo",
	"ProfileInfo",
	&asn_OP_SEQUENCE,
	asn_DEF_ProfileInfo_tags_1,
	sizeof(asn_DEF_ProfileInfo_tags_1)
		/sizeof(asn_DEF_ProfileInfo_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProfileInfo_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProfileInfo_tags_1)
		/sizeof(asn_DEF_ProfileInfo_tags_1[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_ProfileInfo_1,
	14,	/* Elements count */
	&asn_SPC_ProfileInfo_specs_1	/* Additional specs */
};

