/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ProfileDownloadTriggerRequest.h"

asn_TYPE_member_t asn_MBR_ProfileDownloadTriggerRequest_1[] = {
	{ ATF_POINTER, 2, offsetof(struct ProfileDownloadTriggerRequest, profileDownloadData),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ProfileDownloadData,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileDownloadData"
		},
	{ ATF_POINTER, 1, offsetof(struct ProfileDownloadTriggerRequest, eimTransactionId),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransactionId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimTransactionId"
		},
};
static const ber_tlv_tag_t asn_DEF_ProfileDownloadTriggerRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProfileDownloadTriggerRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* profileDownloadData */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* eimTransactionId */
};
asn_SEQUENCE_specifics_t asn_SPC_ProfileDownloadTriggerRequest_specs_1 = {
	sizeof(struct ProfileDownloadTriggerRequest),
	offsetof(struct ProfileDownloadTriggerRequest, _asn_ctx),
	asn_MAP_ProfileDownloadTriggerRequest_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProfileDownloadTriggerRequest = {
	"ProfileDownloadTriggerRequest",
	"ProfileDownloadTriggerRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_ProfileDownloadTriggerRequest_tags_1,
	sizeof(asn_DEF_ProfileDownloadTriggerRequest_tags_1)
		/sizeof(asn_DEF_ProfileDownloadTriggerRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProfileDownloadTriggerRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProfileDownloadTriggerRequest_tags_1)
		/sizeof(asn_DEF_ProfileDownloadTriggerRequest_tags_1[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_ProfileDownloadTriggerRequest_1,
	2,	/* Elements count */
	&asn_SPC_ProfileDownloadTriggerRequest_specs_1	/* Additional specs */
};

