/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ProfileElement.h"

static asn_TYPE_member_t asn_MBR_ProfileElement_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileHeader,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.genericFileManagement),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_GenericFileManagement,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"genericFileManagement"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.pinCodes),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_PINCodes,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pinCodes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.pukCodes),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_PUKCodes,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pukCodes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.akaParameter),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_AKAParameter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"akaParameter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.cdmaParameter),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_CDMAParameter,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cdmaParameter"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.securityDomain),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_SecurityDomain,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"securityDomain"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfm),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_RFM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfm"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.application),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Application,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"application"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.nonStandard),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_NonStandard,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonStandard"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.end),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_End,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"end"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfu1),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Dummy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfu1"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfu2),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Dummy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfu2"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfu3),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Dummy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfu3"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfu4),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Dummy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfu4"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.rfu5),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_Dummy,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rfu5"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.mf),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_MF,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"mf"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.cd),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_CD,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cd"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.telecom),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_TELECOM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"telecom"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.usim),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_USIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"usim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.opt_usim),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_OPT_USIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"opt-usim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.isim),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_ISIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"isim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.opt_isim),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_OPT_ISIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"opt-isim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.phonebook),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_PHONEBOOK,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"phonebook"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.gsm_access),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_GSM_ACCESS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gsm-access"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.csim),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_CSIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"csim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.opt_csim),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_OPT_CSIM,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"opt-csim"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.eap),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_EAP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eap"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.df_5gs),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_DF_5GS,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-5gs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.df_saip),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_DF_SAIP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-saip"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.df_snpn),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_DF_SNPN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-snpn"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.df_5gprose),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_DF_5GPROSE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"df-5gprose"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.iot),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_IoT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iot"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProfileElement, choice.opt_iot),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PE_OPT_IoT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"opt-iot"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ProfileElement_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* header */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* genericFileManagement */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* pinCodes */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* pukCodes */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* akaParameter */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* cdmaParameter */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* securityDomain */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* rfm */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* application */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* nonStandard */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* end */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* rfu1 */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* rfu2 */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* rfu3 */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* rfu4 */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* rfu5 */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* mf */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* cd */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* telecom */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* usim */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* opt-usim */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* isim */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* opt-isim */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* phonebook */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* gsm-access */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* csim */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* opt-csim */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* eap */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* df-5gs */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* df-saip */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* df-snpn */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* df-5gprose */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* iot */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 } /* opt-iot */
};
static asn_CHOICE_specifics_t asn_SPC_ProfileElement_specs_1 = {
	sizeof(struct ProfileElement),
	offsetof(struct ProfileElement, _asn_ctx),
	offsetof(struct ProfileElement, present),
	sizeof(((struct ProfileElement *)0)->present),
	asn_MAP_ProfileElement_tag2el_1,
	34,	/* Count of tags in the map */
	0, 0,
	34	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ProfileElement = {
	"ProfileElement",
	"ProfileElement",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_ProfileElement_1,
	34,	/* Elements count */
	&asn_SPC_ProfileElement_specs_1	/* Additional specs */
};

