/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "ProvideEimPackageResult.h"

asn_TYPE_member_t asn_MBR_ProvideEimPackageResult_1[] = {
	{ ATF_POINTER, 1, offsetof(struct ProvideEimPackageResult, eidValue),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Octet16,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eidValue"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, eimPackageResult),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_EimPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimPackageResult"
		},
};
static const int asn_MAP_ProvideEimPackageResult_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_ProvideEimPackageResult_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (80 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProvideEimPackageResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* ePRAndNotifications */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* eidValue */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* eimPackageResultResponseError */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 1, 0, 0 }, /* euiccPackageResult */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 1, 0, 0 }, /* ipaEuiccDataResponse */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 1, 0, 0 } /* profileDownloadTriggerResult */
};
asn_SEQUENCE_specifics_t asn_SPC_ProvideEimPackageResult_specs_1 = {
	sizeof(struct ProvideEimPackageResult),
	offsetof(struct ProvideEimPackageResult, _asn_ctx),
	asn_MAP_ProvideEimPackageResult_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_ProvideEimPackageResult_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ProvideEimPackageResult = {
	"ProvideEimPackageResult",
	"ProvideEimPackageResult",
	&asn_OP_SEQUENCE,
	asn_DEF_ProvideEimPackageResult_tags_1,
	sizeof(asn_DEF_ProvideEimPackageResult_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResult_tags_1[0]) - 1, /* 1 */
	asn_DEF_ProvideEimPackageResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProvideEimPackageResult_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResult_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ProvideEimPackageResult_1,
	2,	/* Elements count */
	&asn_SPC_ProvideEimPackageResult_specs_1	/* Additional specs */
};

