/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "ProvideEimPackageResultResponse.h"

static asn_oer_constraints_t asn_OER_type_ProvideEimPackageResultResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ProvideEimPackageResultResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const ber_tlv_tag_t asn_DEF_emptyResponse_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_emptyResponse_specs_3 = {
	sizeof(struct ProvideEimPackageResultResponse__emptyResponse),
	offsetof(struct ProvideEimPackageResultResponse__emptyResponse, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_emptyResponse_3 = {
	"emptyResponse",
	"emptyResponse",
	&asn_OP_SEQUENCE,
	asn_DEF_emptyResponse_tags_3,
	sizeof(asn_DEF_emptyResponse_tags_3)
		/sizeof(asn_DEF_emptyResponse_tags_3[0]), /* 1 */
	asn_DEF_emptyResponse_tags_3,	/* Same as above */
	sizeof(asn_DEF_emptyResponse_tags_3)
		/sizeof(asn_DEF_emptyResponse_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_emptyResponse_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProvideEimPackageResultResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResultResponse, choice.eimAcknowledgements),
		(ASN_TAG_CLASS_CONTEXT | (83 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EimAcknowledgements,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimAcknowledgements"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResultResponse, choice.emptyResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_emptyResponse_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"emptyResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResultResponse, choice.provideEimPackageResultError),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"provideEimPackageResultError"
		},
};
static const unsigned asn_MAP_ProvideEimPackageResultResponse_to_canonical_1[] = { 2, 1, 0 };
static const unsigned asn_MAP_ProvideEimPackageResultResponse_from_canonical_1[] = { 2, 1, 0 };
static const ber_tlv_tag_t asn_DEF_ProvideEimPackageResultResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (80 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProvideEimPackageResultResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 2, 0, 0 }, /* provideEimPackageResultError */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* emptyResponse */
    { (ASN_TAG_CLASS_CONTEXT | (83 << 2)), 0, 0, 0 } /* eimAcknowledgements */
};
asn_CHOICE_specifics_t asn_SPC_ProvideEimPackageResultResponse_specs_1 = {
	sizeof(struct ProvideEimPackageResultResponse),
	offsetof(struct ProvideEimPackageResultResponse, _asn_ctx),
	offsetof(struct ProvideEimPackageResultResponse, present),
	sizeof(((struct ProvideEimPackageResultResponse *)0)->present),
	asn_MAP_ProvideEimPackageResultResponse_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_ProvideEimPackageResultResponse_to_canonical_1,
	asn_MAP_ProvideEimPackageResultResponse_from_canonical_1,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ProvideEimPackageResultResponse = {
	"ProvideEimPackageResultResponse",
	"ProvideEimPackageResultResponse",
	&asn_OP_CHOICE,
	asn_DEF_ProvideEimPackageResultResponse_tags_1,
	sizeof(asn_DEF_ProvideEimPackageResultResponse_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResultResponse_tags_1[0]), /* 1 */
	asn_DEF_ProvideEimPackageResultResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProvideEimPackageResultResponse_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResultResponse_tags_1[0]), /* 1 */
	{ &asn_OER_type_ProvideEimPackageResultResponse_constr_1, &asn_PER_type_ProvideEimPackageResultResponse_constr_1, CHOICE_constraint },
	asn_MBR_ProvideEimPackageResultResponse_1,
	3,	/* Elements count */
	&asn_SPC_ProvideEimPackageResultResponse_specs_1	/* Additional specs */
};

