/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "ProvideEimPackageResult.h"

static asn_TYPE_member_t asn_MBR_ePRAndNotifications_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult__ePRAndNotifications, euiccPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult__ePRAndNotifications, notificationList),
		(ASN_TAG_CLASS_CONTEXT | (43 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SGP32_RetrieveNotificationsListResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationList"
		},
};
static const ber_tlv_tag_t asn_DEF_ePRAndNotifications_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ePRAndNotifications_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (43 << 2)), 1, 0, 0 }, /* notificationList */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 } /* euiccPackageResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_ePRAndNotifications_specs_3 = {
	sizeof(struct ProvideEimPackageResult__ePRAndNotifications),
	offsetof(struct ProvideEimPackageResult__ePRAndNotifications, _asn_ctx),
	asn_MAP_ePRAndNotifications_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ePRAndNotifications_3 = {
	"ePRAndNotifications",
	"ePRAndNotifications",
	&asn_OP_SEQUENCE,
	asn_DEF_ePRAndNotifications_tags_3,
	sizeof(asn_DEF_ePRAndNotifications_tags_3)
		/sizeof(asn_DEF_ePRAndNotifications_tags_3[0]), /* 1 */
	asn_DEF_ePRAndNotifications_tags_3,	/* Same as above */
	sizeof(asn_DEF_ePRAndNotifications_tags_3)
		/sizeof(asn_DEF_ePRAndNotifications_tags_3[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_ePRAndNotifications_3,
	2,	/* Elements count */
	&asn_SPC_ePRAndNotifications_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ProvideEimPackageResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, choice.euiccPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, choice.ePRAndNotifications),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ePRAndNotifications_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ePRAndNotifications"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, choice.ipaEuiccDataResponse),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpaEuiccDataResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipaEuiccDataResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, choice.profileDownloadTriggerResult),
		(ASN_TAG_CLASS_CONTEXT | (84 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileDownloadTriggerResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileDownloadTriggerResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ProvideEimPackageResult, choice.eimPackageError),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimPackageError"
		},
};
static const ber_tlv_tag_t asn_DEF_ProvideEimPackageResult_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (80 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ProvideEimPackageResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, 0, 0 }, /* eimPackageError */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* ePRAndNotifications */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 }, /* euiccPackageResult */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 2, 0, 0 }, /* ipaEuiccDataResponse */
    { (ASN_TAG_CLASS_CONTEXT | (84 << 2)), 3, 0, 0 } /* profileDownloadTriggerResult */
};
asn_CHOICE_specifics_t asn_SPC_ProvideEimPackageResult_specs_1 = {
	sizeof(struct ProvideEimPackageResult),
	offsetof(struct ProvideEimPackageResult, _asn_ctx),
	offsetof(struct ProvideEimPackageResult, present),
	sizeof(((struct ProvideEimPackageResult *)0)->present),
	asn_MAP_ProvideEimPackageResult_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ProvideEimPackageResult = {
	"ProvideEimPackageResult",
	"ProvideEimPackageResult",
	&asn_OP_CHOICE,
	asn_DEF_ProvideEimPackageResult_tags_1,
	sizeof(asn_DEF_ProvideEimPackageResult_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResult_tags_1[0]), /* 1 */
	asn_DEF_ProvideEimPackageResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProvideEimPackageResult_tags_1)
		/sizeof(asn_DEF_ProvideEimPackageResult_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_ProvideEimPackageResult_1,
	5,	/* Elements count */
	&asn_SPC_ProvideEimPackageResult_specs_1	/* Additional specs */
};

