/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_Psmo_H_
#define	_Psmo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProfileInfoListRequest.h"
#include "SGP32-SetDefaultDpAddressRequest.h"
#include "Iccid.h"
#include <NULL.h>
#include <constr_SEQUENCE.h>
#include <OBJECT_IDENTIFIER.h>
#include <UTF8String.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Psmo_PR {
	Psmo_PR_NOTHING,	/* No components present */
	Psmo_PR_enable,
	Psmo_PR_disable,
	Psmo_PR_delete,
	Psmo_PR_listProfileInfo,
	Psmo_PR_getRAT,
	Psmo_PR_configureImmediateEnable,
	Psmo_PR_setFallbackAttribute,
	Psmo_PR_unsetFallbackAttribute,
	Psmo_PR_setDefaultDpAddress
	/* Extensions may appear below */
	
} Psmo_PR;

/* Psmo */
typedef struct Psmo {
	Psmo_PR present;
	union Psmo_u {
		struct Psmo__enable {
			Iccid_t	 iccid;
			NULL_t	*rollbackFlag	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} enable;
		struct Psmo__disable {
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} disable;
		struct Psmo__delete {
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} Delete;
		ProfileInfoListRequest_t	 listProfileInfo;
		struct Psmo__getRAT {
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} getRAT;
		struct Psmo__configureImmediateEnable {
			NULL_t	*immediateEnableFlag	/* OPTIONAL */;
			OBJECT_IDENTIFIER_t	*defaultSmdpOid	/* OPTIONAL */;
			UTF8String_t	*defaultSmdpAddress	/* OPTIONAL */;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} configureImmediateEnable;
		struct Psmo__setFallbackAttribute {
			Iccid_t	 iccid;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} setFallbackAttribute;
		struct Psmo__unsetFallbackAttribute {
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} unsetFallbackAttribute;
		SGP32_SetDefaultDpAddressRequest_t	 setDefaultDpAddress;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Psmo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Psmo;
extern asn_CHOICE_specifics_t asn_SPC_Psmo_specs_1;
extern asn_TYPE_member_t asn_MBR_Psmo_1[9];
extern asn_per_constraints_t asn_PER_type_Psmo_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Psmo_H_ */
#include <asn_internal.h>
