/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "Psmo.h"

static asn_TYPE_member_t asn_MBR_enable_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo__enable, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_POINTER, 1, offsetof(struct Psmo__enable, rollbackFlag),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rollbackFlag"
		},
};
static const ber_tlv_tag_t asn_DEF_enable_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_enable_tag2el_2[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 1, 0, 0 }, /* rollbackFlag */
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_enable_specs_2 = {
	sizeof(struct Psmo__enable),
	offsetof(struct Psmo__enable, _asn_ctx),
	asn_MAP_enable_tag2el_2,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_enable_2 = {
	"enable",
	"enable",
	&asn_OP_SEQUENCE,
	asn_DEF_enable_tags_2,
	sizeof(asn_DEF_enable_tags_2)
		/sizeof(asn_DEF_enable_tags_2[0]) - 1, /* 1 */
	asn_DEF_enable_tags_2,	/* Same as above */
	sizeof(asn_DEF_enable_tags_2)
		/sizeof(asn_DEF_enable_tags_2[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_enable_2,
	2,	/* Elements count */
	&asn_SPC_enable_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_disable_6[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo__disable, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_disable_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_disable_tag2el_6[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_disable_specs_6 = {
	sizeof(struct Psmo__disable),
	offsetof(struct Psmo__disable, _asn_ctx),
	asn_MAP_disable_tag2el_6,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_disable_6 = {
	"disable",
	"disable",
	&asn_OP_SEQUENCE,
	asn_DEF_disable_tags_6,
	sizeof(asn_DEF_disable_tags_6)
		/sizeof(asn_DEF_disable_tags_6[0]) - 1, /* 1 */
	asn_DEF_disable_tags_6,	/* Same as above */
	sizeof(asn_DEF_disable_tags_6)
		/sizeof(asn_DEF_disable_tags_6[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_disable_6,
	1,	/* Elements count */
	&asn_SPC_disable_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_delete_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo__delete, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
};
static const ber_tlv_tag_t asn_DEF_delete_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_delete_tag2el_9[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 } /* iccid */
};
static asn_SEQUENCE_specifics_t asn_SPC_delete_specs_9 = {
	sizeof(struct Psmo__delete),
	offsetof(struct Psmo__delete, _asn_ctx),
	asn_MAP_delete_tag2el_9,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_delete_9 = {
	"delete",
	"delete",
	&asn_OP_SEQUENCE,
	asn_DEF_delete_tags_9,
	sizeof(asn_DEF_delete_tags_9)
		/sizeof(asn_DEF_delete_tags_9[0]) - 1, /* 1 */
	asn_DEF_delete_tags_9,	/* Same as above */
	sizeof(asn_DEF_delete_tags_9)
		/sizeof(asn_DEF_delete_tags_9[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_delete_9,
	1,	/* Elements count */
	&asn_SPC_delete_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_getRAT_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SEQUENCE_specifics_t asn_SPC_getRAT_specs_13 = {
	sizeof(struct Psmo__getRAT),
	offsetof(struct Psmo__getRAT, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_getRAT_13 = {
	"getRAT",
	"getRAT",
	&asn_OP_SEQUENCE,
	asn_DEF_getRAT_tags_13,
	sizeof(asn_DEF_getRAT_tags_13)
		/sizeof(asn_DEF_getRAT_tags_13[0]) - 1, /* 1 */
	asn_DEF_getRAT_tags_13,	/* Same as above */
	sizeof(asn_DEF_getRAT_tags_13)
		/sizeof(asn_DEF_getRAT_tags_13[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	0, 0,	/* No members */
	&asn_SPC_getRAT_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_configureAutoEnable_15[] = {
	{ ATF_POINTER, 3, offsetof(struct Psmo__configureAutoEnable, autoEnableFlag),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"autoEnableFlag"
		},
	{ ATF_POINTER, 2, offsetof(struct Psmo__configureAutoEnable, smdpOid),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OBJECT_IDENTIFIER,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpOid"
		},
	{ ATF_POINTER, 1, offsetof(struct Psmo__configureAutoEnable, smdpAddress),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"smdpAddress"
		},
};
static const ber_tlv_tag_t asn_DEF_configureAutoEnable_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_configureAutoEnable_tag2el_15[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* autoEnableFlag */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* smdpOid */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* smdpAddress */
};
static asn_SEQUENCE_specifics_t asn_SPC_configureAutoEnable_specs_15 = {
	sizeof(struct Psmo__configureAutoEnable),
	offsetof(struct Psmo__configureAutoEnable, _asn_ctx),
	asn_MAP_configureAutoEnable_tag2el_15,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_configureAutoEnable_15 = {
	"configureAutoEnable",
	"configureAutoEnable",
	&asn_OP_SEQUENCE,
	asn_DEF_configureAutoEnable_tags_15,
	sizeof(asn_DEF_configureAutoEnable_tags_15)
		/sizeof(asn_DEF_configureAutoEnable_tags_15[0]) - 1, /* 1 */
	asn_DEF_configureAutoEnable_tags_15,	/* Same as above */
	sizeof(asn_DEF_configureAutoEnable_tags_15)
		/sizeof(asn_DEF_configureAutoEnable_tags_15[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_configureAutoEnable_15,
	3,	/* Elements count */
	&asn_SPC_configureAutoEnable_specs_15	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Psmo_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.enable),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_enable_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"enable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.disable),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_disable_6,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"disable"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.Delete),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_delete_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"delete"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.listProfileInfo),
		(ASN_TAG_CLASS_CONTEXT | (45 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileInfoListRequest,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listProfileInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.getRAT),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		0,
		&asn_DEF_getRAT_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getRAT"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Psmo, choice.configureAutoEnable),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		0,
		&asn_DEF_configureAutoEnable_15,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"configureAutoEnable"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_Psmo_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 }, /* enable */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 1, 0, 0 }, /* disable */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 2, 0, 0 }, /* delete */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 4, 0, 0 }, /* getRAT */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 5, 0, 0 }, /* configureAutoEnable */
    { (ASN_TAG_CLASS_CONTEXT | (45 << 2)), 3, 0, 0 } /* listProfileInfo */
};
asn_CHOICE_specifics_t asn_SPC_Psmo_specs_1 = {
	sizeof(struct Psmo),
	offsetof(struct Psmo, _asn_ctx),
	offsetof(struct Psmo, present),
	sizeof(((struct Psmo *)0)->present),
	asn_MAP_Psmo_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_Psmo = {
	"Psmo",
	"Psmo",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, CHOICE_constraint },
	asn_MBR_Psmo_1,
	6,	/* Elements count */
	&asn_SPC_Psmo_specs_1	/* Additional specs */
};

