/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_PUKKeyReferenceValue_H_
#define	_PUKKeyReferenceValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PUKKeyReferenceValue {
	PUKKeyReferenceValue_pukAppl1	= 1,
	PUKKeyReferenceValue_pukAppl2	= 2,
	PUKKeyReferenceValue_pukAppl3	= 3,
	PUKKeyReferenceValue_pukAppl4	= 4,
	PUKKeyReferenceValue_pukAppl5	= 5,
	PUKKeyReferenceValue_pukAppl6	= 6,
	PUKKeyReferenceValue_pukAppl7	= 7,
	PUKKeyReferenceValue_pukAppl8	= 8,
	PUKKeyReferenceValue_secondPUKAppl1	= 129,
	PUKKeyReferenceValue_secondPUKAppl2	= 130,
	PUKKeyReferenceValue_secondPUKAppl3	= 131,
	PUKKeyReferenceValue_secondPUKAppl4	= 132,
	PUKKeyReferenceValue_secondPUKAppl5	= 133,
	PUKKeyReferenceValue_secondPUKAppl6	= 134,
	PUKKeyReferenceValue_secondPUKAppl7	= 135,
	PUKKeyReferenceValue_secondPUKAppl8	= 136
} e_PUKKeyReferenceValue;

/* PUKKeyReferenceValue */
typedef long	 PUKKeyReferenceValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PUKKeyReferenceValue;
asn_struct_free_f PUKKeyReferenceValue_free;
asn_struct_print_f PUKKeyReferenceValue_print;
asn_constr_check_f PUKKeyReferenceValue_constraint;
ber_type_decoder_f PUKKeyReferenceValue_decode_ber;
der_type_encoder_f PUKKeyReferenceValue_encode_der;
xer_type_decoder_f PUKKeyReferenceValue_decode_xer;
xer_type_encoder_f PUKKeyReferenceValue_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _PUKKeyReferenceValue_H_ */
#include <asn_internal.h>
