/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_RemoteOpId_H_
#define	_RemoteOpId_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RemoteOpId {
	RemoteOpId_installBoundProfilePackage	= 1
} e_RemoteOpId;

/* RemoteOpId */
typedef long	 RemoteOpId_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RemoteOpId;
asn_struct_free_f RemoteOpId_free;
asn_struct_print_f RemoteOpId_print;
asn_constr_check_f RemoteOpId_constraint;
ber_type_decoder_f RemoteOpId_decode_ber;
der_type_encoder_f RemoteOpId_encode_der;
xer_type_decoder_f RemoteOpId_decode_xer;
xer_type_encoder_f RemoteOpId_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RemoteOpId_H_ */
#include <asn_internal.h>
