/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "RemoteProfileProvisioningResponse.h"

static asn_TYPE_member_t asn_MBR_RemoteProfileProvisioningResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningResponse, choice.initiateAuthenticationResponse),
		(ASN_TAG_CLASS_CONTEXT | (57 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_InitiateAuthenticationResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initiateAuthenticationResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningResponse, choice.authenticateClientResponseEs9),
		(ASN_TAG_CLASS_CONTEXT | (59 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthenticateClientResponseEs9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authenticateClientResponseEs9"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningResponse, choice.getBoundProfilePackageResponse),
		(ASN_TAG_CLASS_CONTEXT | (58 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GetBoundProfilePackageResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"getBoundProfilePackageResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningResponse, choice.cancelSessionResponseEs9),
		(ASN_TAG_CLASS_CONTEXT | (65 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CancelSessionResponseEs9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cancelSessionResponseEs9"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RemoteProfileProvisioningResponse, choice.authenticateClientResponseEs11),
		(ASN_TAG_CLASS_CONTEXT | (64 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AuthenticateClientResponseEs11,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"authenticateClientResponseEs11"
		},
};
static const ber_tlv_tag_t asn_DEF_RemoteProfileProvisioningResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RemoteProfileProvisioningResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (57 << 2)), 0, 0, 0 }, /* initiateAuthenticationResponse */
    { (ASN_TAG_CLASS_CONTEXT | (58 << 2)), 2, 0, 0 }, /* getBoundProfilePackageResponse */
    { (ASN_TAG_CLASS_CONTEXT | (59 << 2)), 1, 0, 0 }, /* authenticateClientResponseEs9 */
    { (ASN_TAG_CLASS_CONTEXT | (64 << 2)), 4, 0, 0 }, /* authenticateClientResponseEs11 */
    { (ASN_TAG_CLASS_CONTEXT | (65 << 2)), 3, 0, 0 } /* cancelSessionResponseEs9 */
};
static asn_CHOICE_specifics_t asn_SPC_RemoteProfileProvisioningResponse_specs_1 = {
	sizeof(struct RemoteProfileProvisioningResponse),
	offsetof(struct RemoteProfileProvisioningResponse, _asn_ctx),
	offsetof(struct RemoteProfileProvisioningResponse, present),
	sizeof(((struct RemoteProfileProvisioningResponse *)0)->present),
	asn_MAP_RemoteProfileProvisioningResponse_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_RemoteProfileProvisioningResponse = {
	"RemoteProfileProvisioningResponse",
	"RemoteProfileProvisioningResponse",
	&asn_OP_CHOICE,
	asn_DEF_RemoteProfileProvisioningResponse_tags_1,
	sizeof(asn_DEF_RemoteProfileProvisioningResponse_tags_1)
		/sizeof(asn_DEF_RemoteProfileProvisioningResponse_tags_1[0]), /* 1 */
	asn_DEF_RemoteProfileProvisioningResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_RemoteProfileProvisioningResponse_tags_1)
		/sizeof(asn_DEF_RemoteProfileProvisioningResponse_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_RemoteProfileProvisioningResponse_1,
	5,	/* Elements count */
	&asn_SPC_RemoteProfileProvisioningResponse_specs_1	/* Additional specs */
};

