/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_ReturnFromFallbackResponse_H_
#define	_ReturnFromFallbackResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ReturnFromFallbackResponse__returnFromFallbackResult {
	ReturnFromFallbackResponse__returnFromFallbackResult_ok	= 0,
	ReturnFromFallbackResponse__returnFromFallbackResult_catBusy	= 5,
	ReturnFromFallbackResponse__returnFromFallbackResult_fallbackNotAvailable	= 6,
	ReturnFromFallbackResponse__returnFromFallbackResult_commandError	= 7,
	ReturnFromFallbackResponse__returnFromFallbackResult_undefinedError	= 127
} e_ReturnFromFallbackResponse__returnFromFallbackResult;

/* ReturnFromFallbackResponse */
typedef struct ReturnFromFallbackResponse {
	long	 returnFromFallbackResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReturnFromFallbackResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReturnFromFallbackResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _ReturnFromFallbackResponse_H_ */
#include <asn_internal.h>
