/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_RspCapability_H_
#define	_RspCapability_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RspCapability {
	RspCapability_additionalProfile	= 0,
	RspCapability_crlSupport	= 1,
	RspCapability_rpmSupport	= 2,
	RspCapability_testProfileSupport	= 3,
	RspCapability_deviceInfoExtensibilitySupport	= 4,
	RspCapability_serviceSpecificDataSupport	= 5
} e_RspCapability;

/* RspCapability */
typedef BIT_STRING_t	 RspCapability_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RspCapability;
asn_struct_free_f RspCapability_free;
asn_struct_print_f RspCapability_print;
asn_constr_check_f RspCapability_constraint;
ber_type_decoder_f RspCapability_decode_ber;
der_type_encoder_f RspCapability_encode_der;
xer_type_decoder_f RspCapability_decode_xer;
xer_type_encoder_f RspCapability_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _RspCapability_H_ */
#include <asn_internal.h>
