/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#ifndef	_SetDefaultDpAddressResponse_H_
#define	_SetDefaultDpAddressResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SetDefaultDpAddressResponse__setDefaultDpAddressResult {
	SetDefaultDpAddressResponse__setDefaultDpAddressResult_ok	= 0,
	SetDefaultDpAddressResponse__setDefaultDpAddressResult_undefinedError	= 127
} e_SetDefaultDpAddressResponse__setDefaultDpAddressResult;

/* SetDefaultDpAddressResponse */
typedef struct SetDefaultDpAddressResponse {
	long	 setDefaultDpAddressResult;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SetDefaultDpAddressResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SetDefaultDpAddressResponse;

#ifdef __cplusplus
}
#endif

#endif	/* _SetDefaultDpAddressResponse_H_ */
#include <asn_internal.h>
