/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_SGP32_ProfileInfoListError_H_
#define	_SGP32_ProfileInfoListError_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SGP32_ProfileInfoListError {
	SGP32_ProfileInfoListError_incorrectInputValues	= 1,
	SGP32_ProfileInfoListError_profileChangeOngoing	= 11,
	SGP32_ProfileInfoListError_undefinedError	= 127
} e_SGP32_ProfileInfoListError;

/* SGP32-ProfileInfoListError */
typedef long	 SGP32_ProfileInfoListError_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGP32_ProfileInfoListError;
asn_struct_free_f SGP32_ProfileInfoListError_free;
asn_struct_print_f SGP32_ProfileInfoListError_print;
asn_constr_check_f SGP32_ProfileInfoListError_constraint;
ber_type_decoder_f SGP32_ProfileInfoListError_decode_ber;
der_type_encoder_f SGP32_ProfileInfoListError_encode_der;
xer_type_decoder_f SGP32_ProfileInfoListError_decode_xer;
xer_type_encoder_f SGP32_ProfileInfoListError_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _SGP32_ProfileInfoListError_H_ */
#include <asn_internal.h>
