/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "SGP32-PendingNotification.h"

asn_TYPE_member_t asn_MBR_SGP32_PendingNotification_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_PendingNotification, choice.profileInstallationResult),
		(ASN_TAG_CLASS_CONTEXT | (55 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SGP32_ProfileInstallationResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileInstallationResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_PendingNotification, choice.otherSignedNotification),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_OtherSignedNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"otherSignedNotification"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_PendingNotification, choice.compactProfileInstallationResult),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompactProfileInstallationResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compactProfileInstallationResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_PendingNotification, choice.compactOtherSignedNotification),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CompactOtherSignedNotification,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"compactOtherSignedNotification"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_SGP32_PendingNotification_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* otherSignedNotification */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 2, 0, 0 }, /* compactProfileInstallationResult */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 3, 0, 0 }, /* compactOtherSignedNotification */
    { (ASN_TAG_CLASS_CONTEXT | (55 << 2)), 0, 0, 0 } /* profileInstallationResult */
};
asn_CHOICE_specifics_t asn_SPC_SGP32_PendingNotification_specs_1 = {
	sizeof(struct SGP32_PendingNotification),
	offsetof(struct SGP32_PendingNotification, _asn_ctx),
	offsetof(struct SGP32_PendingNotification, present),
	sizeof(((struct SGP32_PendingNotification *)0)->present),
	asn_MAP_SGP32_PendingNotification_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0,
	4	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_SGP32_PendingNotification = {
	"SGP32-PendingNotification",
	"SGP32-PendingNotification",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_SGP32_PendingNotification_1,
	4,	/* Elements count */
	&asn_SPC_SGP32_PendingNotification_specs_1	/* Additional specs */
};

