/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#ifndef	_SGP32_SetDefaultDpAddressRequest_H_
#define	_SGP32_SetDefaultDpAddressRequest_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SGP32-SetDefaultDpAddressRequest */
typedef struct SGP32_SetDefaultDpAddressRequest {
	UTF8String_t	 defaultDpAddress;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGP32_SetDefaultDpAddressRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGP32_SetDefaultDpAddressRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_SGP32_SetDefaultDpAddressRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_SGP32_SetDefaultDpAddressRequest_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SGP32_SetDefaultDpAddressRequest_H_ */
#include <asn_internal.h>
