/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_SGP32_CancelSessionResponse_H_
#define	_SGP32_CancelSessionResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "CancelSessionResponseOk.h"
#include <NativeInteger.h>
#include "CompactCancelSessionResponseOk.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SGP32_CancelSessionResponse_PR {
	SGP32_CancelSessionResponse_PR_NOTHING,	/* No components present */
	SGP32_CancelSessionResponse_PR_cancelSessionResponseOk,
	SGP32_CancelSessionResponse_PR_cancelSessionResponseError,
	SGP32_CancelSessionResponse_PR_compactCancelSessionResponseOk
	/* Extensions may appear below */
	
} SGP32_CancelSessionResponse_PR;
typedef enum SGP32_CancelSessionResponse__cancelSessionResponseError {
	SGP32_CancelSessionResponse__cancelSessionResponseError_invalidTransactionId	= 5,
	SGP32_CancelSessionResponse__cancelSessionResponseError_undefinedError	= 127
} e_SGP32_CancelSessionResponse__cancelSessionResponseError;

/* SGP32-CancelSessionResponse */
typedef struct SGP32_CancelSessionResponse {
	SGP32_CancelSessionResponse_PR present;
	union SGP32_CancelSessionResponse_u {
		CancelSessionResponseOk_t	 cancelSessionResponseOk;
		long	 cancelSessionResponseError;
		CompactCancelSessionResponseOk_t	 compactCancelSessionResponseOk;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGP32_CancelSessionResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGP32_CancelSessionResponse;
extern asn_CHOICE_specifics_t asn_SPC_SGP32_CancelSessionResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_SGP32_CancelSessionResponse_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SGP32_CancelSessionResponse_H_ */
#include <asn_internal.h>
