/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_SGP32_RetrieveNotificationsListResponse_H_
#define	_SGP32_RetrieveNotificationsListResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SGP32_RetrieveNotificationsListResponse_PR {
	SGP32_RetrieveNotificationsListResponse_PR_NOTHING,	/* No components present */
	SGP32_RetrieveNotificationsListResponse_PR_notificationList,
	SGP32_RetrieveNotificationsListResponse_PR_notificationsListResultError,
	SGP32_RetrieveNotificationsListResponse_PR_euiccPackageResultList,
	SGP32_RetrieveNotificationsListResponse_PR_notificationAndEprList
	/* Extensions may appear below */
	
} SGP32_RetrieveNotificationsListResponse_PR;
typedef enum SGP32_RetrieveNotificationsListResponse__notificationsListResultError {
	SGP32_RetrieveNotificationsListResponse__notificationsListResultError_undefinedError	= 127
} e_SGP32_RetrieveNotificationsListResponse__notificationsListResultError;

/* Forward declarations */
struct SGP32_PendingNotification;
struct EuiccPackageResult;

/* SGP32-RetrieveNotificationsListResponse */
typedef struct SGP32_RetrieveNotificationsListResponse {
	SGP32_RetrieveNotificationsListResponse_PR present;
	union SGP32_RetrieveNotificationsListResponse_u {
		struct SGP32_RetrieveNotificationsListResponse__notificationList {
			A_SEQUENCE_OF(struct SGP32_PendingNotification) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} notificationList;
		long	 notificationsListResultError;
		struct SGP32_RetrieveNotificationsListResponse__euiccPackageResultList {
			A_SEQUENCE_OF(struct EuiccPackageResult) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} euiccPackageResultList;
		struct SGP32_RetrieveNotificationsListResponse__notificationAndEprList {
			struct SGP32_RetrieveNotificationsListResponse__notificationAndEprList__notificationList {
				A_SEQUENCE_OF(struct SGP32_PendingNotification) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} notificationList;
			struct SGP32_RetrieveNotificationsListResponse__notificationAndEprList__euiccPackageResultList {
				A_SEQUENCE_OF(struct EuiccPackageResult) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} euiccPackageResultList;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} notificationAndEprList;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SGP32_RetrieveNotificationsListResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SGP32_RetrieveNotificationsListResponse;
extern asn_CHOICE_specifics_t asn_SPC_SGP32_RetrieveNotificationsListResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_SGP32_RetrieveNotificationsListResponse_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SGP32-PendingNotification.h"
#include "EuiccPackageResult.h"

#endif	/* _SGP32_RetrieveNotificationsListResponse_H_ */
#include <asn_internal.h>
