/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "SGP32-EuiccMemoryResetRequest.h"

static asn_TYPE_member_t asn_MBR_SGP32_EuiccMemoryResetRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SGP32_EuiccMemoryResetRequest, resetOptions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BIT_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"resetOptions"
		},
};
static const ber_tlv_tag_t asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (100 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SGP32_EuiccMemoryResetRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 0 } /* resetOptions */
};
static asn_SEQUENCE_specifics_t asn_SPC_SGP32_EuiccMemoryResetRequest_specs_1 = {
	sizeof(struct SGP32_EuiccMemoryResetRequest),
	offsetof(struct SGP32_EuiccMemoryResetRequest, _asn_ctx),
	asn_MAP_SGP32_EuiccMemoryResetRequest_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SGP32_EuiccMemoryResetRequest = {
	"SGP32-EuiccMemoryResetRequest",
	"SGP32-EuiccMemoryResetRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1,
	sizeof(asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1)
		/sizeof(asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1)
		/sizeof(asn_DEF_SGP32_EuiccMemoryResetRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SGP32_EuiccMemoryResetRequest_1,
	1,	/* Elements count */
	&asn_SPC_SGP32_EuiccMemoryResetRequest_specs_1	/* Additional specs */
};

