/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#include "StoreMetadataRequest.h"

static int
memb_serviceProviderName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 32)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_profileName_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const UTF8String_t *st = (const UTF8String_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = UTF8String_length(st);
	if((ssize_t)size < 0) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: UTF-8: broken encoding (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	if((size <= 64)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_icon_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size <= 1024)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int asn_DFL_7_cmp_2(const void *sptr) {
	const ProfileClass_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 2 */
	return (*st != 2);
}
static int asn_DFL_7_set_2(void **sptr) {
	ProfileClass_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 2 */
	*st = 2;
	return 0;
}
static asn_TYPE_member_t asn_MBR_notificationConfigurationInfo_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NotificationConfigurationInformation,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_notificationConfigurationInfo_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_notificationConfigurationInfo_specs_8 = {
	sizeof(struct StoreMetadataRequest__notificationConfigurationInfo),
	offsetof(struct StoreMetadataRequest__notificationConfigurationInfo, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_notificationConfigurationInfo_8 = {
	"notificationConfigurationInfo",
	"notificationConfigurationInfo",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_notificationConfigurationInfo_tags_8,
	sizeof(asn_DEF_notificationConfigurationInfo_tags_8)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_8[0]) - 1, /* 1 */
	asn_DEF_notificationConfigurationInfo_tags_8,	/* Same as above */
	sizeof(asn_DEF_notificationConfigurationInfo_tags_8)
		/sizeof(asn_DEF_notificationConfigurationInfo_tags_8[0]), /* 2 */
	{ 0, 0, SEQUENCE_OF_constraint },
	asn_MBR_notificationConfigurationInfo_8,
	1,	/* Single element */
	&asn_SPC_notificationConfigurationInfo_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_StoreMetadataRequest_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, iccid),
		(ASN_TAG_CLASS_APPLICATION | (26 << 2)),
		0,
		&asn_DEF_Iccid,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iccid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0,  memb_serviceProviderName_constraint_1 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct StoreMetadataRequest, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0,  memb_profileName_constraint_1 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 8, offsetof(struct StoreMetadataRequest, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 7, offsetof(struct StoreMetadataRequest, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0,  memb_icon_constraint_1 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 6, offsetof(struct StoreMetadataRequest, profileClass),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProfileClass,
		0,
		{ 0, 0, 0 },
		&asn_DFL_7_cmp_2,	/* Compare DEFAULT 2 */
		&asn_DFL_7_set_2,	/* Set DEFAULT 2 */
		"profileClass"
		},
	{ ATF_POINTER, 5, offsetof(struct StoreMetadataRequest, notificationConfigurationInfo),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		0,
		&asn_DEF_notificationConfigurationInfo_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationConfigurationInfo"
		},
	{ ATF_POINTER, 4, offsetof(struct StoreMetadataRequest, profileOwner),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OperatorId,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileOwner"
		},
	{ ATF_POINTER, 3, offsetof(struct StoreMetadataRequest, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
	{ ATF_POINTER, 2, offsetof(struct StoreMetadataRequest, serviceSpecificDataStoredInEuicc),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceSpecificDataStoredInEuicc"
		},
	{ ATF_POINTER, 1, offsetof(struct StoreMetadataRequest, serviceSpecificDataNotStoredInEuicc),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceSpecificDataNotStoredInEuicc"
		},
};
static const ber_tlv_tag_t asn_DEF_StoreMetadataRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (37 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_StoreMetadataRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_APPLICATION | (26 << 2)), 0, 0, 0 }, /* iccid */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 1, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 2, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 3, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 4, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 5, 0, 0 }, /* profileClass */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 6, 0, 0 }, /* notificationConfigurationInfo */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 7, 0, 0 }, /* profileOwner */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 8, 0, 0 }, /* profilePolicyRules */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 9, 0, 0 }, /* serviceSpecificDataStoredInEuicc */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 10, 0, 0 } /* serviceSpecificDataNotStoredInEuicc */
};
asn_SEQUENCE_specifics_t asn_SPC_StoreMetadataRequest_specs_1 = {
	sizeof(struct StoreMetadataRequest),
	offsetof(struct StoreMetadataRequest, _asn_ctx),
	asn_MAP_StoreMetadataRequest_tag2el_1,
	11,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	11,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_StoreMetadataRequest = {
	"StoreMetadataRequest",
	"StoreMetadataRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_StoreMetadataRequest_tags_1,
	sizeof(asn_DEF_StoreMetadataRequest_tags_1)
		/sizeof(asn_DEF_StoreMetadataRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_StoreMetadataRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_StoreMetadataRequest_tags_1)
		/sizeof(asn_DEF_StoreMetadataRequest_tags_1[0]), /* 2 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_StoreMetadataRequest_1,
	11,	/* Elements count */
	&asn_SPC_StoreMetadataRequest_specs_1	/* Additional specs */
};

