/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "SuccessResult.h"

asn_TYPE_member_t asn_MBR_SuccessResult_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SuccessResult, aid),
		(ASN_TAG_CLASS_APPLICATION | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aid"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SuccessResult, simaResponse),
		(ASN_TAG_CLASS_UNIVERSAL | (4 << 2)),
		0,
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"simaResponse"
		},
};
static const ber_tlv_tag_t asn_DEF_SuccessResult_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SuccessResult_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (4 << 2)), 1, 0, 0 }, /* simaResponse */
    { (ASN_TAG_CLASS_APPLICATION | (15 << 2)), 0, 0, 0 } /* aid */
};
asn_SEQUENCE_specifics_t asn_SPC_SuccessResult_specs_1 = {
	sizeof(struct SuccessResult),
	offsetof(struct SuccessResult, _asn_ctx),
	asn_MAP_SuccessResult_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SuccessResult = {
	"SuccessResult",
	"SuccessResult",
	&asn_OP_SEQUENCE,
	asn_DEF_SuccessResult_tags_1,
	sizeof(asn_DEF_SuccessResult_tags_1)
		/sizeof(asn_DEF_SuccessResult_tags_1[0]), /* 1 */
	asn_DEF_SuccessResult_tags_1,	/* Same as above */
	sizeof(asn_DEF_SuccessResult_tags_1)
		/sizeof(asn_DEF_SuccessResult_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_SuccessResult_1,
	2,	/* Elements count */
	&asn_SPC_SuccessResult_specs_1	/* Additional specs */
};

