/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "../../../asn1/PKIX1Explicit88.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "TeletexDomainDefinedAttribute.h"

asn_TYPE_member_t asn_MBR_TeletexDomainDefinedAttribute_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TeletexDomainDefinedAttribute, type),
		(ASN_TAG_CLASS_UNIVERSAL | (20 << 2)),
		0,
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TeletexDomainDefinedAttribute, value),
		(ASN_TAG_CLASS_UNIVERSAL | (20 << 2)),
		0,
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_TeletexDomainDefinedAttribute_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TeletexDomainDefinedAttribute_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 0, 0, 1 }, /* type */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 1, -1, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_TeletexDomainDefinedAttribute_specs_1 = {
	sizeof(struct TeletexDomainDefinedAttribute),
	offsetof(struct TeletexDomainDefinedAttribute, _asn_ctx),
	asn_MAP_TeletexDomainDefinedAttribute_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TeletexDomainDefinedAttribute = {
	"TeletexDomainDefinedAttribute",
	"TeletexDomainDefinedAttribute",
	&asn_OP_SEQUENCE,
	asn_DEF_TeletexDomainDefinedAttribute_tags_1,
	sizeof(asn_DEF_TeletexDomainDefinedAttribute_tags_1)
		/sizeof(asn_DEF_TeletexDomainDefinedAttribute_tags_1[0]), /* 1 */
	asn_DEF_TeletexDomainDefinedAttribute_tags_1,	/* Same as above */
	sizeof(asn_DEF_TeletexDomainDefinedAttribute_tags_1)
		/sizeof(asn_DEF_TeletexDomainDefinedAttribute_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_TeletexDomainDefinedAttribute_1,
	2,	/* Elements count */
	&asn_SPC_TeletexDomainDefinedAttribute_specs_1	/* Additional specs */
};

