/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "../../../asn1/PKIX1Explicit88.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "TeletexPersonalName.h"

static asn_TYPE_member_t asn_MBR_TeletexPersonalName_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TeletexPersonalName, surname),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"surname"
		},
	{ ATF_POINTER, 3, offsetof(struct TeletexPersonalName, given_name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"given-name"
		},
	{ ATF_POINTER, 2, offsetof(struct TeletexPersonalName, initials),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"initials"
		},
	{ ATF_POINTER, 1, offsetof(struct TeletexPersonalName, generation_qualifier),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"generation-qualifier"
		},
};
static const ber_tlv_tag_t asn_DEF_TeletexPersonalName_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (17 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TeletexPersonalName_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* surname */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* given-name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* initials */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* generation-qualifier */
};
static const uint8_t asn_MAP_TeletexPersonalName_mmap_1[(4 + (8 * sizeof(unsigned int)) - 1) / 8] = {
	(1 << 7) | (0 << 6) | (0 << 5) | (0 << 4)
};
static 
asn_SET_specifics_t asn_SPC_TeletexPersonalName_specs_1 = {
	sizeof(struct TeletexPersonalName),
	offsetof(struct TeletexPersonalName, _asn_ctx),
	offsetof(struct TeletexPersonalName, _presence_map),
	asn_MAP_TeletexPersonalName_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_TeletexPersonalName_tag2el_1,	/* Same as above */
	4,	/* Count of tags in the CXER map */
	0,	/* Whether extensible */
	(const unsigned int *)asn_MAP_TeletexPersonalName_mmap_1	/* Mandatory elements map */
};
asn_TYPE_descriptor_t asn_DEF_TeletexPersonalName = {
	"TeletexPersonalName",
	"TeletexPersonalName",
	&asn_OP_SET,
	asn_DEF_TeletexPersonalName_tags_1,
	sizeof(asn_DEF_TeletexPersonalName_tags_1)
		/sizeof(asn_DEF_TeletexPersonalName_tags_1[0]), /* 1 */
	asn_DEF_TeletexPersonalName_tags_1,	/* Same as above */
	sizeof(asn_DEF_TeletexPersonalName_tags_1)
		/sizeof(asn_DEF_TeletexPersonalName_tags_1[0]), /* 1 */
	{ 0, 0, 0 },
	asn_MBR_TeletexPersonalName_1,
	4,	/* Elements count */
	&asn_SPC_TeletexPersonalName_specs_1	/* Additional specs */
};

