/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example`
 */

#include "TransferEimPackageResponse.h"

static asn_oer_constraints_t asn_OER_type_TransferEimPackageResponse_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_TransferEimPackageResponse_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_ePRAndNotifications_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse__ePRAndNotifications, euiccPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse__ePRAndNotifications, notificationList),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PendingNotificationList,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"notificationList"
		},
};
static const ber_tlv_tag_t asn_DEF_ePRAndNotifications_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ePRAndNotifications_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 1, 0, 0 }, /* notificationList */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 } /* euiccPackageResult */
};
static asn_SEQUENCE_specifics_t asn_SPC_ePRAndNotifications_specs_3 = {
	sizeof(struct TransferEimPackageResponse__ePRAndNotifications),
	offsetof(struct TransferEimPackageResponse__ePRAndNotifications, _asn_ctx),
	asn_MAP_ePRAndNotifications_tag2el_3,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ePRAndNotifications_3 = {
	"ePRAndNotifications",
	"ePRAndNotifications",
	&asn_OP_SEQUENCE,
	asn_DEF_ePRAndNotifications_tags_3,
	sizeof(asn_DEF_ePRAndNotifications_tags_3)
		/sizeof(asn_DEF_ePRAndNotifications_tags_3[0]), /* 1 */
	asn_DEF_ePRAndNotifications_tags_3,	/* Same as above */
	sizeof(asn_DEF_ePRAndNotifications_tags_3)
		/sizeof(asn_DEF_ePRAndNotifications_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ePRAndNotifications_3,
	2,	/* Elements count */
	&asn_SPC_ePRAndNotifications_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_TransferEimPackageResponse_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse, choice.euiccPackageResult),
		(ASN_TAG_CLASS_CONTEXT | (81 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EuiccPackageResult,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"euiccPackageResult"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse, choice.ePRAndNotifications),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_ePRAndNotifications_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ePRAndNotifications"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse, choice.ipaEuiccDataResponse),
		(ASN_TAG_CLASS_CONTEXT | (82 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IpaEuiccDataResponse,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ipaEuiccDataResponse"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse, choice.eimPackageReceived),
		(ASN_TAG_CLASS_UNIVERSAL | (5 << 2)),
		0,
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimPackageReceived"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TransferEimPackageResponse, choice.eimPackageError),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eimPackageError"
		},
};
static const unsigned asn_MAP_TransferEimPackageResponse_to_canonical_1[] = { 4, 3, 1, 0, 2 };
static const unsigned asn_MAP_TransferEimPackageResponse_from_canonical_1[] = { 3, 2, 4, 1, 0 };
static const ber_tlv_tag_t asn_DEF_TransferEimPackageResponse_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (78 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TransferEimPackageResponse_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 4, 0, 0 }, /* eimPackageError */
    { (ASN_TAG_CLASS_UNIVERSAL | (5 << 2)), 3, 0, 0 }, /* eimPackageReceived */
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 1, 0, 0 }, /* ePRAndNotifications */
    { (ASN_TAG_CLASS_CONTEXT | (81 << 2)), 0, 0, 0 }, /* euiccPackageResult */
    { (ASN_TAG_CLASS_CONTEXT | (82 << 2)), 2, 0, 0 } /* ipaEuiccDataResponse */
};
asn_CHOICE_specifics_t asn_SPC_TransferEimPackageResponse_specs_1 = {
	sizeof(struct TransferEimPackageResponse),
	offsetof(struct TransferEimPackageResponse, _asn_ctx),
	offsetof(struct TransferEimPackageResponse, present),
	sizeof(((struct TransferEimPackageResponse *)0)->present),
	asn_MAP_TransferEimPackageResponse_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_TransferEimPackageResponse_to_canonical_1,
	asn_MAP_TransferEimPackageResponse_from_canonical_1,
	5	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TransferEimPackageResponse = {
	"TransferEimPackageResponse",
	"TransferEimPackageResponse",
	&asn_OP_CHOICE,
	asn_DEF_TransferEimPackageResponse_tags_1,
	sizeof(asn_DEF_TransferEimPackageResponse_tags_1)
		/sizeof(asn_DEF_TransferEimPackageResponse_tags_1[0]), /* 1 */
	asn_DEF_TransferEimPackageResponse_tags_1,	/* Same as above */
	sizeof(asn_DEF_TransferEimPackageResponse_tags_1)
		/sizeof(asn_DEF_TransferEimPackageResponse_tags_1[0]), /* 1 */
	{ &asn_OER_type_TransferEimPackageResponse_constr_1, &asn_PER_type_TransferEimPackageResponse_constr_1, CHOICE_constraint },
	asn_MBR_TransferEimPackageResponse_1,
	5,	/* Elements count */
	&asn_SPC_TransferEimPackageResponse_specs_1	/* Additional specs */
};

