/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SGP32Definitions"
 * 	found in "../../../asn1/SGP32Definitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_TransferEimPackageResponse_H_
#define	_TransferEimPackageResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "EuiccPackageResult.h"
#include "IpaEuiccDataResponse.h"
#include <NULL.h>
#include <NativeInteger.h>
#include "SGP32-RetrieveNotificationsListResponse.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TransferEimPackageResponse_PR {
	TransferEimPackageResponse_PR_NOTHING,	/* No components present */
	TransferEimPackageResponse_PR_euiccPackageResult,
	TransferEimPackageResponse_PR_ePRAndNotifications,
	TransferEimPackageResponse_PR_ipaEuiccDataResponse,
	TransferEimPackageResponse_PR_eimPackageReceived,
	TransferEimPackageResponse_PR_eimPackageError
	/* Extensions may appear below */
	
} TransferEimPackageResponse_PR;
typedef enum TransferEimPackageResponse__eimPackageError {
	TransferEimPackageResponse__eimPackageError_invalidPackageFormat	= 1,
	TransferEimPackageResponse__eimPackageError_unknownPackage	= 2,
	TransferEimPackageResponse__eimPackageError_undefinedError	= 127
} e_TransferEimPackageResponse__eimPackageError;

/* TransferEimPackageResponse */
typedef struct TransferEimPackageResponse {
	TransferEimPackageResponse_PR present;
	union TransferEimPackageResponse_u {
		EuiccPackageResult_t	 euiccPackageResult;
		struct TransferEimPackageResponse__ePRAndNotifications {
			EuiccPackageResult_t	 euiccPackageResult;
			SGP32_RetrieveNotificationsListResponse_t	 notificationList;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} ePRAndNotifications;
		IpaEuiccDataResponse_t	 ipaEuiccDataResponse;
		NULL_t	 eimPackageReceived;
		long	 eimPackageError;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TransferEimPackageResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TransferEimPackageResponse;
extern asn_CHOICE_specifics_t asn_SPC_TransferEimPackageResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_TransferEimPackageResponse_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _TransferEimPackageResponse_H_ */
#include <asn_internal.h>
