/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PEDefinitions"
 * 	found in "../../../asn1/PEDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_UICCApplicationParameters_H_
#define	_UICCApplicationParameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UICCApplicationParameters */
typedef struct UICCApplicationParameters {
	OCTET_STRING_t	*uiccToolkitApplicationSpecificParametersField	/* OPTIONAL */;
	OCTET_STRING_t	*uiccAccessApplicationSpecificParametersField	/* OPTIONAL */;
	OCTET_STRING_t	*uiccAdministrativeAccessApplicationSpecificParametersField	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UICCApplicationParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UICCApplicationParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_UICCApplicationParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_UICCApplicationParameters_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UICCApplicationParameters_H_ */
#include <asn_internal.h>
