/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "UpdateMetadataRequest.h"

static asn_TYPE_member_t asn_MBR_UpdateMetadataRequest_1[] = {
	{ ATF_POINTER, 6, offsetof(struct UpdateMetadataRequest, serviceProviderName),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceProviderName"
		},
	{ ATF_POINTER, 5, offsetof(struct UpdateMetadataRequest, profileName),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profileName"
		},
	{ ATF_POINTER, 4, offsetof(struct UpdateMetadataRequest, iconType),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IconType,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iconType"
		},
	{ ATF_POINTER, 3, offsetof(struct UpdateMetadataRequest, icon),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"icon"
		},
	{ ATF_POINTER, 2, offsetof(struct UpdateMetadataRequest, profilePolicyRules),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PprIds,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"profilePolicyRules"
		},
	{ ATF_POINTER, 1, offsetof(struct UpdateMetadataRequest, serviceSpecificDataStoredInEuicc),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VendorSpecificExtension,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"serviceSpecificDataStoredInEuicc"
		},
};
static const ber_tlv_tag_t asn_DEF_UpdateMetadataRequest_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (42 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UpdateMetadataRequest_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 0, 0, 0 }, /* serviceProviderName */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 1, 0, 0 }, /* profileName */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 2, 0, 0 }, /* iconType */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 3, 0, 0 }, /* icon */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 4, 0, 0 }, /* profilePolicyRules */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 5, 0, 0 } /* serviceSpecificDataStoredInEuicc */
};
static asn_SEQUENCE_specifics_t asn_SPC_UpdateMetadataRequest_specs_1 = {
	sizeof(struct UpdateMetadataRequest),
	offsetof(struct UpdateMetadataRequest, _asn_ctx),
	asn_MAP_UpdateMetadataRequest_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UpdateMetadataRequest = {
	"UpdateMetadataRequest",
	"UpdateMetadataRequest",
	&asn_OP_SEQUENCE,
	asn_DEF_UpdateMetadataRequest_tags_1,
	sizeof(asn_DEF_UpdateMetadataRequest_tags_1)
		/sizeof(asn_DEF_UpdateMetadataRequest_tags_1[0]) - 1, /* 1 */
	asn_DEF_UpdateMetadataRequest_tags_1,	/* Same as above */
	sizeof(asn_DEF_UpdateMetadataRequest_tags_1)
		/sizeof(asn_DEF_UpdateMetadataRequest_tags_1[0]), /* 2 */
	{ 0, 0, 0 },
	asn_MBR_UpdateMetadataRequest_1,
	6,	/* Elements count */
	&asn_SPC_UpdateMetadataRequest_specs_1	/* Additional specs */
};

