/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "RSPDefinitions"
 * 	found in "../../../asn1/RSPDefinitions.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER`
 */

#ifndef	_VendorSpecificExtension_H_
#define	_VendorSpecificExtension_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <OBJECT_IDENTIFIER.h>
#include <ANY.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct VendorSpecificExtension__Member {
	OBJECT_IDENTIFIER_t	 vendorOid;
	ANY_t	 vendorSpecificData;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VendorSpecificExtension__Member;

/* VendorSpecificExtension */
typedef struct VendorSpecificExtension {
	A_SEQUENCE_OF(VendorSpecificExtension__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VendorSpecificExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VendorSpecificExtension;
extern asn_SET_OF_specifics_t asn_SPC_VendorSpecificExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_VendorSpecificExtension_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _VendorSpecificExtension_H_ */
#include <asn_internal.h>
