/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PKIX1Explicit88"
 * 	found in "../../../asn1/PKIX1Explicit88.asn"
 * 	`asn1c -fcompound-names -no-gen-example -no-gen-OER -no-gen-PER -fno-constraints`
 */

#include "X520Title.h"

static asn_TYPE_member_t asn_MBR_X520Title_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct X520Title, choice.teletexString),
		(ASN_TAG_CLASS_UNIVERSAL | (20 << 2)),
		0,
		&asn_DEF_TeletexString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"teletexString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X520Title, choice.printableString),
		(ASN_TAG_CLASS_UNIVERSAL | (19 << 2)),
		0,
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"printableString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X520Title, choice.universalString),
		(ASN_TAG_CLASS_UNIVERSAL | (28 << 2)),
		0,
		&asn_DEF_UniversalString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"universalString"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X520Title, choice.utf8String),
		(ASN_TAG_CLASS_UNIVERSAL | (12 << 2)),
		0,
		&asn_DEF_UTF8String,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"utf8String"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct X520Title, choice.bmpString),
		(ASN_TAG_CLASS_UNIVERSAL | (30 << 2)),
		0,
		&asn_DEF_BMPString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"bmpString"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_X520Title_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (12 << 2)), 3, 0, 0 }, /* utf8String */
    { (ASN_TAG_CLASS_UNIVERSAL | (19 << 2)), 1, 0, 0 }, /* printableString */
    { (ASN_TAG_CLASS_UNIVERSAL | (20 << 2)), 0, 0, 0 }, /* teletexString */
    { (ASN_TAG_CLASS_UNIVERSAL | (28 << 2)), 2, 0, 0 }, /* universalString */
    { (ASN_TAG_CLASS_UNIVERSAL | (30 << 2)), 4, 0, 0 } /* bmpString */
};
static asn_CHOICE_specifics_t asn_SPC_X520Title_specs_1 = {
	sizeof(struct X520Title),
	offsetof(struct X520Title, _asn_ctx),
	offsetof(struct X520Title, present),
	sizeof(((struct X520Title *)0)->present),
	asn_MAP_X520Title_tag2el_1,
	5,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_X520Title = {
	"X520Title",
	"X520Title",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, 0, 0 },
	asn_MBR_X520Title_1,
	5,	/* Elements count */
	&asn_SPC_X520Title_specs_1	/* Additional specs */
};

